package android.icu.text;

class RBBIRuleParseTable {
    static final short doCheckVarDef = (short) 1;
    static final short doDotAny = (short) 2;
    static final short doEndAssign = (short) 3;
    static final short doEndOfRule = (short) 4;
    static final short doEndVariableName = (short) 5;
    static final short doExit = (short) 6;
    static final short doExprCatOperator = (short) 7;
    static final short doExprFinished = (short) 8;
    static final short doExprOrOperator = (short) 9;
    static final short doExprRParen = (short) 10;
    static final short doExprStart = (short) 11;
    static final short doLParen = (short) 12;
    static final short doNOP = (short) 13;
    static final short doNoChain = (short) 14;
    static final short doOptionEnd = (short) 15;
    static final short doOptionStart = (short) 16;
    static final short doReverseDir = (short) 17;
    static final short doRuleChar = (short) 18;
    static final short doRuleError = (short) 19;
    static final short doRuleErrorAssignExpr = (short) 20;
    static final short doScanUnicodeSet = (short) 21;
    static final short doSlash = (short) 22;
    static final short doStartAssign = (short) 23;
    static final short doStartTagValue = (short) 24;
    static final short doStartVariableName = (short) 25;
    static final short doTagDigit = (short) 26;
    static final short doTagExpectedError = (short) 27;
    static final short doTagValue = (short) 28;
    static final short doUnaryOpPlus = (short) 29;
    static final short doUnaryOpQuestion = (short) 30;
    static final short doUnaryOpStar = (short) 31;
    static final short doVariableNameExpectedErr = (short) 32;
    static RBBIRuleTableElement[] gRuleParseStateTable = null;
    static final short kRuleSet_default = (short) 255;
    static final short kRuleSet_digit_char = (short) 128;
    static final short kRuleSet_eof = (short) 252;
    static final short kRuleSet_escaped = (short) 254;
    static final short kRuleSet_name_char = (short) 129;
    static final short kRuleSet_name_start_char = (short) 130;
    static final short kRuleSet_rule_char = (short) 131;
    static final short kRuleSet_white_space = (short) 132;

    static class RBBIRuleTableElement {
        short fAction;
        short fCharClass;
        boolean fNextChar;
        short fNextState;
        short fPushState;
        String fStateName;

        RBBIRuleTableElement(short a, int cc, int ns, int ps, boolean nc, String sn) {
            this.fAction = a;
            this.fCharClass = (short) cc;
            this.fNextState = (short) ns;
            this.fPushState = (short) ps;
            this.fNextChar = nc;
            this.fStateName = sn;
        }
    }

    RBBIRuleParseTable() {
    }

    static {
        RBBIRuleTableElement[] rBBIRuleTableElementArr = new RBBIRuleTableElement[104];
        rBBIRuleTableElementArr[0] = new RBBIRuleTableElement((short) 13, 0, 0, 0, true, null);
        rBBIRuleTableElementArr[1] = new RBBIRuleTableElement((short) 11, 254, 29, 9, false, "start");
        rBBIRuleTableElementArr[2] = new RBBIRuleTableElement((short) 13, 132, 1, 0, true, null);
        rBBIRuleTableElementArr[3] = new RBBIRuleTableElement((short) 14, 94, 12, 9, true, null);
        rBBIRuleTableElementArr[4] = new RBBIRuleTableElement((short) 11, 36, 88, 98, false, null);
        rBBIRuleTableElementArr[5] = new RBBIRuleTableElement((short) 13, 33, 19, 0, true, null);
        rBBIRuleTableElementArr[6] = new RBBIRuleTableElement((short) 13, 59, 1, 0, true, null);
        rBBIRuleTableElementArr[7] = new RBBIRuleTableElement((short) 13, 252, 0, 0, false, null);
        rBBIRuleTableElementArr[8] = new RBBIRuleTableElement((short) 11, 255, 29, 9, false, null);
        rBBIRuleTableElementArr[9] = new RBBIRuleTableElement((short) 4, 59, 1, 0, true, "break-rule-end");
        rBBIRuleTableElementArr[10] = new RBBIRuleTableElement((short) 13, 132, 9, 0, true, null);
        rBBIRuleTableElementArr[11] = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[12] = new RBBIRuleTableElement((short) 11, 254, 29, 0, false, "start-after-caret");
        rBBIRuleTableElementArr[13] = new RBBIRuleTableElement((short) 13, 132, 12, 0, true, null);
        rBBIRuleTableElementArr[14] = new RBBIRuleTableElement(doRuleError, 94, 103, 0, false, null);
        rBBIRuleTableElementArr[15] = new RBBIRuleTableElement((short) 11, 36, 88, 37, false, null);
        rBBIRuleTableElementArr[16] = new RBBIRuleTableElement(doRuleError, 59, 103, 0, false, null);
        rBBIRuleTableElementArr[17] = new RBBIRuleTableElement(doRuleError, 252, 103, 0, false, null);
        rBBIRuleTableElementArr[18] = new RBBIRuleTableElement((short) 11, 255, 29, 0, false, null);
        rBBIRuleTableElementArr[19] = new RBBIRuleTableElement((short) 13, 33, 21, 0, true, "rev-option");
        rBBIRuleTableElementArr[20] = new RBBIRuleTableElement((short) 17, 255, 28, 9, false, null);
        rBBIRuleTableElementArr[21] = new RBBIRuleTableElement((short) 16, 130, 23, 0, true, "option-scan1");
        rBBIRuleTableElementArr[22] = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[23] = new RBBIRuleTableElement((short) 13, 129, 23, 0, true, "option-scan2");
        rBBIRuleTableElementArr[24] = new RBBIRuleTableElement((short) 15, 255, 25, 0, false, null);
        rBBIRuleTableElementArr[25] = new RBBIRuleTableElement((short) 13, 59, 1, 0, true, "option-scan3");
        rBBIRuleTableElementArr[26] = new RBBIRuleTableElement((short) 13, 132, 25, 0, true, null);
        rBBIRuleTableElementArr[27] = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[28] = new RBBIRuleTableElement((short) 11, 255, 29, 9, false, "reverse-rule");
        rBBIRuleTableElementArr[29] = new RBBIRuleTableElement(doRuleChar, 254, 38, 0, true, "term");
        rBBIRuleTableElementArr[30] = new RBBIRuleTableElement((short) 13, 132, 29, 0, true, null);
        rBBIRuleTableElementArr[31] = new RBBIRuleTableElement(doRuleChar, 131, 38, 0, true, null);
        rBBIRuleTableElementArr[32] = new RBBIRuleTableElement((short) 13, 91, 94, 38, false, null);
        rBBIRuleTableElementArr[33] = new RBBIRuleTableElement((short) 12, 40, 29, 38, true, null);
        rBBIRuleTableElementArr[34] = new RBBIRuleTableElement((short) 13, 36, 88, 37, false, null);
        rBBIRuleTableElementArr[35] = new RBBIRuleTableElement((short) 2, 46, 38, 0, true, null);
        rBBIRuleTableElementArr[36] = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[37] = new RBBIRuleTableElement((short) 1, 255, 38, 0, false, "term-var-ref");
        rBBIRuleTableElementArr[38] = new RBBIRuleTableElement((short) 13, 132, 38, 0, true, "expr-mod");
        rBBIRuleTableElementArr[39] = new RBBIRuleTableElement(doUnaryOpStar, 42, 43, 0, true, null);
        rBBIRuleTableElementArr[40] = new RBBIRuleTableElement(doUnaryOpPlus, 43, 43, 0, true, null);
        rBBIRuleTableElementArr[41] = new RBBIRuleTableElement(doUnaryOpQuestion, 63, 43, 0, true, null);
        rBBIRuleTableElementArr[42] = new RBBIRuleTableElement((short) 13, 255, 43, 0, false, null);
        rBBIRuleTableElementArr[43] = new RBBIRuleTableElement((short) 7, 254, 29, 0, false, "expr-cont");
        rBBIRuleTableElementArr[44] = new RBBIRuleTableElement((short) 13, 132, 43, 0, true, null);
        rBBIRuleTableElementArr[45] = new RBBIRuleTableElement((short) 7, 131, 29, 0, false, null);
        rBBIRuleTableElementArr[46] = new RBBIRuleTableElement((short) 7, 91, 29, 0, false, null);
        rBBIRuleTableElementArr[47] = new RBBIRuleTableElement((short) 7, 40, 29, 0, false, null);
        rBBIRuleTableElementArr[48] = new RBBIRuleTableElement((short) 7, 36, 29, 0, false, null);
        rBBIRuleTableElementArr[49] = new RBBIRuleTableElement((short) 7, 46, 29, 0, false, null);
        rBBIRuleTableElementArr[50] = new RBBIRuleTableElement((short) 7, 47, 55, 0, false, null);
        rBBIRuleTableElementArr[51] = new RBBIRuleTableElement((short) 7, 123, 67, 0, true, null);
        rBBIRuleTableElementArr[52] = new RBBIRuleTableElement((short) 9, 124, 29, 0, true, null);
        rBBIRuleTableElementArr[53] = new RBBIRuleTableElement((short) 10, 41, 255, 0, true, null);
        rBBIRuleTableElementArr[54] = new RBBIRuleTableElement((short) 8, 255, 255, 0, false, null);
        rBBIRuleTableElementArr[55] = new RBBIRuleTableElement(doSlash, 47, 57, 0, true, "look-ahead");
        rBBIRuleTableElementArr[56] = new RBBIRuleTableElement((short) 13, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[57] = new RBBIRuleTableElement((short) 7, 254, 29, 0, false, "expr-cont-no-slash");
        rBBIRuleTableElementArr[58] = new RBBIRuleTableElement((short) 13, 132, 43, 0, true, null);
        rBBIRuleTableElementArr[59] = new RBBIRuleTableElement((short) 7, 131, 29, 0, false, null);
        rBBIRuleTableElementArr[60] = new RBBIRuleTableElement((short) 7, 91, 29, 0, false, null);
        rBBIRuleTableElementArr[61] = new RBBIRuleTableElement((short) 7, 40, 29, 0, false, null);
        rBBIRuleTableElementArr[62] = new RBBIRuleTableElement((short) 7, 36, 29, 0, false, null);
        rBBIRuleTableElementArr[63] = new RBBIRuleTableElement((short) 7, 46, 29, 0, false, null);
        rBBIRuleTableElementArr[64] = new RBBIRuleTableElement((short) 9, 124, 29, 0, true, null);
        rBBIRuleTableElementArr[65] = new RBBIRuleTableElement((short) 10, 41, 255, 0, true, null);
        rBBIRuleTableElementArr[66] = new RBBIRuleTableElement((short) 8, 255, 255, 0, false, null);
        rBBIRuleTableElementArr[67] = new RBBIRuleTableElement((short) 13, 132, 67, 0, true, "tag-open");
        rBBIRuleTableElementArr[68] = new RBBIRuleTableElement(doStartTagValue, 128, 70, 0, false, null);
        rBBIRuleTableElementArr[69] = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[70] = new RBBIRuleTableElement((short) 13, 132, 74, 0, true, "tag-value");
        rBBIRuleTableElementArr[71] = new RBBIRuleTableElement((short) 13, 125, 74, 0, false, null);
        rBBIRuleTableElementArr[72] = new RBBIRuleTableElement(doTagDigit, 128, 70, 0, true, null);
        rBBIRuleTableElementArr[73] = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[74] = new RBBIRuleTableElement((short) 13, 132, 74, 0, true, "tag-close");
        rBBIRuleTableElementArr[75] = new RBBIRuleTableElement(doTagValue, 125, 77, 0, true, null);
        rBBIRuleTableElementArr[76] = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[77] = new RBBIRuleTableElement((short) 7, 254, 29, 0, false, "expr-cont-no-tag");
        rBBIRuleTableElementArr[78] = new RBBIRuleTableElement((short) 13, 132, 77, 0, true, null);
        rBBIRuleTableElementArr[79] = new RBBIRuleTableElement((short) 7, 131, 29, 0, false, null);
        rBBIRuleTableElementArr[80] = new RBBIRuleTableElement((short) 7, 91, 29, 0, false, null);
        rBBIRuleTableElementArr[81] = new RBBIRuleTableElement((short) 7, 40, 29, 0, false, null);
        rBBIRuleTableElementArr[82] = new RBBIRuleTableElement((short) 7, 36, 29, 0, false, null);
        rBBIRuleTableElementArr[83] = new RBBIRuleTableElement((short) 7, 46, 29, 0, false, null);
        rBBIRuleTableElementArr[84] = new RBBIRuleTableElement((short) 7, 47, 55, 0, false, null);
        rBBIRuleTableElementArr[85] = new RBBIRuleTableElement((short) 9, 124, 29, 0, true, null);
        rBBIRuleTableElementArr[86] = new RBBIRuleTableElement((short) 10, 41, 255, 0, true, null);
        rBBIRuleTableElementArr[87] = new RBBIRuleTableElement((short) 8, 255, 255, 0, false, null);
        rBBIRuleTableElementArr[88] = new RBBIRuleTableElement(doStartVariableName, 36, 90, 0, true, "scan-var-name");
        rBBIRuleTableElementArr[89] = new RBBIRuleTableElement((short) 13, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[90] = new RBBIRuleTableElement((short) 13, 130, 92, 0, true, "scan-var-start");
        rBBIRuleTableElementArr[91] = new RBBIRuleTableElement((short) 32, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[92] = new RBBIRuleTableElement((short) 13, 129, 92, 0, true, "scan-var-body");
        rBBIRuleTableElementArr[93] = new RBBIRuleTableElement((short) 5, 255, 255, 0, false, null);
        rBBIRuleTableElementArr[94] = new RBBIRuleTableElement(doScanUnicodeSet, 91, 255, 0, true, "scan-unicode-set");
        rBBIRuleTableElementArr[95] = new RBBIRuleTableElement(doScanUnicodeSet, 112, 255, 0, true, null);
        rBBIRuleTableElementArr[96] = new RBBIRuleTableElement(doScanUnicodeSet, 80, 255, 0, true, null);
        rBBIRuleTableElementArr[97] = new RBBIRuleTableElement((short) 13, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[98] = new RBBIRuleTableElement((short) 13, 132, 98, 0, true, "assign-or-rule");
        rBBIRuleTableElementArr[99] = new RBBIRuleTableElement(doStartAssign, 61, 29, 101, true, null);
        rBBIRuleTableElementArr[100] = new RBBIRuleTableElement((short) 13, 255, 37, 9, false, null);
        rBBIRuleTableElementArr[101] = new RBBIRuleTableElement((short) 3, 59, 1, 0, true, "assign-end");
        rBBIRuleTableElementArr[102] = new RBBIRuleTableElement(doRuleErrorAssignExpr, 255, 103, 0, false, null);
        rBBIRuleTableElementArr[103] = new RBBIRuleTableElement((short) 6, 255, 103, 0, true, "errorDeath");
        gRuleParseStateTable = rBBIRuleTableElementArr;
    }
}
