package com.huawei.i18n.tmr.address.pt;

import com.huawei.i18n.tmr.address.util.Regexs;

public class RegularExpression extends Regexs {
    private static final String AT = "(?:\\b(?:(?i)at|no|em?)\\s+|@\\s*)(\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,2}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b\\s+\\b((?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|\\s+Sé|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque\\s+de\\s+Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação\\s+Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Pte\\.|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|S\\.M\\.))";
    private static final String BS = "\\b(?<build>(?i)(?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque de Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|s\\.m\\.|\\s+Sé|Pte\\.)\\s+(?:(?:de|dos?|das?)\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?:dos?\\s+)?|\\s*\\(\\s*|\\s*,\\s*)(?<street1>(?:\\b(?i)lote\\s+\\d{1,4}\\s*)?\\b((?i)Rota\\b|Rua\\b|R\\.|R\\b|Avenida\\b|Av\\.|Av\\b|Avª\\b|Travessa\\b|Tv\\.|Calçada\\b|Calç\\.|Estrada\\b|Estr\\.|Rovovia\\b|Rod\\.|Praça\\b|Pç\\b|Largo\\b|Lg\\.|Campo\\b|Rodovia\\b|Túnel\\b|Ladeirados\\b|Ladeira\\b|Viaduto\\b|Boulevard\\b|Bulevar\\b|Lig\\.|Estradas\\b|No\\.|Bloco\\b)\\s+(?:(?:(?i)das?|dos?)?\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?i)lote)?\\s*(?:,\\s*)?\\b(?:(?i)nº\\s*)?\\d{1,4}(?:\\s*(/|-)\\s*\\d{1,3})?\\b)?)(?:\\s*\\))?)?|(?<street2>(?:\\b(?i)lote\\s+\\d{1,4}\\s*)?\\b((?i)Rota\\b|Rua\\b|R\\.|R\\b|Avenida\\b|Av\\.|Av\\b|Avª\\b|Travessa\\b|Tv\\.|Calçada\\b|Calç\\.|Estrada\\b|Estr\\.|Rovovia\\b|Rod\\.|Praça\\b|Pç\\b|Largo\\b|Lg\\.|Campo\\b|Rodovia\\b|Túnel\\b|Ladeirados\\b|Ladeira\\b|Viaduto\\b|Boulevard\\b|Bulevar\\b|Lig\\.|Estradas\\b|No\\.|Bloco\\b)\\s+(?:(?:(?i)das?|dos?)?\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?i)lote)?\\s*(?:,\\s*)?\\b(?:(?i)nº\\s*)?\\d{1,4}(?:\\s*(/|-)\\s*\\d{1,3})?\\b)?)";
    private static final String BUI = "\\b(?<build>(?i)(?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque de Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|s\\.m\\.|\\s+Sé|Pte\\.)\\s+(?:(?:de|dos?|das?)\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b";
    private static final String BUI_STR = "\\b(?<build>(?i)(?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque de Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|s\\.m\\.|\\s+Sé|Pte\\.)\\s+(?:(?:de|dos?|das?)\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?:dos?\\s+)?|\\s*\\(\\s*|\\s*,\\s*)(?<street1>(?:\\b(?i)lote\\s+\\d{1,4}\\s*)?\\b((?i)Rota\\b|Rua\\b|R\\.|R\\b|Avenida\\b|Av\\.|Av\\b|Avª\\b|Travessa\\b|Tv\\.|Calçada\\b|Calç\\.|Estrada\\b|Estr\\.|Rovovia\\b|Rod\\.|Praça\\b|Pç\\b|Largo\\b|Lg\\.|Campo\\b|Rodovia\\b|Túnel\\b|Ladeirados\\b|Ladeira\\b|Viaduto\\b|Boulevard\\b|Bulevar\\b|Lig\\.|Estradas\\b|No\\.|Bloco\\b)\\s+(?:(?:(?i)das?|dos?)?\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?i)lote)?\\s*(?:,\\s*)?\\b(?:(?i)nº\\s*)?\\d{1,4}(?:\\s*(/|-)\\s*\\d{1,3})?\\b)?)(?:\\s*\\))?)?";
    private static final String CAT = "\\s*,\\s*";
    private static final String CITY_NO_CODE = "\\s*\\(.*\\)|(?:,?\\s+(?:(?i)em?\\s+|de\\s+|in\\s+|na\\s+|das?\\s+|no\\s+)?|\\s*(?:,|-)\\s*)\\(?(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)de|das?|do)\\s+)?|\\s*(?:,|/|-|\\(|\\))\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s*\\))?";
    private static final String CITY_WITH_CODE = "(?:,?\\s+(?:(?i)em?\\s+|de\\s+|in\\s+|na\\s+|das?\\s+|no\\s+)?|\\s*(?:,|-)\\s*)(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*)?(?:\\s*,\\s*|\\s+))?(?:\\bAPARTADO\\s*\\d{4,5}\\s*,\\s*)?(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)de|das?)\\s+)?|\\s*(?:-|,)\\s*)){0,4}\\b(?:(?i)cep\\s*:\\s*)?\\d{4,5}(?:-\\d{3})?\\b(?:\\s*(,\\s*)?(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)de|das?)\\s+)?|\\s*(?:-|,)\\s*)){0,3}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*)?";
    private static final String CODE = "\\b(?:(?i)cep\\s*:\\s*)?\\d{4,5}(?:-\\d{3})?\\b";
    private static final String CODE_CITY = "(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*)?(?:\\s*,\\s*|\\s+))?(?:\\bAPARTADO\\s*\\d{4,5}\\s*,\\s*)?(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)de|das?)\\s+)?|\\s*(?:-|,)\\s*)){0,4}\\b(?:(?i)cep\\s*:\\s*)?\\d{4,5}(?:-\\d{3})?\\b(?:\\s*(,\\s*)?(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)de|das?)\\s+)?|\\s*(?:-|,)\\s*)){0,3}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*)?";
    private static final String CON = "(?:,?\\s+(?:(?i)em?\\s+|de\\s+|in\\s+|na\\s+|das?\\s+|no\\s+)?|\\s*(?:,|-)\\s*)";
    private static final String KEY_BUI = "\\b(?<build>(?i)(?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque de Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|s\\.m\\.|\\s+Sé|Pte\\.)";
    private static final String KEY_BUI_B = "\\b((?:Condomínio|Apartamento|Loja|Hispital|Catedral|Lote|Conjunto|Andar|Bairro|Freguesia|Estado|Residencial|Auditório|Igreja|Arquipélago|\\s+Sé|Catetral|Mosteiro|Convento|Capela|Santuário|Memorial|Casa|Paço|Monumento|Cemitério|Templo|Panteão|Castelo|Forte Duque\\s+de\\s+Caixas|Câmara municipal|Direcção|Chilindró|Tribunal|Fundação|Agência|Edifício|Prédio|Posto|Estacionamento|Correios|Editora|Banco|Clínica|Congregação\\s+Cristã|Mercado|Feira|Shopping|Loja|Mall|Livraria|Hall|Outlet|Centro|Supermercado|acessório|comboio|Exposição|Alameda|Pálace|Laboratório|Colégio|Faculdade|Cinema|Teatro|Theatro|Torre|Ponte|Pte\\.|Museu|Miradouro|Miradouro|Mirante|Aquário|Galeria|Bar|Parque|Lounge|Clube|Porto|Cais|Jardim|Elevador|Passeio|Palácio|Hospital|Hotel|Hotéis|Hostel|Motel|Bodega|Taverna|Taberna|Condomínio|Pizzaria|Clinica|Aeroporto|Estação|Parada|Rodoviária|Restaurante|Lanchonete|Café|Churrascaria|Cervejaria|Cantina|Hamburgueria|Biblioteca|Bar|Pastelaria|Terminal|Padaria|Bistro|Universidade|Campus|Estádio|Arena|Residência|Praia|Metrô|Salão|Oficina|Palace|Lagoa|Campo|Square|Mercadinho|Praça|Fazenda|Academia|Vale|Bancários|Ilha|Ponto|Empório|Ginásio)\\b|apt\\.|Apto\\.|Conj\\.|S\\.M\\.)";
    private static final String KEY_STR = "\\b((?i)Rota\\b|Rua\\b|R\\.|R\\b|Avenida\\b|Av\\.|Av\\b|Avª\\b|Travessa\\b|Tv\\.|Calçada\\b|Calç\\.|Estrada\\b|Estr\\.|Rovovia\\b|Rod\\.|Praça\\b|Pç\\b|Largo\\b|Lg\\.|Campo\\b|Rodovia\\b|Túnel\\b|Ladeirados\\b|Ladeira\\b|Viaduto\\b|Boulevard\\b|Bulevar\\b|Lig\\.|Estradas\\b|No\\.|Bloco\\b)";
    private static final String POS = "\\b(?:(?i)cep\\s*:?\\s*)\\d{4,5}(?:-\\d{3})?\\b";
    private static final String STR = "(?:\\b(?i)lote\\s+\\d{1,4}\\s*)?\\b((?i)Rota\\b|Rua\\b|R\\.|R\\b|Avenida\\b|Av\\.|Av\\b|Avª\\b|Travessa\\b|Tv\\.|Calçada\\b|Calç\\.|Estrada\\b|Estr\\.|Rovovia\\b|Rod\\.|Praça\\b|Pç\\b|Largo\\b|Lg\\.|Campo\\b|Rodovia\\b|Túnel\\b|Ladeirados\\b|Ladeira\\b|Viaduto\\b|Boulevard\\b|Bulevar\\b|Lig\\.|Estradas\\b|No\\.|Bloco\\b)\\s+(?:(?:(?i)das?|dos?)?\\s+)?\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b(?:(?:\\s+(?i)lote)?\\s*(?:,\\s*)?\\b(?:(?i)nº\\s*)?\\d{1,4}(?:\\s*(/|-)\\s*\\d{1,3})?\\b)?";
    private static final String STR_NUM = "\\b(?:(?i)nº\\s*)?\\d{1,4}(?:\\s*(/|-)\\s*\\d{1,3})?\\b";
    private static final String WORD = "[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*";
    private static final String WORDS2_STR = "\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,2}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b";
    private static final String WORDS3_STR = "\\b(?:[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*(?:\\s+(?:(?:(?i)das?|dos?|de)\\s+)?|\\s*(?:/|-)\\s*)){0,4}[A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÕÚÙÛ0-9][0-9'A-ZÁÃÀÂÉÈÊÌÎÍÒÔÓÚÙÛa-záãàâéèêìîíòôóõúùûªç]*\\b";

    @Override // com.huawei.i18n.tmr.address.util.Regexs
    public void init() {
        put("pbs", BS);
        put("pat", AT);
        put("pCat", CAT);
        put("pnum", "\\d{4,5}");
        put("pCityWithCode", CITY_WITH_CODE);
        put("pCityNoCode", CITY_NO_CODE);
        put("pPos", POS);
    }
}
