package com.huawei.i18n.tmr.address.de;

import com.huawei.i18n.tmr.address.util.Regexs;

public class RegularExpression extends Regexs {
    private static final String BLACK_KEY = "\\b((?i)einen|kleinen|wurde|diese|gibt|viele|dieses|dass|meine|Ihre|diejenigen|unsere|seine|sie|Bezug|aufs|Nähe|eine|gerne|Zimmer|Einbahnstraße|Passstraßen|Jedes|Jene|Welche|Manche|Neue|Alte|Beide|Nächste|den)\\b";
    private static final String BLACK_KEY_INDI = "(?:(?i)einen|kleinen|diese|viele|dieses|dass|Ihre|diejenigen|unsere|seine|sie|aufs|Nähe|eine|Jedes|Jene|Welche|Manche|Neue|Alte|Beide|Nächste|den)\\b";
    private static final String BLACK_KEY_NO_SINGAL = "(?:(?i)platz|bahnhof|Schule|Kirche|Messe)";
    private static final String BLACK_KEY_UNINDI = "(?:(?i)Einbahn|Pass|Schnell)";
    private static final String CITY = "(?:(?:\\s+|\\s*,\\s*)(?:(?:(?i)at|in|im|am|aus|bei|auf|zum|zu)\\s+)?(\\s*#?\\d{5}\\s*)?#?((Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16}(-(Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16})?|[A-ZÄÖÜ]{1,3}[^a-zäüßö])(((\\s|-|:|#|,|\\s\\(.*\\)\\s)+[A-Z][a-zäüßö]{2,16})?((\\s|-|:|#|,|\\s\\(.*\\)\\s)+((?i)Germany|Deutschland)))?(?:,\\s+(?:\\b[A-Z][A-Za-zäüßö],\\s+)?Germany|Deutschland?)?)?";
    private static final String CITY_KEY_0 = "(Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16}";
    private static final String CITY_KEY_1 = "(Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16}(-(Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16})?";
    private static final String COUNTRY_KEY = "((?i)Germany|Deutschland)";
    private static final String ED = "((((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)((?i)Apotheke|Altersheim|Amtsgericht|Anlegeplatz|Bank|Buchladen|Bibliothek|Bücherei|Bistro|Blumengeschäft|Buchhandlung|Boutique|Büchersammlung|Cafeteria|Cantina|Drogerie|Entbindungsklinik|Einkaufszentrum|Flughafen|Gasthof|Gasthaus|Gastshaus|Garten|Gartenanlagen|Grundschule|Gaststätte|Heilanstalt|Herberge|Hospital|Hotel|Hotelkette|Institut|Jugendherberge|Kantine|Klinik|Kaufhaus|Kaufhalle|Kaufhäuser|Krankenhaus|Kneipe|Lazarett|Mall|Motel|Messehalle|Markthalle|Museum|Markt|Metrostation|Plaza|Postamt|Pharmazie|Privatklinik|Postbank|Reiseagentur|Restaurant|Reisebüro|Schauplatz|Schaubühne|Schauspielhaus|Schankwirtschaft|Shopping\\s*-\\s*zentrum|Schenke|Schänke|Stattliches\\s+wohnhaus|Shopping\\s*-\\s*Center|Spital|Spielplatz|Supermarkt|Sparkasse|Tankstelle|Tussauds|Tiergarten|U\\s*-\\s*bahn\\s+station|Vergnügungspark|Wharf|Weingeschäft|Wirtshaus|Shop|Seebrücke|Park|Zoo|Station|Theater|College|Universität|Gymnasium|Kindergarten|Fitness\\s*-\\s*studio|Bushaltestelle|Tierpark|Hochschule|Gynasium|Hbf|Galerie|bahnhof|Gallery|Stadion|Rathaus|Studio|Wohnung|brücke|University))|(((?i)Apotheke|Altersheim|Amtsgericht|Anlegeplatz|Bank|Buchladen|Bibliothek|Bücherei|Bistro|Blumengeschäft|Buchhandlung|Boutique|Büchersammlung|Cafeteria|Cantina|Drogerie|Entbindungsklinik|Einkaufszentrum|Flughafen|Gasthof|Gasthaus|Gastshaus|Garten|Gartenanlagen|Grundschule|Gaststätte|Heilanstalt|Herberge|Hospital|Hotel|Hotelkette|Institut|Jugendherberge|Kantine|Klinik|Kaufhaus|Kaufhalle|Kaufhäuser|Krankenhaus|Kneipe|Lazarett|Mall|Motel|Messehalle|Markthalle|Museum|Markt|Metrostation|Plaza|Postamt|Pharmazie|Privatklinik|Postbank|Reiseagentur|Restaurant|Reisebüro|Schauplatz|Schaubühne|Schauspielhaus|Schankwirtschaft|Shopping\\s*-\\s*zentrum|Schenke|Schänke|Stattliches\\s+wohnhaus|Shopping\\s*-\\s*Center|Spital|Spielplatz|Supermarkt|Sparkasse|Tankstelle|Tussauds|Tiergarten|U\\s*-\\s*bahn\\s+station|Vergnügungspark|Wharf|Weingeschäft|Wirtshaus|Shop|Seebrücke|Park|Zoo|Station|Theater|College|Universität|Gymnasium|Kindergarten|Fitness\\s*-\\s*studio|Bushaltestelle|Tierpark|Hochschule|Gynasium|Hbf|Galerie|bahnhof|Gallery|Stadion|Rathaus|Studio|Wohnung|brücke|University)(\\s*-\\s*|\\s*)((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)))(?:,\\s*)?\\b";
    private static final String ED_INDEPEND = "((((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)((?i)Platz|Bureau|Dom|Fabrik|Halle|Hall|Kirche|Messe|Turm|Flohmarkt|Fitnessstudio|Fitnessraum|Trainingsraum|Center|Geldinstitut|Gerichtshof|Gebäude|Hochhaus|Kreditinstitut|Villa|Zenturm|Areal|GmbH))|(((?i)Platz|Bureau|Dom|Fabrik|Halle|Hall|Kirche|Messe|Turm|Flohmarkt|Fitnessstudio|Fitnessraum|Trainingsraum|Center|Geldinstitut|Gerichtshof|Gebäude|Hochhaus|Kreditinstitut|Villa|Zenturm|Areal|GmbH)(\\s*-\\s*|\\s*)((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)))(?:,\\s*)?\\b";
    private static final String KEY_BUI = "((?i)Apotheke|Altersheim|Amtsgericht|Anlegeplatz|Bank|Buchladen|Bibliothek|Bücherei|Bistro|Blumengeschäft|Buchhandlung|Boutique|Büchersammlung|Cafeteria|Cantina|Drogerie|Entbindungsklinik|Einkaufszentrum|Flughafen|Gasthof|Gasthaus|Gastshaus|Garten|Gartenanlagen|Grundschule|Gaststätte|Heilanstalt|Herberge|Hospital|Hotel|Hotelkette|Institut|Jugendherberge|Kantine|Klinik|Kaufhaus|Kaufhalle|Kaufhäuser|Krankenhaus|Kneipe|Lazarett|Mall|Motel|Messehalle|Markthalle|Museum|Markt|Metrostation|Plaza|Postamt|Pharmazie|Privatklinik|Postbank|Reiseagentur|Restaurant|Reisebüro|Schauplatz|Schaubühne|Schauspielhaus|Schankwirtschaft|Shopping\\s*-\\s*zentrum|Schenke|Schänke|Stattliches\\s+wohnhaus|Shopping\\s*-\\s*Center|Spital|Spielplatz|Supermarkt|Sparkasse|Tankstelle|Tussauds|Tiergarten|U\\s*-\\s*bahn\\s+station|Vergnügungspark|Wharf|Weingeschäft|Wirtshaus|Shop|Seebrücke|Park|Zoo|Station|Theater|College|Universität|Gymnasium|Kindergarten|Fitness\\s*-\\s*studio|Bushaltestelle|Tierpark|Hochschule|Gynasium|Hbf|Galerie|bahnhof|Gallery|Stadion|Rathaus|Studio|Wohnung|brücke|University)";
    private static final String KEY_BUI_INDEPEND = "((?i)Platz|Bureau|Dom|Fabrik|Halle|Hall|Kirche|Messe|Turm|Flohmarkt|Fitnessstudio|Fitnessraum|Trainingsraum|Center|Geldinstitut|Gerichtshof|Gebäude|Hochhaus|Kreditinstitut|Villa|Zenturm|Areal|GmbH)";
    private static final String KEY_CITY = "((Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16}(-(Bad\\s{1,3})?[A-Z][a-zäüßö]{2,16})?|[A-ZÄÖÜ]{1,3}[^a-zäüßö])(((\\s|-|:|#|,|\\s\\(.*\\)\\s)+[A-Z][a-zäüßö]{2,16})?((\\s|-|:|#|,|\\s\\(.*\\)\\s)+((?i)Germany|Deutschland)))?";
    private static final String KEY_PRE = "(?:(?i)at|in|im|am|aus|bei|auf|zum|zu)";
    private static final String KEY_STR = "((?i)straße|avenue|allee|strasse|str\\.|gasse|Steinweg|damm|street|Landstraße)";
    private static final String REG_PREP = "\\s+(?:(?i)at|in|im|am|aus|bei|auf|zum|zu)\\s+";
    private static final String ST = "((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)((?i)straße|avenue|allee|strasse|str\\.|gasse|Steinweg|damm|street|Landstraße)(?:(\\s*(?<!\\d)\\d{1,4}(?!\\d))(?:-\\d{1,4})?)?";
    private static final String STATE_KEY_0 = "[A-Z][a-zäüßö]{2,16}";
    private static final String TOKEN_KEY = "(\\s|-|:|#|,|\\s\\(.*\\)\\s)+";
    private static final String WHITE_KEY = "(?:(?i)Brandenburger\\s+Tor|Gezi\\s*-\\s*Park|Gezi\\s+Park|Otto\\s*-\\s*Beck\\s*-\\s*Straße|Tel\\s+Aviv\\s+Museum|Red\\s+Roof\\s+Inn|Elbe\\s*-\\s*Einkaufszentrum|Toon\\s+Arena|Ausm\\s+zoo|Ruhr\\s*-\\s*Universität|Landkreis\\s*Rottal-\\s*Inn|Istanbul\\s+Holiday\\s+Inn|Hyde\\s+Park|Gabis\\s+Art\\s+Galerie|Otto\\s*-\\s*Hahn\\s*-\\s*Straße|Rega\\s+Hotel\\s+Stuttgart|Opel\\s*-\\s*Zoo|Stadttheater|Essl\\s+Museum|MesseStar\\s+Tankstelle|Karl\\s*-\\s*Marx\\s*-\\s*Straße|Wall\\s*-\\s*Street|Croke\\s+Park|City\\s*-\\s*Galerie\\s+Augsburg|Festung\\s+Königstein|Karl\\s*-\\s*Marx\\s*-\\s*Allee|Modern\\s+Art\\s+Museum|Adam\\s*-\\s*Ries\\s*-\\s*Strasse|Louvre\\s+Museum|Ditmar\\s*-\\s*Koel\\s*-\\s*Straße|MAMAG\\s+Museum|Gabis\\s+Art\\s+Galerie|Karl\\s*-\\s*May\\s*-\\s*Museum|Red\\s+Bull\\s*-\\s*Arena|Van\\s+Gogh\\s+Museum|Disneyland|Universität\\s+Harvard|Stanford|Eiffelturm)";
    private static final String WORDS_BIG = "((?:\\b[A-Z][A-Za-zäüßö]{3,25}(?:\\s*-\\s*|\\s+)){0,2})(\\b[A-Z][A-Za-zäüßö]{2,25})(\\s*-\\s*|\\s*)";
    private static final String WORD_BIG = "\\b[A-Z][A-Za-zäüßö]";

    @Override // com.huawei.i18n.tmr.address.util.Regexs
    public void init() {
        put("pBlackKey", BLACK_KEY);
        put("pRegWT", WHITE_KEY);
        put("pRegED_Independ", ED_INDEPEND);
        put("pRegED", ED);
        put("pReg_city", CITY);
        put("pRegST", ST);
        put("pRegPrep", REG_PREP);
        put("pRegBlackKeyIndi", BLACK_KEY_INDI);
        put("pRegBlackKeyIndi_withBlank", "(?:(?i)einen|kleinen|diese|viele|dieses|dass|Ihre|diejenigen|unsere|seine|sie|aufs|Nähe|eine|Jedes|Jene|Welche|Manche|Neue|Alte|Beide|Nächste|den)\\b(?:\\s*-\\s*|\\s+)");
        put("pRegBlackKeyUnIndi", BLACK_KEY_UNINDI);
        put("pRegBlackKeyNoSingal", BLACK_KEY_NO_SINGAL);
    }
}
