package com.huawei.hwperformance;

public interface HwPerformance {
    public static final int PERF_EVENT_ANIMATION = 7;
    public static final int PERF_EVENT_APP_START = 4;
    public static final int PERF_EVENT_BOOT_COMPLETE = 0;
    public static final int PERF_EVENT_INTERACTION = 1;
    public static final int PERF_EVENT_LIST_FLING = 8;
    public static final int PERF_EVENT_MAX = 12;
    public static final int PERF_EVENT_OFF = 0;
    public static final int PERF_EVENT_ON = 1;
    public static final int PERF_EVENT_PROBE = 4097;
    public static final int PERF_EVENT_RAW_REQ = 4096;
    public static final int PERF_EVENT_ROTATING = 6;
    public static final int PERF_EVENT_SCREEN_OFF = 10;
    public static final int PERF_EVENT_SCREEN_ON = 9;
    public static final int PERF_EVENT_STATUSBAR = 11;
    public static final int PERF_EVENT_VSYNC_OFF = 3;
    public static final int PERF_EVENT_VSYNC_ON = 2;
    public static final int PERF_EVENT_WINDOW_SWITCH = 5;
    public static final int PERF_TAG_B_CPU_CUR = 6;
    public static final int PERF_TAG_B_CPU_MAX = 5;
    public static final int PERF_TAG_B_CPU_MIN = 4;
    public static final int PERF_TAG_CTL_CPUS_ON = 101;
    public static final int PERF_TAG_CTL_CPUS_ON_LIMIT = 102;
    public static final int PERF_TAG_CTL_DEVICE_TYPE = 100;
    public static final int PERF_TAG_CTRL_TYPE = 0;
    public static final int PERF_TAG_DEF_B_CPU_MAX = 24;
    public static final int PERF_TAG_DEF_B_CPU_MIN = 23;
    public static final int PERF_TAG_DEF_L_CPU_MAX = 22;
    public static final int PERF_TAG_DEF_L_CPU_MIN = 21;
    public static final int PERF_TAG_L_CPU_CUR = 3;
    public static final int PERF_TAG_L_CPU_MAX = 2;
    public static final int PERF_TAG_L_CPU_MIN = 1;
    public static final int PERF_TAG_PARAM_DURATION = 106;
    public static final int PERF_TAG_PARAM_EVENT_ID = 103;
    public static final int PERF_TAG_PARAM_EVENT_PAYLOAD = 104;
    public static final int PERF_TAG_PARAM_IO_PREFETCH_PID = 105;
    public static final int PERF_TAG_TASK_FORK_ON_B_CLUSTER = 20;
    public static final int PERF_VAL_CTRL_TYPE_HIGHPERF = 0;
    public static final int PERF_VAL_CTRL_TYPE_LOW_VOLTAGE = 3;
    public static final int PERF_VAL_CTRL_TYPE_MAX = 4;
    public static final int PERF_VAL_CTRL_TYPE_SPEC_SCENE = 1;
    public static final int PERF_VAL_CTRL_TYPE_THERMAL_PROTECT = 2;
    public static final int PERF_VAL_DEV_TYPE_CPU_B_CUR = 7;
    public static final int PERF_VAL_DEV_TYPE_CPU_B_MAX = 6;
    public static final int PERF_VAL_DEV_TYPE_CPU_B_MIN = 5;
    public static final int PERF_VAL_DEV_TYPE_CPU_DEF_B_MAX = 11;
    public static final int PERF_VAL_DEV_TYPE_CPU_DEF_B_MIN = 10;
    public static final int PERF_VAL_DEV_TYPE_CPU_DEF_L_MAX = 9;
    public static final int PERF_VAL_DEV_TYPE_CPU_DEF_L_MIN = 8;
    public static final int PERF_VAL_DEV_TYPE_CPU_EVENT = 12;
    public static final int PERF_VAL_DEV_TYPE_CPU_L_CUR = 4;
    public static final int PERF_VAL_DEV_TYPE_CPU_L_MAX = 3;
    public static final int PERF_VAL_DEV_TYPE_CPU_L_MIN = 2;
    public static final int PERF_VAL_DEV_TYPE_IO_PREFETCH_START = 0;
    public static final int PERF_VAL_DEV_TYPE_IO_PREFETCH_STOP = 1;
    public static final int PERF_VAL_DEV_TYPE_MAX = 13;
    public static final int PERF_VAL_STATE_OFF = 0;
    public static final int PERF_VAL_STATE_ON = 1;
    public static final int REQUEST_FAILED = -1;
    public static final int REQUEST_INPUT_INVALID = -3;
    public static final int REQUEST_PLATFORM_NOTSUPPORT = -2;
    public static final int REQUEST_SUCCEEDED = 0;

    int perfConfigGet(int[] iArr, int[] iArr2);

    int perfConfigSet(int[] iArr, int[] iArr2, String str);
}
