package android_maps_conflict_avoidance.com.google.googlenav.proto;

import android_maps_conflict_avoidance.com.google.common.io.protocol.ProtoBufType;

public class GmmMessageTypes {
    public static final ProtoBufType ACCEPT_PUBLIC_UPDATE_TERMS_REQUEST_PAYLOAD = null;
    public static final ProtoBufType ACCEPT_PUBLIC_UPDATE_TERMS_RESPONSE = null;
    public static final ProtoBufType ACTIVITY = null;
    public static final ProtoBufType ACTIVITY_FRIEND = null;
    public static final ProtoBufType AD_EVENT_REPORT_REQUEST_PROTO = null;
    public static final ProtoBufType AD_EVENT_REPORT_RESPONSE_PROTO = null;
    public static final ProtoBufType AD_LAYER = null;
    public static final ProtoBufType BATCH_SPEECH_REQUEST_PROTO = null;
    public static final ProtoBufType BATCH_SPEECH_RESPONSE_PROTO = null;
    public static final ProtoBufType BATTERY_STEP = null;
    public static final ProtoBufType BATTERY_STEP_SETTING = null;
    public static final ProtoBufType BATTERY_STEP_SETTINGS = null;
    public static final ProtoBufType BUZZ_LAYER_SNIPPET = null;
    public static final ProtoBufType BUZZ_USER_STATE_PROTO = null;
    public static final ProtoBufType CAPTCHA_REQUEST_PROTO = null;
    public static final ProtoBufType CAPTCHA_RESPONSE_PROTO = null;
    public static final ProtoBufType CATEGORY_INFO_LIST_PROTO = null;
    public static final ProtoBufType CATEGORY_INFO_PROTO = null;
    public static final ProtoBufType CATEGORY_TREE_INNER_NODE_PROTO = null;
    public static final ProtoBufType CLICKABLE_AREA_PROTO = null;
    public static final ProtoBufType CLIENT_CAPABILITIES_PROTO = null;
    public static final ProtoBufType CLIENT_CATEGORY_HISTORY_PROTO = null;
    public static final ProtoBufType CLIENT_FEATURE_PROTO = null;
    public static final ProtoBufType CLIENT_INFO_MATCH_PROTO = null;
    public static final ProtoBufType CLIENT_LATITUDE_WIDGET_MODEL_PROTO = null;
    public static final ProtoBufType CLIENT_LAYER_MANAGER_STATE_PROTO = null;
    public static final ProtoBufType CLIENT_PARAMETERS_REQUEST_PROTO = null;
    public static final ProtoBufType CLIENT_PARAMETERS_RESPONSE_PROTO = null;
    public static final ProtoBufType CLIENT_POST_UPDATE_WIZARD_STATE_PROTO = null;
    public static final ProtoBufType CLIENT_PROPERTIES_REQUEST_PROTO = null;
    public static final ProtoBufType CLIENT_PROPERTIES_RESPONSE_PROTO = null;
    public static final ProtoBufType CLIENT_REQUIREMENTS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_ACTIVITY_FULL_PREFS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_DIRECTIONS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_FRIENDS_MINIMAL_SETTINGS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_FRIENDS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_FRIEND_PHOTOS_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_GAIA_ACCOUNT_STATE_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_OPTION_PROTO = null;
    public static final ProtoBufType CLIENT_SAVED_PHOTO_CACHE_INDEX = null;
    public static final ProtoBufType CLIENT_SAVED_SEARCH_PROTO = null;
    public static final ProtoBufType CLIENT_WAYPOINT_HISTORY_PROTO = null;
    public static final ProtoBufType CLIENT_WAYPOINT_INFO_PROTO = null;
    public static final ProtoBufType CLIENT_WIZARD_MANAGER_STATE_PROTO = null;
    public static final ProtoBufType COMMENT = null;
    public static final ProtoBufType COUNTRY_TO_TREE_MAP_PROTO = null;
    public static final ProtoBufType COUPON_PROTO = null;
    public static final ProtoBufType CREATE_ACTIVITY_REQUEST_PAYLOAD = null;
    public static final ProtoBufType CREATE_ACTIVITY_REQUEST_PROTO = null;
    public static final ProtoBufType CREATE_ACTIVITY_RESPONSE = null;
    public static final ProtoBufType CREATE_ACTIVITY_RESPONSE_PROTO = null;
    public static final ProtoBufType CREATE_COMMENT_REQUEST_PAYLOAD = null;
    public static final ProtoBufType CREATE_COMMENT_REQUEST_PROTO = null;
    public static final ProtoBufType CREATE_COMMENT_RESPONSE = null;
    public static final ProtoBufType CREATE_COMMENT_RESPONSE_PROTO = null;
    public static final ProtoBufType CREATE_RALLY_POINT_REQUEST_PROTO = null;
    public static final ProtoBufType CREATE_RALLY_POINT_RESPONSE_PROTO = null;
    public static final ProtoBufType CURRENT_MOTION_PROTO = null;
    public static final ProtoBufType DATA_REQUEST_PROTO = null;
    public static final ProtoBufType DATE_TIME_PROTO = null;
    public static final ProtoBufType DELETE_RALLY_POINT_REQUEST_PROTO = null;
    public static final ProtoBufType DELETE_RALLY_POINT_RESPONSE_PROTO = null;
    public static final ProtoBufType DEPARTURE_PROTO = null;
    public static final ProtoBufType DETAIL_ITEM = null;
    public static final ProtoBufType DIRECTIONS_ALERT_PROTO = null;
    public static final ProtoBufType DIRECTIONS_ICON_REQUEST_PROTO = null;
    public static final ProtoBufType DIRECTIONS_ICON_RESPONSE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_NOTE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_OPTION_DEFINITION_PROTO = null;
    public static final ProtoBufType DIRECTIONS_OPTION_REQUEST_PROTO = null;
    public static final ProtoBufType DIRECTIONS_OPTION_RESPONSE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_OPTION_VALUE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_REQUEST_PROTO = null;
    public static final ProtoBufType DIRECTIONS_RESPONSE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_STEP_CUE_PROTO = null;
    public static final ProtoBufType DIRECTIONS_STEP_INFO = null;
    public static final ProtoBufType DIRECTIONS_TRAFFIC_SPAN = null;
    public static final ProtoBufType DISMISS_SUGGESTED_FRIEND_REQUEST_PROTO = null;
    public static final ProtoBufType DISMISS_SUGGESTED_FRIEND_RESPONSE_PROTO = null;
    public static final ProtoBufType DOCUMENT_INFO_PROTO = null;
    public static final ProtoBufType EFFICIENT_MAP_POINT_PROTO = null;
    public static final ProtoBufType EMAIL_OPTIONS = null;
    public static final ProtoBufType ENABLE_FEATURE_PARAMETERS_PROTO = null;
    public static final ProtoBufType EXPORTABLE_INTERSECTION = null;
    public static final ProtoBufType EXPORTABLE_PGRAPH = null;
    public static final ProtoBufType EXPORTABLE_ROUTE_NAME = null;
    public static final ProtoBufType EXPORTABLE_SEGMENT = null;
    public static final ProtoBufType EXPORTABLE_SHARED_SEGMENT = null;
    public static final ProtoBufType EXPORTABLE_SIGN_NAME = null;
    public static final ProtoBufType FEATURE_RANGE = null;
    public static final ProtoBufType FEATURE_RESTRICTIONS_PROTO = null;
    public static final ProtoBufType FEATURE_RESTRICTIONS_REQUEST_PROTO = null;
    public static final ProtoBufType FEATURE_RESTRICTIONS_RESPONSE_PROTO = null;
    public static final ProtoBufType FEEDBACK_PROTO = null;
    public static final ProtoBufType FRIEND_ENTRY = null;
    public static final ProtoBufType FRIEND_PROFILE = null;
    public static final ProtoBufType GAIA_RESPONSE_PROTO = null;
    public static final ProtoBufType GEOMETRY_PROTO = null;
    public static final ProtoBufType GET_ACTIVITY_REQUEST_PAYLOAD = null;
    public static final ProtoBufType GET_ACTIVITY_REQUEST_PROTO = null;
    public static final ProtoBufType GET_ACTIVITY_RESPONSE = null;
    public static final ProtoBufType GET_ACTIVITY_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_ACTIVITY_STREAM_REQUEST_PAYLOAD = null;
    public static final ProtoBufType GET_ACTIVITY_STREAM_REQUEST_PROTO = null;
    public static final ProtoBufType GET_ACTIVITY_STREAM_RESPONSE = null;
    public static final ProtoBufType GET_ACTIVITY_STREAM_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_FRIENDS_LOCATIONS_REQUEST_PROTO = null;
    public static final ProtoBufType GET_FRIENDS_LOCATIONS_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_FRIENDS_PROFILES_REQUEST_PROTO = null;
    public static final ProtoBufType GET_FRIENDS_PROFILES_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_FRIEND_FINDER_USERS_REQUEST_PROTO = null;
    public static final ProtoBufType GET_FRIEND_FINDER_USERS_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_INVITE_CONTACT_LIST_REQUEST_PROTO = null;
    public static final ProtoBufType GET_INVITE_CONTACT_LIST_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_INVITE_GROUP_LIST_REQUEST_PROTO = null;
    public static final ProtoBufType GET_INVITE_GROUP_LIST_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_PRODUCTION_STREAM_REQUEST_PAYLOAD = null;
    public static final ProtoBufType GET_PRODUCTION_STREAM_REQUEST_PROTO = null;
    public static final ProtoBufType GET_PRODUCTION_STREAM_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_RALLY_POINTS_FOR_USER_REQUEST_PROTO = null;
    public static final ProtoBufType GET_RALLY_POINTS_FOR_USER_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_RALLY_POINT_REQUEST_PROTO = null;
    public static final ProtoBufType GET_RALLY_POINT_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_SUGGESTED_FRIEND_LIST_REQUEST_PROTO = null;
    public static final ProtoBufType GET_SUGGESTED_FRIEND_LIST_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_USER_PROFILE_REQUEST_PAYLOAD = null;
    public static final ProtoBufType GET_USER_PROFILE_REQUEST_PROTO = null;
    public static final ProtoBufType GET_USER_PROFILE_RESPONSE = null;
    public static final ProtoBufType GET_USER_PROFILE_RESPONSE_PROTO = null;
    public static final ProtoBufType GET_USER_STATE_REQUEST_PROTO = null;
    public static final ProtoBufType GET_USER_STATE_RESPONSE_PROTO = null;
    public static final ProtoBufType GUIDANCE_EVENT_PROTO = null;
    public static final ProtoBufType HAS_ACCEPTED_PUBLIC_UPDATE_TERMS_REQUEST_PAYLOAD = null;
    public static final ProtoBufType HAS_ACCEPTED_PUBLIC_UPDATE_TERMS_RESPONSE = null;
    public static final ProtoBufType HOTPOT_UPDATE = null;
    public static final ProtoBufType HOTPOT_UPDATE_PARAM = null;
    public static final ProtoBufType IMAGE_PROTO = null;
    public static final ProtoBufType IMPLICIT_LOCATION_PROTO = null;
    public static final ProtoBufType INVITE_GROUP_ID_PROTO = null;
    public static final ProtoBufType JOIN_EXPERIMENTS_REQUEST_PROTO = null;
    public static final ProtoBufType JOIN_EXPERIMENTS_RESPONSE_PROTO = null;
    public static final ProtoBufType JUSTIFICATION = null;
    public static final ProtoBufType LAYER_CATEGORY_REQUEST_PROTO = null;
    public static final ProtoBufType LAYER_CATEGORY_RESPONSE_PROTO = null;
    public static final ProtoBufType LAYER_EVENT_REPORT_REQUEST_PROTO = null;
    public static final ProtoBufType LAYER_EVENT_REPORT_RESPONSE_PROTO = null;
    public static final ProtoBufType LAYER_INFO_PROTO = null;
    public static final ProtoBufType LAYER_ITEM_DETAIL_PROTO = null;
    public static final ProtoBufType LAYER_ITEM_REQUEST_PROTO = null;
    public static final ProtoBufType LAYER_ITEM_RESPONSE_PROTO = null;
    public static final ProtoBufType LAYER_ITEM_SNIPPET_PROTO = null;
    public static final ProtoBufType LAYER_LIST_REQUEST_PROTO = null;
    public static final ProtoBufType LAYER_LIST_RESPONSE_PROTO = null;
    public static final ProtoBufType LAYER_PARAMETER_PROTO = null;
    public static final ProtoBufType LAYER_TILE_INFO_PROTO = null;
    public static final ProtoBufType LAYER_TILE_REQUEST_PROTO = null;
    public static final ProtoBufType LAYER_TILE_RESPONSE_HEADER_PROTO = null;
    public static final ProtoBufType LAYER_TILE_RESPONSE_PROTO = null;
    public static final ProtoBufType LOCALE_AND_LABEL_PAIR_PROTO = null;
    public static final ProtoBufType LOCAL_DETAILS_REQUEST_PROTO = null;
    public static final ProtoBufType LOCAL_DETAILS_RESPONSE_PROTO = null;
    public static final ProtoBufType LOCATION = null;
    public static final ProtoBufType LOCATION_PRIVACY_SETTING_PROTO = null;
    public static final ProtoBufType LOCATION_PROTO = null;
    public static final ProtoBufType LOCATION_REPORT_REASON = null;
    public static final ProtoBufType LOCATION_SHIFT_REQUEST_PROTO = null;
    public static final ProtoBufType LOCATION_SHIFT_RESPONSE_PROTO = null;
    public static final ProtoBufType LOCATION_UPDATE_REQUEST_PROTO = null;
    public static final ProtoBufType LOCATION_UPDATE_RESPONSE_PROTO = null;
    public static final ProtoBufType MAPS_ADDRESS_BOOK_ENTRY_PROTO = null;
    public static final ProtoBufType MAP_INFO_PROTO = null;
    public static final ProtoBufType MAP_POINT_PROTO = null;
    public static final ProtoBufType MAP_SHOP_RAW_REQUESTS = null;
    public static final ProtoBufType MAP_TILE_PROTO = null;
    public static final ProtoBufType MEDIA = null;
    public static final ProtoBufType MORE_DETAILS_PROTO = null;
    public static final ProtoBufType NAVIGATION_PARAMETERS_PROTO = null;
    public static final ProtoBufType NETWORK_INITIATED_PREFERENCE = null;
    public static final ProtoBufType NOTIFICATIONS_REQUEST_PROTO = null;
    public static final ProtoBufType NOTIFICATIONS_RESPONSE_PROTO = null;
    public static final ProtoBufType NOTIFICATION_CHECK_REQUEST_PAYLOAD = null;
    public static final ProtoBufType NOTIFICATION_CHECK_REQUEST_PROTO = null;
    public static final ProtoBufType NOTIFICATION_CHECK_RESPONSE = null;
    public static final ProtoBufType NOTIFICATION_CHECK_RESPONSE_PROTO = null;
    public static final ProtoBufType NOTIFICATION_RESPONSE = null;
    public static final ProtoBufType PARAMETER_CONFIGURATION_PROTO = null;
    public static final ProtoBufType PARAMETER_GROUP_PROTO = null;
    public static final ProtoBufType PARAMETER_RULE_PROTO = null;
    public static final ProtoBufType PHOTO_DATA = null;
    public static final ProtoBufType PHOTO_ID = null;
    public static final ProtoBufType PHOTO_PROTO = null;
    public static final ProtoBufType PHOTO_UPLOAD = null;
    public static final ProtoBufType PIXEL_POINT_PROTO = null;
    public static final ProtoBufType POINT = null;
    public static final ProtoBufType PROFILE_PHOTO = null;
    public static final ProtoBufType PROFILE_PHOTO_DATA = null;
    public static final ProtoBufType PROFILE_PHOTO_REQUEST_PROTO = null;
    public static final ProtoBufType PROFILE_PHOTO_RESPONSE_PROTO = null;
    public static final ProtoBufType PROFILE_PHOTO_SPEC_PROTO = null;
    public static final ProtoBufType PUBLIC_UPDATE_TERMS_AND_CONDITIONS = null;
    public static final ProtoBufType QUERY_PARAMETERS = null;
    public static final ProtoBufType RALLY_POINT = null;
    public static final ProtoBufType RATING_PROTO = null;
    public static final ProtoBufType REAL_ESTATE_QUERY_REFINEMENT = null;
    public static final ProtoBufType RECOMMENDATION_REASON_PROTO = null;
    public static final ProtoBufType RECOMMENDATION_REQUEST_PROTO = null;
    public static final ProtoBufType REPORT_MAP_ISSUE_REQUEST_PROTO = null;
    public static final ProtoBufType REPORT_MAP_ISSUE_RESPONSE_PROTO = null;
    public static final ProtoBufType RESOURCE_REQUEST_PROTO = null;
    public static final ProtoBufType RESOURCE_RESPONSE_PROTO = null;
    public static final ProtoBufType REVERSE_GEOCODE_REQUEST_PROTO = null;
    public static final ProtoBufType REVERSE_GEOCODE_RESPONSE_PROTO = null;
    public static final ProtoBufType REVERSE_GEOCODE_RESULT_PROTO = null;
    public static final ProtoBufType REVERSE_GEOCODE_RESULT_TYPE_ENUM = null;
    public static final ProtoBufType REVIEW = null;
    public static final ProtoBufType REVIEWS_PROTO = null;
    public static final ProtoBufType REVIEW_PROTO = null;
    public static final ProtoBufType ROADWAY_PROTO = null;
    public static final ProtoBufType ROAD_POINT_PROTO = null;
    public static final ProtoBufType ROUTE_PROTO = null;
    public static final ProtoBufType SEARCH_DIALOG_PREFERENCES_PROTO = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PAYLOAD = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PROTO = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PAYLOAD = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PROTO = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_OPTIONS = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_REQUEST_PAYLOAD = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_RESPONSE = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_RESPONSE_PROTO = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PAYLOAD = null;
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PROTO = null;
    public static final ProtoBufType SEARCH_REQUEST_PROTO = null;
    public static final ProtoBufType SEARCH_RESPONSE_PROTO = null;
    public static final ProtoBufType SEARCH_RESPONSE_WITH_PAYLOAD_PROTO = null;
    public static final ProtoBufType SEARCH_RESULT_PROTO = null;
    public static final ProtoBufType SECURITY_POPUP_SETTINGS = null;
    public static final ProtoBufType SEED_PLACE = null;
    public static final ProtoBufType SERVER_SETTING_PARAMETERS_PROTO = null;
    public static final ProtoBufType SESAME_REQUEST_PROTO = null;
    public static final ProtoBufType SESAME_RESPONSE_PROTO = null;
    public static final ProtoBufType SET_HTTP_COOKIE_REQUEST_PROTO = null;
    public static final ProtoBufType SET_HTTP_COOKIE_RESPONSE_PROTO = null;
    public static final ProtoBufType SET_LOCATION_PRIVACY_SETTING_REQUEST_PROTO = null;
    public static final ProtoBufType SET_LOCATION_PRIVACY_SETTING_RESPONSE_PROTO = null;
    public static final ProtoBufType SET_NETWORK_INITIATED_PREFERENCE_REQUEST_PROTO = null;
    public static final ProtoBufType SET_NETWORK_INITIATED_PREFERENCE_RESPONSE_PROTO = null;
    public static final ProtoBufType SET_USER_STATE_REQUEST_PROTO = null;
    public static final ProtoBufType SET_USER_STATE_RESPONSE_PROTO = null;
    public static final ProtoBufType SHARE_WITH_FRIEND_REQUEST_PROTO = null;
    public static final ProtoBufType SHARE_WITH_FRIEND_RESPONSE_PROTO = null;
    public static final ProtoBufType SNAP_TO_PLACE_REQUEST_PROTO = null;
    public static final ProtoBufType SNAP_TO_PLACE_RESPONSE_PROTO = null;
    public static final ProtoBufType SNIPPET_PROTO = null;
    public static final ProtoBufType SPEECH_REQUEST_PROTO = null;
    public static final ProtoBufType SPEECH_RESPONSE_PROTO = null;
    public static final ProtoBufType STARRING_PREFS_PROTO = null;
    public static final ProtoBufType STAR_DETAILS_PROTO = null;
    public static final ProtoBufType STAR_DETAILS_STORAGE_PROTO = null;
    public static final ProtoBufType STAR_MRUITEM = null;
    public static final ProtoBufType STAR_PROTO = null;
    public static final ProtoBufType STAR_RESULT_PROTO = null;
    public static final ProtoBufType STAR_WITH_DETAILS_PROTO = null;
    public static final ProtoBufType STEP_PROTO = null;
    public static final ProtoBufType STREAM = null;
    public static final ProtoBufType STREET_VIEW_METADATA_PROTO = null;
    public static final ProtoBufType STREET_VIEW_REPORT_PROTO = null;
    public static final ProtoBufType STREET_VIEW_REPORT_RESPONSE_PROTO = null;
    public static final ProtoBufType STREET_VIEW_REQUEST_PROTO = null;
    public static final ProtoBufType STREET_VIEW_RESPONSE_PROTO = null;
    public static final ProtoBufType STREET_VIEW_TAKE_DOWN_REQUEST_PROTO = null;
    public static final ProtoBufType STREET_VIEW_TAKE_DOWN_RESPONSE_PROTO = null;
    public static final ProtoBufType STRUCTURED_ADDRESS_PROTO = null;
    public static final ProtoBufType STRUCTURED_INSTRUCTIONS_PROTO = null;
    public static final ProtoBufType SUBMIT_REVIEW_REQUEST_PROTO = null;
    public static final ProtoBufType SUBMIT_REVIEW_RESPONSE_PROTO = null;
    public static final ProtoBufType SUGGESTION_GROUP_PROTO = null;
    public static final ProtoBufType SUGGESTION_PROTO = null;
    public static final ProtoBufType SUGGEST_REQUEST_PROTO = null;
    public static final ProtoBufType SUGGEST_RESPONSE_PROTO = null;
    public static final ProtoBufType SYNCED_DATA_CORPUS_STORAGE_PROTO = null;
    public static final ProtoBufType SYNCED_DATA_PENDING_QUEUE_PROTO = null;
    public static final ProtoBufType SYNCED_DATA_PREFERENCES_PROTO = null;
    public static final ProtoBufType SYNCED_DATA_STORAGE_PROTO = null;
    public static final ProtoBufType SYNCED_DATA_VIEW_PROTO = null;
    public static final ProtoBufType SYNC_CORPUS_REQUEST_PROTO = null;
    public static final ProtoBufType SYNC_CORPUS_RESPONSE_PROTO = null;
    public static final ProtoBufType SYNC_ERROR_PROTO = null;
    public static final ProtoBufType SYNC_ITEM = null;
    public static final ProtoBufType SYNC_ITEM_UPDATE_REQUEST = null;
    public static final ProtoBufType SYNC_ITEM_UPDATE_RESPONSE = null;
    public static final ProtoBufType SYNC_OPERATION = null;
    public static final ProtoBufType SYNC_REQUEST_PROTO = null;
    public static final ProtoBufType SYNC_RESPONSE_PROTO = null;
    public static final ProtoBufType TRAFFIC_VECTOR_TILE_PROTO = null;
    public static final ProtoBufType TRANSIT_AGENCY_PROTO = null;
    public static final ProtoBufType TRANSIT_LINE_DISPLAY_PROPERTIES_PROTO = null;
    public static final ProtoBufType TRANSIT_LINE_INFO_PROTO = null;
    public static final ProtoBufType TRANSIT_LINE_RESULT_PROTO = null;
    public static final ProtoBufType TRANSIT_LINE_WITH_DEPARTURES_AT_STATION_PROTO = null;
    public static final ProtoBufType TRANSIT_STATION_INFO_PROTO = null;
    public static final ProtoBufType TRANSIT_STATION_RESULT_PROTO = null;
    public static final ProtoBufType TRIP_GROUP_AND_DEPARTURES_PROTO = null;
    public static final ProtoBufType UPDATE_ACTIVITY_REQUEST_PAYLOAD = null;
    public static final ProtoBufType UPDATE_ACTIVITY_REQUEST_PROTO = null;
    public static final ProtoBufType UPDATE_ACTIVITY_RESPONSE = null;
    public static final ProtoBufType UPDATE_ACTIVITY_RESPONSE_PROTO = null;
    public static final ProtoBufType UPDATE_FRIEND_STATE_REQUEST_PROTO = null;
    public static final ProtoBufType UPDATE_FRIEND_STATE_RESPONSE_PROTO = null;
    public static final ProtoBufType UPDATE_LOCATION_ACL_REQUEST_PROTO = null;
    public static final ProtoBufType UPDATE_LOCATION_ACL_RESPONSE_PROTO = null;
    public static final ProtoBufType URL_REQUEST_PROTO = null;
    public static final ProtoBufType URL_RESPONSE_PROTO = null;
    public static final ProtoBufType USER_CONTENT_REQUEST_PROTO = null;
    public static final ProtoBufType USER_CONTENT_RESPONSE_META = null;
    public static final ProtoBufType USER_CONTENT_RESPONSE_PROTO = null;
    public static final ProtoBufType USER_LOCATION_DEBUG_INFO = null;
    public static final ProtoBufType USER_MAP_LISTING_PROTO = null;
    public static final ProtoBufType USER_PHOTO_DATA = null;
    public static final ProtoBufType USER_PROFILE_UPDATE_REQUEST_PROTO = null;
    public static final ProtoBufType USER_PROFILE_UPDATE_RESPONSE_PROTO = null;
    public static final ProtoBufType USER_STATE_PROTO = null;
    public static final ProtoBufType VOICE_SEARCH_LANGUAGE_PROTO = null;
    public static final ProtoBufType VOICE_SEARCH_PARAMETERS_PROTO = null;

    static {
        /* JADX: method processing error */
/*
        Error: jadx.core.utils.exceptions.DecodeException: Load method exception in method: android_maps_conflict_avoidance.com.google.googlenav.proto.GmmMessageTypes.<clinit>():void
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:113)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:256)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
	at jadx.core.ProcessClass.process(ProcessClass.java:42)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:281)
	at jadx.api.JavaClass.decompile(JavaClass.java:59)
	at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:161)
Caused by: jadx.core.utils.exceptions.DecodeException:  in method: android_maps_conflict_avoidance.com.google.googlenav.proto.GmmMessageTypes.<clinit>():void
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:46)
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:98)
	... 7 more
Caused by: java.lang.IllegalArgumentException: bogus opcode: 00e9
	at com.android.dx.io.OpcodeInfo.get(OpcodeInfo.java:1197)
	at com.android.dx.io.OpcodeInfo.getFormat(OpcodeInfo.java:1212)
	at com.android.dx.io.instructions.DecodedInstruction.decode(DecodedInstruction.java:72)
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:43)
	... 8 more
*/
        /*
        // Can't load method instructions.
        */
        throw new UnsupportedOperationException("Method not decompiled: android_maps_conflict_avoidance.com.google.googlenav.proto.GmmMessageTypes.<clinit>():void");
    }
}
