package android.common;

import android.os.Bundle;

public interface HwFrameworkMonitor {
    public static final String APP_FILE_NAME = "APP_FILE_NAME";
    public static final String AREA_NAME = "AREA_NAME";
    public static final String CALLING_NAME = "CALLING_NAME";
    public static final String CALLING_UID = "CALLING_UID";
    public static final String CIRCREF_RCYCL_CNT = "circref_rcycl_cnt";
    public static final String CIRCREF_RCYCL_MAX_DURATION = "circref_rcycl_max_duration";
    public static final String CONSUM_CLASS_LOCATOR = "consum_class_locator";
    public static final String CONSUM_MPL_FILES = "consum_mpl_files";
    public static final String CYCLE_PATTERN = "cycle_pattern";
    public static final String DELETE_NUM = "DELETE_NUM";
    public static final String ELAPSED_REALTIME = "ELAPSED_REALTIME";
    public static final String ERROR_CODE = "ERROR_CODE";
    public static final String EXCEPTION_INFO = "EXCEPTION_INFO";
    public static final String EXCEPTION_NAME = "EXCEPTION_NAME";
    public static final String FILE_NAME = "FILE_NAME";
    public static final String GC_MANAGE_HEAP = "gc_manage_heap";
    public static final String GLOBAL_WATER_LINE = "global_water_line";
    public static final String KEY_ACTION = "action";
    public static final String KEY_ACTION_COUNT = "actionCount";
    public static final String KEY_BROADCAST_INTENT = "intent";
    public static final String KEY_COMPONENT = "component";
    public static final String KEY_CPU_STATE = "cpuState";
    public static final String KEY_CPU_TIME = "cpuTime";
    public static final String KEY_ERROR_TYPE = "errorType";
    public static final String KEY_EXTRA = "extra";
    public static final String KEY_MESSAGE = "message";
    public static final String KEY_MMS_BROADCAST_FLAG = "mmsFlag";
    public static final String KEY_PACKAGE = "package";
    public static final String KEY_REASON = "reason";
    public static final String KEY_RECEIVER = "receiver";
    public static final String KEY_RECEIVE_TIME = "receiveTime";
    public static final String KEY_VERSION_CODE = "versionCode";
    public static final String KEY_VERSION_NAME = "versionName";
    public static final String MEM_ALLOC_ABNORMAL = "mem_alloc_abnormal";
    public static final String MEM_ALLOC_SPACE_UTIL = "mem_alloc_space_util";
    public static final String MEM_LEAK_AVRG = "mem_leak_avrg";
    public static final String MEM_LEAK_PEAK = "mem_leak_peak";
    public static final String NATIVE_TABLE_SIZE = "native_table_size";
    public static final String PACKAGE_NUM = "PACKAGE_NUM";
    public static final String PROC_NAME = "proc_name";
    public static final String RC_ABNORMAL = "rc_abnormal";
    public static final String REBOOT_TIMES = "REBOOT_TIMES";
    public static final String REFLECT_MANAGE_HEAP = "reflect_manage_heap";
    public static final int SCENE_BROADCAST_OVERLENGTH = 907400002;
    public static final int SCENE_BROADCAST_OVERTIME = 907400003;
    public static final int SCENE_CHECK_PASSWORD_FAIL = 907034001;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1001 = 1001;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1002 = 1002;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1003 = 1003;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1004 = 1004;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1005 = 1005;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1006 = 1006;
    public static final int SCENE_CHECK_PASSWORD_FAIL_ERROR_TYPE_1007 = 1007;
    public static final int SCENE_CPU_SPEED_TOO_LARGE = 907400016;
    public static final int SCENE_DPM_FACTORY_RESET = 907400018;
    public static final int SCENE_ENROLL_PASSWORD_FAIL = 907034002;
    public static final int SCENE_ENROOL_ERROR_DUPLICATE_UPDATE = 1010;
    public static final int SCENE_ENROOL_ERROR_INTERUPTED = 1012;
    public static final int SCENE_PACKAGE_INSTALL_FAIL_SD = 907400000;
    public static final int SCENE_PACKAGE_INSTALL_FAIL_UID = 907400001;
    public static final int SCENE_PACKAGE_VOLUME_DOWN_EVENT_ID = 907400028;
    public static final int SCENE_PMS_DATA_APP_DELETED = 907400031;
    public static final int SCENE_PMS_INIT_EXCEPTION = 907400030;
    public static final int SCENE_PMS_PARSE_FILE_EXCEPTION = 907400029;
    public static final int SCENE_REPORT_RT = 942030001;
    public static final int SCENE_TRAFFIC_SPENT_TOO_MUCH = 907400017;
    public static final String STAT_DURATION = "stat_duration";
    public static final String THREADS_LOCAL_WATER_LINE = "threads_local_water_line";
    public static final String UNKNOWN = "unknown";
    public static final String USER_ID = "USER_ID";
    public static final String WEAK_WATER_LINE = "weak_water_line";

    boolean monitor(int i, Bundle bundle);
}
