package com.huawei.server.security.permissionmanager.util;

import com.huawei.android.util.SlogEx;
import com.huawei.server.security.permissionmanager.struct.HwPermissionInfo;

public class PermConst {
    public static final HwPermissionInfo ACCESS_BROWSER_RECORDS_INFO = new HwPermissionInfo(PermissionType.ACCESS_BROWSER_RECORDS, new String[]{READ_HISTORY_BOOKMARKS}, false);
    public static final String ACTIVE_ONE_TIME_PERM_TABLE_NAME = "activeOneTimePermPkgInfo";
    public static final HwPermissionInfo ACTIVITY_RECOGNITION_INFO = new HwPermissionInfo(PermissionType.ACTIVITY_RECOGNITION, new String[]{"android.permission.ACTIVITY_RECOGNITION"}, false);
    public static final String APP_LIST_KEY = "app_list_key";
    public static final String APP_MAP_KEY = "app_map_key";
    public static final String APP_UID = "uid";
    public static final HwPermissionInfo BODY_SENSOR_INFO = new HwPermissionInfo(PermissionType.BODY_SENSORS, new String[]{"android.permission.BODY_SENSORS"}, false);
    public static final String BROADCAST_KEY = "broadcast_key";
    public static final HwPermissionInfo CALL_FORWARD_INFO = new HwPermissionInfo(PermissionType.CALL_FORWARD, new String[]{"android.permission.CALL_PHONE"}, false);
    public static final HwPermissionInfo CALL_PHONE_INFO = new HwPermissionInfo(64, new String[]{"android.permission.CALL_PHONE"}, false);
    public static final HwPermissionInfo CAMERA_INFO = new HwPermissionInfo(PermissionType.CAMERA, new String[]{"android.permission.CAMERA"}, false);
    public static final String CHECK_HW_PERM_INFO = "checkHwPerm";
    public static final String CHECK_SMS_BLOCK_STATE = "checkSmsBlockState";
    public static final int CLOSE = 2;
    public static final String COLUMN_BLOCKED_PACKAGE_NAME = "blockedPackageName";
    public static final String COLUMN_SUPPORTED_PACKAGE_NAME = "supportedPackageName";
    public static final HwPermissionInfo EDIT_SHORTCUT_INFO = new HwPermissionInfo(PermissionType.EDIT_SHORTCUT, new String[]{"com.android.launcher.permission.INSTALL_SHORTCUT", "com.android.launcher.permission.UNINSTALL_SHORTCUT"}, false);
    public static final String GET_ALL_APP_PERM_INFO = "getAllAppPermInfo";
    public static final String GET_HW_PERM_APPS_INFO = "getHwPermApps";
    public static final String GET_HW_PERM_INFO = "getHwPermInfo";
    public static final String GET_HW_PERM_INFO_FOR_PACKAGE_INSTALLER = "getHwPermInfoForInstaller";
    public static final String GET_MMS_PERM_INFO = "application/vnd.wap.mms-message";
    public static final String GET_ONE_TIME_PERMISSION_CONTROL_INFO = "getOneTimePermissionControlInfo";
    public static final String GET_PROPERTY_PERMISSIONS_HUB = "get_property_permissions_hub";
    public static final String GET_RECOMMEND_PERM_FOR_INSTALLER = "getRecommendPermForInstaller";
    public static final String HOTA_UPDATE_SMS_BLOCK_DATA = "hotaUpdateSmsBlockData";
    public static final String HW_PERM_SET_TABLE_NAME = "permissionCfg_";
    public static final int ILLEGAL_STATE = -1;
    public static final int ILLEGAL_UID = -1;
    public static final String INFO_TYPE_KEY = "info_type";
    public static final String INIT_SMS_BLOCK_DATA = "initSmsBlockData";
    public static final boolean IS_UNIT = true;
    public static final HwPermissionInfo LOCATION_BACKGROUND_INFO = new HwPermissionInfo(PermissionType.LOCATION_BACKGROUND, new String[]{"android.permission.ACCESS_BACKGROUND_LOCATION"}, false);
    public static final HwPermissionInfo LOCATION_INFO = new HwPermissionInfo(8, new String[]{"android.permission.ACCESS_FINE_LOCATION", "android.permission.ACCESS_COARSE_LOCATION", "android.permission.ACCESS_BACKGROUND_LOCATION"}, false);
    public static final HwPermissionInfo MODIFY_PHONE_STATUS_INFO = new HwPermissionInfo(PermissionType.MODIFY_PHONE_STATE, new String[]{"android.permission.MODIFY_PHONE_STATE"}, false);
    public static final String NAME_KEY = "name_key";
    public static final String NOTIFY_SMS_PKG_REMOVE = "notifySmsPkgRemove";
    public static final String NOTIFY_SMS_USER_RESET = "notifySmsUserReset";
    public static final boolean NOT_UNIT = false;
    public static final int NO_APPLY_PERMISSION = 4;
    public static final String ONE_TIME_PERM_TABLE_NAME = "oneTimePermPkgInfo";
    public static final String ONE_TIME_PERM_TYPE_BLOCK = "blocked";
    public static final String ONE_TIME_PERM_TYPE_SUPPORT = "supported";
    public static final int OPEN = 1;
    public static final String OPERATION_KEY = "operation_key";
    public static final String PACKAEGE_NAME_KEY = "package_name";
    public static final String PACKAGE_NAME = "packageName";
    public static final String PERMISSION_CFG = "permissionCfg";
    public static final String PERMISSION_CODE = "permissionCode";
    public static final String PERM_TYPE_KEY = "perm_type_key";
    public static final String PRE_DEFINED_SMS_CONFIG = "preDefinedSmsConfig";
    public static final String PROPERTY_PERMISSIONS_HUB_ENABLED = "permissions_hub_enabled";
    public static final HwPermissionInfo READ_CALENDAR_INFO = new HwPermissionInfo(PermissionType.READ_CALENDAR, new String[]{"android.permission.READ_CALENDAR"}, false);
    public static final HwPermissionInfo READ_CALLLOG_INFO = new HwPermissionInfo(2, new String[]{"android.permission.READ_CALL_LOG"}, false);
    public static final HwPermissionInfo READ_CONTACTS_INFO = new HwPermissionInfo(1, new String[]{"android.permission.READ_CONTACTS"}, false);
    public static final String READ_HISTORY_BOOKMARKS = "com.android.browser.permission.READ_HISTORY_BOOKMARKS";
    public static final HwPermissionInfo READ_MSG_INFO = new HwPermissionInfo(4, new String[]{"android.permission.READ_SMS"}, false);
    public static final HwPermissionInfo READ_PHONE_STATUS_INFO = new HwPermissionInfo(16, new String[]{"android.permission.READ_PHONE_STATE"}, false);
    public static final HwPermissionInfo RECEIVE_SMS_INFO = new HwPermissionInfo(PermissionType.RECEIVE_SMS, new String[]{"android.permission.RECEIVE_SMS"}, false);
    public static final String RECOMMEND_PERMISSION_TABLE_NAME = "permissionOuterTable";
    public static final String RECOMMEND_PERM_TYPE = "recommend";
    public static final HwPermissionInfo RECORD_AUDIO_INFO = new HwPermissionInfo(128, new String[]{"android.permission.RECORD_AUDIO"}, false);
    public static final int REMIND = 0;
    public static final String REMOVE_HW_PERM_INFO = "removeHwPermission";
    public static final String REPLACE_HW_PERM_INFO = "replaceHwPermInfo";
    public static final String REPLACE_PERM_ALL_APP = "replacePermForAllApp";
    public static final String RETURN_RESULT_KEY = "return_result_key";
    public static final HwPermissionInfo SEND_MMS_INFO = new HwPermissionInfo(PermissionType.SEND_MMS, new String[]{"android.permission.SEND_SMS"}, false);
    public static final HwPermissionInfo SEND_SMS_INFO = new HwPermissionInfo(32, new String[]{"android.permission.SEND_SMS"}, false);
    public static final String SET_HW_PERMS_INFO = "setHwPermissions";
    public static final String SET_HW_PERM_INFO = "setHwPermission";
    public static final String SET_HW_PERM_INFO_FOR_PACKAGE_INSTALLER = "setHwPermissionForInstaller";
    public static final String SET_ONE_TIME_PERMISSION_CONTROL_INFO = "setOneTimePermissionControlInfo";
    public static final String SET_PROPERTY_PERMISSIONS_HUB = "set_property_permissions_hub";
    public static final String SET_RECOMMEND_PERMISSION = "setRecommendPermission";
    public static final String SMS_BLOCK_DATA_KEY = "sms_block_data_key";
    public static final String SMS_BLOCK_TABLE_NAME = "smsBlock_";
    public static final HwPermissionInfo STORAGE_INFO = new HwPermissionInfo(256, new String[]{"android.permission.READ_EXTERNAL_STORAGE", "android.permission.WRITE_EXTERNAL_STORAGE"}, false);
    public static final String SUB_PERMISSION = "smsPermission";
    public static final String SYSTEM_MANAGER_PACKAGE_NAME = "com.huawei.systemmanager";
    private static final String TAG = "PermConst";
    public static final int UNKNOWN = 3;
    public static final String USER_ID = "userId";
    public static final HwPermissionInfo WRITE_CALENDAR_INFO = new HwPermissionInfo(PermissionType.WRITE_CALENDAR, new String[]{"android.permission.WRITE_CALENDAR"}, false);
    public static final HwPermissionInfo WRITE_CALL_LOG_INFO = new HwPermissionInfo(PermissionType.WRITE_CALL_LOG, new String[]{"android.permission.WRITE_CALL_LOG"}, false);
    public static final HwPermissionInfo WRITE_CONTACTS_INFO = new HwPermissionInfo(PermissionType.WRITE_CONTACTS, new String[]{"android.permission.WRITE_CONTACTS"}, false);

    private PermConst() {
        SlogEx.i(TAG, "create PerConst");
    }
}
