package ohos.com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_sv extends ListResourceBundle {
    @Override // java.util.ListResourceBundle
    public Object[][] getContents() {
        return new Object[][]{new Object[]{BasisLibrary.RUN_TIME_INTERNAL_ERR, "Internt exekveringsfel i ''{0}''"}, new Object[]{BasisLibrary.RUN_TIME_COPY_ERR, "Exekveringsexekveringsfel av <xsl:copy>."}, new Object[]{"DATA_CONVERSION_ERR", "Ogiltig konvertering från ''{0}'' till ''{1}''."}, new Object[]{BasisLibrary.EXTERNAL_FUNC_ERR, "Den externa funktionen ''{0}'' understöds inte i XSLTC."}, new Object[]{BasisLibrary.EQUALITY_EXPR_ERR, "Okänd argumenttyp i likhetsuttryck."}, new Object[]{BasisLibrary.INVALID_ARGUMENT_ERR, "Argumenttyp ''{0}'' i anrop till ''{1}'' är inte giltig"}, new Object[]{BasisLibrary.FORMAT_NUMBER_ERR, "Försöker formatera talet ''{0}'' med mönstret ''{1}''."}, new Object[]{BasisLibrary.ITERATOR_CLONE_ERR, "Kan inte klona iteratorn ''{0}''."}, new Object[]{BasisLibrary.AXIS_SUPPORT_ERR, "Iteratorn för axeln ''{0}'' understöds inte."}, new Object[]{BasisLibrary.TYPED_AXIS_SUPPORT_ERR, "Iteratorn för den typade axeln ''{0}'' understöds inte."}, new Object[]{"STRAY_ATTRIBUTE_ERR", "Attributet ''{0}'' finns utanför elementet."}, new Object[]{BasisLibrary.STRAY_NAMESPACE_ERR, "Namnrymdsdeklarationen ''{0}''=''{1}'' finns utanför element."}, new Object[]{BasisLibrary.NAMESPACE_PREFIX_ERR, "Namnrymd för prefix ''{0}'' har inte deklarerats."}, new Object[]{BasisLibrary.DOM_ADAPTER_INIT_ERR, "DOMAdapter har skapats med fel typ av DOM-källa."}, new Object[]{BasisLibrary.PARSER_DTD_SUPPORT_ERR, "Den SAX-parser som du använder hanterar inga DTD-deklarationshändelser."}, new Object[]{BasisLibrary.NAMESPACES_SUPPORT_ERR, "Den SAX-parser som du använder saknar stöd för XML-namnrymder."}, new Object[]{BasisLibrary.CANT_RESOLVE_RELATIVE_URI_ERR, "Kunde inte matcha URI-referensen ''{0}''."}, new Object[]{"UNSUPPORTED_XSL_ERR", "XSL-elementet ''{0}'' stöds inte"}, new Object[]{"UNSUPPORTED_EXT_ERR", "XSLTC-tillägget ''{0}'' är okänt"}, new Object[]{BasisLibrary.UNKNOWN_TRANSLET_VERSION_ERR, "Angiven translet, ''{0}'', har skapats med en XSLTC-version som är senare än den XSLTC-körning i bruk. För att kunna köra denna translet måste du omkompilera formatmallen eller använda en senare version av XSLTC."}, new Object[]{"INVALID_QNAME_ERR", "Ett attribut vars värde måste vara ett QName hade värdet ''{0}''"}, new Object[]{"INVALID_NCNAME_ERR", "Ett attribut vars värde måste vara ett NCName hade värdet ''{0}''"}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_FUNCTION_ERR, "Användning av tilläggsfunktionen ''{0}'' är inte tillåtet när säker bearbetning tillämpas."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_ELEMENT_ERR, "Användning av tilläggselementet ''{0}'' är inte tillåtet när säker bearbetning tillämpas."}};
    }
}
