package ohos.com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_de extends ListResourceBundle {
    @Override // java.util.ListResourceBundle
    public Object[][] getContents() {
        return new Object[][]{new Object[]{BasisLibrary.RUN_TIME_INTERNAL_ERR, "Interner Laufzeitfehler in \"{0}\""}, new Object[]{BasisLibrary.RUN_TIME_COPY_ERR, "Laufzeitfehler beim Ausführen von <xsl:copy>."}, new Object[]{"DATA_CONVERSION_ERR", "Ungültige Konvertierung von \"{0}\" in \"{1}\"."}, new Object[]{BasisLibrary.EXTERNAL_FUNC_ERR, "Externe Funktion \"{0}\" nicht unterstützt von XSLTC."}, new Object[]{BasisLibrary.EQUALITY_EXPR_ERR, "Unbekannter Argumenttyp in Gleichheitsausdruck."}, new Object[]{BasisLibrary.INVALID_ARGUMENT_ERR, "Ungültiger Argumenttyp \"{0}\" in Aufruf von \"{1}\""}, new Object[]{BasisLibrary.FORMAT_NUMBER_ERR, "Versuch, Zahl \"{0}\" mit Muster \"{1}\" zu formatieren."}, new Object[]{BasisLibrary.ITERATOR_CLONE_ERR, "Iterator \"{0}\" kann nicht geclont werden."}, new Object[]{BasisLibrary.AXIS_SUPPORT_ERR, "Iterator für Achse \"{0}\" nicht unterstützt."}, new Object[]{BasisLibrary.TYPED_AXIS_SUPPORT_ERR, "Iterator für typisierte Achse \"{0}\" nicht unterstützt."}, new Object[]{"STRAY_ATTRIBUTE_ERR", "Attribut \"{0}\" außerhalb des Elements."}, new Object[]{BasisLibrary.STRAY_NAMESPACE_ERR, "Namespace-Deklaration {0}={1} außerhalb des Elements."}, new Object[]{BasisLibrary.NAMESPACE_PREFIX_ERR, "Namespace für Präfix \"{0}\" wurde nicht deklariert."}, new Object[]{BasisLibrary.DOM_ADAPTER_INIT_ERR, "DOMAdapter mit falschem Typ von Quell-DOM erstellt."}, new Object[]{BasisLibrary.PARSER_DTD_SUPPORT_ERR, "Der verwendete SAX-Parser verarbeitet keine DTD-Deklarationsereignisse."}, new Object[]{BasisLibrary.NAMESPACES_SUPPORT_ERR, "Der verwendete SAX-Parser unterstützt keine XML-Namespaces."}, new Object[]{BasisLibrary.CANT_RESOLVE_RELATIVE_URI_ERR, "URI-Referenz \"{0}\" konnte nicht aufgelöst werden."}, new Object[]{"UNSUPPORTED_XSL_ERR", "Nicht unterstütztes XSL-Element \"{0}\""}, new Object[]{"UNSUPPORTED_EXT_ERR", "Unbekannte XSLTC-Erweiterung \"{0}\""}, new Object[]{BasisLibrary.UNKNOWN_TRANSLET_VERSION_ERR, "Das angegebene Translet \"{0}\" wurde mit einer neueren Version von XSLTC als die verwendete Version der XSLTC-Laufzeit erstellt. Sie müssen das Stylesheet neu kompilieren oder eine aktuellere Version von XSLTC verwenden, um dieses Translet auszuführen."}, new Object[]{"INVALID_QNAME_ERR", "Ein Attribut, dessen Wert ein QName sein muss, hatte den Wert \"{0}\""}, new Object[]{"INVALID_NCNAME_ERR", "Ein Attribut, dessen Wert ein NCName sein muss, hatte den Wert \"{0}\""}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_FUNCTION_ERR, "Verwendung der Erweiterungsfunktion \"{0}\" ist nicht zulässig, wenn das Feature für die sichere Verarbeitung auf \"true\" gesetzt ist."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_ELEMENT_ERR, "Verwendung des Erweiterungselements \"{0}\" ist nicht zulässig, wenn das Feature für die sichere Verarbeitung auf \"true\" gesetzt ist."}};
    }
}
