package com.huawei.device.connectivitychrlog;

public class CSubWL_COUNTERS extends ChrLogBaseModel {
    public ENCSubEventId enSubEventId = new ENCSubEventId();
    public LogInt imonitorDuration = new LogInt();
    public LogInt ireset = new LogInt();
    public LogInt irxbadcm = new LogInt();
    public LogInt irxbadds = new LogInt();
    public LogInt irxbadfcs = new LogInt();
    public LogInt irxbadplcp = new LogInt();
    public LogInt irxbadproto = new LogInt();
    public LogInt irxbeaconmbss = new LogInt();
    public LogInt irxbeaconobss = new LogInt();
    public LogInt irxbyte = new LogInt();
    public LogInt irxcfrmmcast = new LogInt();
    public LogInt irxcfrmocast = new LogInt();
    public LogInt irxcfrmucast = new LogInt();
    public LogInt irxcrsglitch = new LogInt();
    public LogInt irxdfrmmcast = new LogInt();
    public LogInt irxdfrmocast = new LogInt();
    public LogInt irxdfrmucastmbss = new LogInt();
    public LogInt irxdfrmucastobss = new LogInt();
    public LogInt irxfrag = new LogInt();
    public LogInt irxframe = new LogInt();
    public LogInt irxmfrmmcast = new LogInt();
    public LogInt irxmfrmocast = new LogInt();
    public LogInt irxmfrmucastmbss = new LogInt();
    public LogInt irxmulti = new LogInt();
    public LogInt irxnobuf = new LogInt();
    public LogInt irxnondata = new LogInt();
    public LogInt irxstrt = new LogInt();
    public LogInt itxallfrm = new LogInt();
    public LogInt itxbyte = new LogInt();
    public LogInt itxctl = new LogInt();
    public LogInt itxerror = new LogInt();
    public LogInt itxfail = new LogInt();
    public LogInt itxfrag = new LogInt();
    public LogInt itxframe = new LogInt();
    public LogInt itxfrmsnt = new LogInt();
    public LogInt itxnoack = new LogInt();
    public LogInt itxnoassoc = new LogInt();
    public LogInt itxnobuf = new LogInt();
    public LogInt itxnocts = new LogInt();
    public LogInt itxphyerr = new LogInt();
    public LogInt itxphyerror = new LogInt();
    public LogInt itxretrans = new LogInt();
    public LogInt itxrts = new LogInt();

    public CSubWL_COUNTERS() {
        this.lengthMap.put("enSubEventId", Integer.valueOf(2));
        this.fieldMap.put("enSubEventId", this.enSubEventId);
        this.lengthMap.put("imonitorDuration", Integer.valueOf(4));
        this.fieldMap.put("imonitorDuration", this.imonitorDuration);
        this.lengthMap.put("itxframe", Integer.valueOf(4));
        this.fieldMap.put("itxframe", this.itxframe);
        this.lengthMap.put("itxbyte", Integer.valueOf(4));
        this.fieldMap.put("itxbyte", this.itxbyte);
        this.lengthMap.put("itxfail", Integer.valueOf(4));
        this.fieldMap.put("itxfail", this.itxfail);
        this.lengthMap.put("itxfrag", Integer.valueOf(4));
        this.fieldMap.put("itxfrag", this.itxfrag);
        this.lengthMap.put("itxfrmsnt", Integer.valueOf(4));
        this.fieldMap.put("itxfrmsnt", this.itxfrmsnt);
        this.lengthMap.put("itxnoack", Integer.valueOf(4));
        this.fieldMap.put("itxnoack", this.itxnoack);
        this.lengthMap.put("itxphyerr", Integer.valueOf(4));
        this.fieldMap.put("itxphyerr", this.itxphyerr);
        this.lengthMap.put("itxnobuf", Integer.valueOf(4));
        this.fieldMap.put("itxnobuf", this.itxnobuf);
        this.lengthMap.put("itxnocts", Integer.valueOf(4));
        this.fieldMap.put("itxnocts", this.itxnocts);
        this.lengthMap.put("itxrts", Integer.valueOf(4));
        this.fieldMap.put("itxrts", this.itxrts);
        this.lengthMap.put("itxphyerror", Integer.valueOf(4));
        this.fieldMap.put("itxphyerror", this.itxphyerror);
        this.lengthMap.put("itxnoassoc", Integer.valueOf(4));
        this.fieldMap.put("itxnoassoc", this.itxnoassoc);
        this.lengthMap.put("itxctl", Integer.valueOf(4));
        this.fieldMap.put("itxctl", this.itxctl);
        this.lengthMap.put("itxallfrm", Integer.valueOf(4));
        this.fieldMap.put("itxallfrm", this.itxallfrm);
        this.lengthMap.put("itxerror", Integer.valueOf(4));
        this.fieldMap.put("itxerror", this.itxerror);
        this.lengthMap.put("itxretrans", Integer.valueOf(4));
        this.fieldMap.put("itxretrans", this.itxretrans);
        this.lengthMap.put("irxframe", Integer.valueOf(4));
        this.fieldMap.put("irxframe", this.irxframe);
        this.lengthMap.put("irxbyte", Integer.valueOf(4));
        this.fieldMap.put("irxbyte", this.irxbyte);
        this.lengthMap.put("irxfrag", Integer.valueOf(4));
        this.fieldMap.put("irxfrag", this.irxfrag);
        this.lengthMap.put("irxbadfcs", Integer.valueOf(4));
        this.fieldMap.put("irxbadfcs", this.irxbadfcs);
        this.lengthMap.put("irxnobuf", Integer.valueOf(4));
        this.fieldMap.put("irxnobuf", this.irxnobuf);
        this.lengthMap.put("irxbadcm", Integer.valueOf(4));
        this.fieldMap.put("irxbadcm", this.irxbadcm);
        this.lengthMap.put("irxbadplcp", Integer.valueOf(4));
        this.fieldMap.put("irxbadplcp", this.irxbadplcp);
        this.lengthMap.put("irxcrsglitch", Integer.valueOf(4));
        this.fieldMap.put("irxcrsglitch", this.irxcrsglitch);
        this.lengthMap.put("irxbadproto", Integer.valueOf(4));
        this.fieldMap.put("irxbadproto", this.irxbadproto);
        this.lengthMap.put("irxmulti", Integer.valueOf(4));
        this.fieldMap.put("irxmulti", this.irxmulti);
        this.lengthMap.put("irxnondata", Integer.valueOf(4));
        this.fieldMap.put("irxnondata", this.irxnondata);
        this.lengthMap.put("irxbadds", Integer.valueOf(4));
        this.fieldMap.put("irxbadds", this.irxbadds);
        this.lengthMap.put("ireset", Integer.valueOf(4));
        this.fieldMap.put("ireset", this.ireset);
        this.lengthMap.put("irxdfrmocast", Integer.valueOf(4));
        this.fieldMap.put("irxdfrmocast", this.irxdfrmocast);
        this.lengthMap.put("irxmfrmocast", Integer.valueOf(4));
        this.fieldMap.put("irxmfrmocast", this.irxmfrmocast);
        this.lengthMap.put("irxdfrmucastmbss", Integer.valueOf(4));
        this.fieldMap.put("irxdfrmucastmbss", this.irxdfrmucastmbss);
        this.lengthMap.put("irxmfrmucastmbss", Integer.valueOf(4));
        this.fieldMap.put("irxmfrmucastmbss", this.irxmfrmucastmbss);
        this.lengthMap.put("irxbeaconmbss", Integer.valueOf(4));
        this.fieldMap.put("irxbeaconmbss", this.irxbeaconmbss);
        this.lengthMap.put("irxdfrmucastobss", Integer.valueOf(4));
        this.fieldMap.put("irxdfrmucastobss", this.irxdfrmucastobss);
        this.lengthMap.put("irxbeaconobss", Integer.valueOf(4));
        this.fieldMap.put("irxbeaconobss", this.irxbeaconobss);
        this.lengthMap.put("irxstrt", Integer.valueOf(4));
        this.fieldMap.put("irxstrt", this.irxstrt);
        this.lengthMap.put("irxcfrmocast", Integer.valueOf(4));
        this.fieldMap.put("irxcfrmocast", this.irxcfrmocast);
        this.lengthMap.put("irxcfrmucast", Integer.valueOf(4));
        this.fieldMap.put("irxcfrmucast", this.irxcfrmucast);
        this.lengthMap.put("irxdfrmmcast", Integer.valueOf(4));
        this.fieldMap.put("irxdfrmmcast", this.irxdfrmmcast);
        this.lengthMap.put("irxmfrmmcast", Integer.valueOf(4));
        this.fieldMap.put("irxmfrmmcast", this.irxmfrmmcast);
        this.lengthMap.put("irxcfrmmcast", Integer.valueOf(4));
        this.fieldMap.put("irxcfrmmcast", this.irxcfrmmcast);
        this.enSubEventId.setValue("WL_COUNTERS");
    }
}
