package ohos.media.camera.params.adapter;

import ohos.agp.utils.Rect;
import ohos.location.Location;
import ohos.media.camera.params.ParameterKey;

public class InnerParameterKey {
    public static final ParameterKey.Key<Boolean> AE_LOCK = new ParameterKey.Key<>("ohos.camera.aeLock", Boolean.class);
    public static final ParameterKey.Key<Integer> AE_MODE = new ParameterKey.Key<>("ohos.camera.aeMode", Integer.class);
    public static final ParameterKey.Key<Integer> AE_PRECAPTURE_TRIGGER = new ParameterKey.Key<>("ohos.camera.aePrecaptureTrigger", Integer.class);
    public static final ParameterKey.Key<Rect> AE_REGION = new ParameterKey.Key<>("ohos.camera.aeRegion", Rect.class);
    public static final ParameterKey.Key<Integer> AE_TRIGGER = new ParameterKey.Key<>("ohos.camera.aeTrigger", Integer.class);
    public static final ParameterKey.Key<Integer> AF_MODE = new ParameterKey.Key<>("ohos.camera.afMode", Integer.class);
    public static final ParameterKey.Key<Rect> AF_REGION = new ParameterKey.Key<>("ohos.camera.afRegion", Rect.class);
    public static final ParameterKey.Key<Integer> AF_TRIGGER = new ParameterKey.Key<>("ohos.camera.afTrigger", Integer.class);
    public static final ParameterKey.Key<Byte> AF_TRIGGER_LOCK = new ParameterKey.Key<>("ohos.camera.afTriggerLock", Byte.class);
    public static final ParameterKey.Key<Integer> API_VERSION = new ParameterKey.Key<>("ohos.camera.apiVersion", Integer.class);
    public static final ParameterKey.Key<Byte> BEAUTY_MULTI_SETTING_MODE = new ParameterKey.Key<>("ohos.camera.specificBeautyMultiSettingMode", Byte.class);
    public static final ParameterKey.Key<Byte> BEST_SHOT_MODE = new ParameterKey.Key<>("ohos.camera.bestShotMode", Byte.class);
    public static final ParameterKey.Key<Byte> BODY_SHAPING_LEVEL = new ParameterKey.Key<>("ohos.camera.bodyShapingLevel", Byte.class);
    public static final ParameterKey.Key<Byte> BRIGHTNESS_VALUE = new ParameterKey.Key<>("ohos.camera.brightnessValue", Byte.class);
    public static final ParameterKey.Key<Byte> BURST_SNAPSHOT_MODE = new ParameterKey.Key<>("ohos.camera.burstSnapshotMode", Byte.class);
    public static final ParameterKey.Key<Byte> CAMERA_FLAG = new ParameterKey.Key<>("ohos.camera.camera2Flag", Byte.class);
    public static final ParameterKey.Key<Integer> CAMERA_SCENE_MODE = new ParameterKey.Key<>("ohos.camera.cameraSceneMode", Integer.class);
    public static final ParameterKey.Key<Integer> CAMERA_SESSION_SCENE_MODE = new ParameterKey.Key<>("ohos.camera.cameraSessionSceneMode", Integer.class);
    public static final ParameterKey.Key<Byte> CAPTURE_MIRROR = new ParameterKey.Key<>("ohos.camera.captureMirrorMode", Byte.class);
    public static final ParameterKey.Key<Integer> COLOR_EFFECT_LEVEL = new ParameterKey.Key<>("ohos.camera.colorEffectLevel", Integer.class);
    public static final ParameterKey.Key<Byte> COLOR_EFFECT_MODE = new ParameterKey.Key<>("ohos.camera.colorEffectMode", Byte.class);
    public static final ParameterKey.Key<Byte> COLOR_MODE = new ParameterKey.Key<>("ohos.camera.colorMode", Byte.class);
    public static final ParameterKey.Key<Byte> CONTRAST_VALUE = new ParameterKey.Key<>("ohos.camera.contrastValue", Byte.class);
    public static final ParameterKey.Key<int[]> CONTROL_AE_REGIONS = new ParameterKey.Key<>("ohos.camera.aeRegions", int[].class);
    public static final ParameterKey.Key<int[]> CONTROL_AF_REGIONS = new ParameterKey.Key<>("ohos.camera.afRegions", int[].class);
    public static final ParameterKey.Key<Byte> DM_WATERMARK_MODE = new ParameterKey.Key<>("ohos.camera.dmWaterMarkMode", Byte.class);
    public static final ParameterKey.Key<Byte> DUAL_SENSOR_MODE = new ParameterKey.Key<>("ohos.camera.dualSensorMode", Byte.class);
    public static final ParameterKey.Key<Integer> FACE_BEAUTY_LEVEL = new ParameterKey.Key<>("ohos.camera.faceBeautyLevel", Integer.class);
    public static final ParameterKey.Key<Byte> FACE_BEAUTY_MODE = new ParameterKey.Key<>("ohos.camera.faceBeautyMode", Byte.class);
    public static final ParameterKey.Key<Integer> FACE_DETECTION_TYPE = new ParameterKey.Key<>("ohos.camera.faceDetectionType", Integer.class);
    public static final ParameterKey.Key<Integer> FLASH_MODE = new ParameterKey.Key<>("ohos.camera.flashMode", Integer.class);
    public static final ParameterKey.Key<Integer> HIGH_VIDEO_FPS = new ParameterKey.Key<>("ohos.camera.highVideoFps", Integer.class);
    public static final ParameterKey.Key<Byte> IMAGE_FOREGROUND_PROCESS_MODE = new ParameterKey.Key<>("ohos.camera.postProcessForegroundReturnMode", Byte.class);
    public static final ParameterKey.Key<Byte> IMAGE_POST_PROCESS_MODE = new ParameterKey.Key<>("ohos.camera.imagePostProcessMode", Byte.class);
    public static final ParameterKey.Key<Integer> IMAGE_ROTATION = new ParameterKey.Key<>("ohos.camera.imageRotation", Integer.class);
    public static final ParameterKey.Key<byte[]> JPEG_FILE_NAME = new ParameterKey.Key<>("ohos.camera.jpegFileName", byte[].class);
    public static final ParameterKey.Key<Float> LENS_FOCUS_DISTANCE = new ParameterKey.Key<>("ohos.camera.lensFocusDistance", Float.class);
    public static final ParameterKey.Key<Integer> LENS_OPTICAL_STABILIZATION_MODE = new ParameterKey.Key<>("ohos.camera.opticalStabilization", Integer.class);
    public static final ParameterKey.Key<Location> LOCATION = new ParameterKey.Key<>("ohos.camera.location", Location.class);
    public static final ParameterKey.Key<Integer> MANUAL_FOCUS_VALUE = new ParameterKey.Key<>("ohos.camera.manualFocusValue", Integer.class);
    public static final ParameterKey.Key<Byte> MASTER_AI_ENABLE = new ParameterKey.Key<>("ohos.camera.masterAIEnable", Byte.class);
    public static final ParameterKey.Key<Integer> MASTER_AI_ENTER_MODE = new ParameterKey.Key<>("ohos.camera.smartSuggestEnterMode", Integer.class);
    public static final ParameterKey.Key<Byte> METERING_MODE = new ParameterKey.Key<>("ohos.camera.meteringMode", Byte.class);
    public static final ParameterKey.Key<Byte> NICE_FOOD_MODE = new ParameterKey.Key<>("ohos.camera.niceFoodMode", Byte.class);
    public static final ParameterKey.Key<int[]> REAL_VIDEO_SIZE = new ParameterKey.Key<>("ohos.camera.videoStreamResolution", int[].class);
    public static final ParameterKey.Key<Byte> SATURATION_VALUE = new ParameterKey.Key<>("ohos.camera.saturationValue", Byte.class);
    public static final ParameterKey.Key<Rect> SCALER_CROP_REGION = new ParameterKey.Key<>("ohos.camera.cropRegion", Rect.class);
    public static final ParameterKey.Key<Byte> SENSOR_HDR_MODE = new ParameterKey.Key<>("ohos.camera.sensorHdrMode", Byte.class);
    public static final ParameterKey.Key<Boolean> SMART_CAPTURE = new ParameterKey.Key<>("ohos.camera.smartCapture", Boolean.class);
    public static final ParameterKey.Key<Byte> SMART_CAPTURE_ENABLE = new ParameterKey.Key<>("ohos.camera.smartCaptureEnable", Byte.class);
    public static final ParameterKey.Key<Integer> SMART_SUGGEST_CONFIRM = new ParameterKey.Key<>("ohos.camera.smartSuggestConfirm", Integer.class);
    public static final ParameterKey.Key<Integer> SMART_SUGGEST_DISMISS = new ParameterKey.Key<>("ohos.camera.smartSuggestDismiss", Integer.class);
    public static final ParameterKey.Key<Integer> SMART_SUGGEST_EXIT_MODE = new ParameterKey.Key<>("ohos.camera.smartSuggestExitMode", Integer.class);
    public static final ParameterKey.Key<Integer> SMART_SUGGEST_RECORD_CLEAR = new ParameterKey.Key<>("ohos.camera.smartSuggestRecordClear", Integer.class);
    public static final ParameterKey.Key<Byte> SMILE_DETECTION = new ParameterKey.Key<>("ohos.camera.smileDetectionMode", Byte.class);
    public static final ParameterKey.Key<Integer> VIDEO_DYNAMIC_FPS_MODE = new ParameterKey.Key<>("ohos.camera.videoDynamicFpsMode", Integer.class);
    public static final ParameterKey.Key<Boolean> WATER_MARK = new ParameterKey.Key<>("ohos.camera.waterMark", Boolean.class);
    public static final ParameterKey.Key<Float> ZOOM_RATIO = new ParameterKey.Key<>("ohos.camera.zoom", Float.class);
}
