package com.huawei.i18n.tmr.address.it;

import com.huawei.i18n.tmr.address.util.Regexs;

public class RegularExpression extends Regexs {
    private static final String BLACK_BUILDING = "(in|a)\\s([A-Z][a-z,A-Zè€éòóìàâe'ù]+)(\\s|\\.|,)?";
    private static final String BLACK_STREET = "(in|a)\\s([A-Z][a-z,A-Zè€éòóìàâe'ù]+)(\\s|\\.|,)?";
    private static final String BUILD_KEY_ED_NEW = "((?i)(Villa|piazzale|Garden|Giardino|Farmacia|Stazione|Aeroporto|Piazza|Parco|Lago|Basilica|Politecnico|Liceo|Scuola|Accademia|Chiesa|Duomo|Hotel|Locanda|Trattoria|Osteria|Quadrato|Mercato|Cattedrale|College|Collegio|Facoltà|Parrocchia|Mura|Teatro|Palazzo|Museo|Ufficio Postale|Aula|Sartoria|Cantina|Questura|Stadio|Municipio|Cinema|Ospedale|Spiaggia|Palestra|Bar|Banca|Ristorante|Pasticceria|Lido|Porto|Carica|Libreria|Biblioteca|Chiostro|Cantiere|Sala|Bottega|Laboratorio|Torre|Resort|Fotogallery|Pinacoteca|Reggia|Ponte|Zoo|Centro|Centrale|Istituto|Caffetteria|Tribunale|Campanile|Castello|Giardino|Galleria|Club|Casa)\\s)";
    private static final String BUILD_KEY_ED_REST = "((?i)(Colosseo|Supermarcheto|Drugstore|Piscina|Stagno|Laghetto|Parrochia|Guesthouse|Località|Magazzino|Ateneo|Cafferia|Refettorio|Corporation|Monte|Opere\\s{1,6}Teatrali|Arte\\s{1,6}Drammatica|Casetta\\s{1,6}Giocattolo|Conversario|Nosocomio|Mensa|Parrucchiere|Confettiere|Autostazione|Fermata|Edicola|Chiosco|Cinematografo|Vestibolo|Tavola\\s{1,6}Fredda|Fioraio|Parcheggio|Agriturismo|Banchina|Cartoleria|Ginnasio|Barra|Sbarra|Barretta|Pontile|Imbarcadero|Lavanderia|Bucato|Arsenale|Panetteria|Fruttivendolo|Pescheria|Macelleria|Molo|Concerti|Bettola|Negozio|Panificio|Spaccio|Apartamento|Dimora|Motel|Taverna|Ostello|Asilo|Bistro|Clinica|Tavola\\s{1,6}Calda|Ufficio|pensione|Centrali|Albergo|Caffè|cartoleria|Università)\\s)";
    private static final String CITY_KEY = "(\\s{0,6}(in|,)\\s{0,6})?([,-]?\\s?(IT-\\d{1,5}|I-\\d{1,5}|\\d{1,5})\\s?[,-]?)?\\s*(?:((?i)Milanello|CATANIA|Cortina\\s{1,6}D'Ampezzo|Bologna|Genova\\s{1,6}Pegli|Cortona|Città\\s{1,6}del\\s{1,6}Vaticano|Courmayeur|Cuneo|Abano\\s{1,6}Terme|Abruzzo\\s{0,6}-\\s{0,6}Teramo|Agrigento|Conca\\s{1,6}dei\\s{1,6}Marini|Badia|Roma|Alberobello|Alessandria\\s{1,6}&\\s{1,6}Monferrato|Amalfi\\s{1,6}Coast|Ancona|Aosta\\s{0,6}-\\s{0,6}Courmayeur|Monterosso|Sorrento|Aosta|Arezzo\\s{1,6}Province|Arezzo|Ascoli\\s{1,6}Piceno|Assisi|Avellino|Bari|Bergamo|Brescia|Brindisi|Calabria\\s{1,6}Seaside|Capri\\s{1,6}Island|Carpi|Caserta|Castiglioncello|Cefalu|Chianciano\\s{1,6}Terme|Cinque\\s{1,6}Terre|Como|Elba\\s{1,6}Island|Fabriano|Fano|Ferrara|Florence\\s{1,6}Province|Florence|Foligno|Forli|Garda\\s{1,6}Lake|Genova|Grosseto|Gubbio|Ischia\\s{1,6}Island|Italian\\s{1,6}Riviera|La\\s{1,6}Spezia|L'Aquila|Lecco|Livorno|Lucca|Macerata|Maggiore\\s{1,6}and\\s{1,6}Orta\\s{1,6}Lakes|Maratea|Matera|Melfi|Messina|Milan\\s{1,6}Province|Milano|Milan|Modena|Montecatini\\s{1,6}Terme|Montepulciano|Naples|Ostuni|Padova|Paestum|Palermo|Parma|Perugia|Pescasseroli|Piacenza|Pisa|Porto\\s{1,6}San\\s{1,6}Giorgio|Portofino\\s{1,6}and\\s{1,6}Tigullio|Positano|Prato|Puglia\\s{1,6}Seaside|Ragusa|Ravenna|Reggio\\s{1,6}Emilia|Riccione|Rieti|Rimini|Rome\\s{1,6}Province|Salerno|San\\s{1,6}Gimignano|San\\s{1,6}Giovanni\\s{1,6}Rotondo|Sardinia|Sicily|Siena|Siracusa|Sorrento|Spoleto|Taormina|Terni|The\\s{1,6}Alps\\s{0,6}-\\s{0,6}Dolomiti|Tirrenian\\s{1,6}Sea\\s{1,6}Coast|Torino|Trapani|Trento|Treviso|Trieste|Tropea|Turin|Tuscany\\s{0,6}-\\s{0,6}Chianti|Varese|Venice\\s{1,6}Province|Venice|Verona|Versilia|RomaInizio|Vicenza|Wine\\s{1,6}Route|Rome)(?:\\s*\\([A-Z]{2}\\))?|([(]?[A-Z][A-Z][)]?))[,.!]*";
    private static final String COUNTRY = "[,-]?\\s?(Italia)";
    private static final String PREPANDWORDS_ST = "((nella|nei|per|nello|negli|nelle|nel|nell'|al|ai|allo|agli|alla|alle|del|dei|dello|degli|della|delle|sul|sui|sullo|sugli|sulla|sulle|dalla|dai|dallo|dagli|dalle|dal|S\\.|di|dì|su|est|da)\\s+([A-Z][a-z,A-Zè€éòóìàâe'ù]*\\s*)|([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}((in|a)\\s+([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*){1,4})?";
    private static final String PREPAND_WORDS = "((nella|nei|per|nello|negli|nelle|nel|nell'|al|ai|allo|agli|alla|alle|del|dei|dello|degli|della|delle|sul|sui|sullo|sugli|sulla|sulle|dalla|dai|dallo|dagli|dalle|dal|S\\.|di|dì|a|su|est|da)\\s+([A-Z][a-z,A-Zè€éòóìàâe'ù]*\\s*)|([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}(in\\s+([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*){1,4})?";
    private static final String REGION = "\\s?(Abruzzi|Basilicata|Calabria|Campania|Emilia\\s{0,6}-\\s{0,6}Romagna|Friuli\\s{0,6}-\\s{0,6}Venezia\\s{1,6}Giulia|Lazio|Liguria|Lombardia|Marche|Molise|Piemonte|Puglia|Sardegna|Sicilia|Toscana|Trentino\\s{0,6}-\\s{0,6}Alto\\s{1,6}Adige|Umbria|Valle\\s{1,6}d'Aosta|Veneto)";
    private static final String REG_ED_1 = "(Torre\\s{1,6}di\\s{1,6}Pisa|Pizza\\s{1,6}Hut|Colosseo\\s{1,6}di\\s{1,6}Roma|Museo\\s{1,6}archeologico|Campanile\\s{1,6}di\\s{1,6}Giotto|Battistero\\s{1,6}di\\s{1,6}San\\s{1,6}Giovanni|Harvard|Pantheon|Fontana\\s{1,6}di\\s{1,6}Trevi)|((?i)(Villa|piazzale|Garden|Giardino|Farmacia|Stazione|Aeroporto|Piazza|Parco|Lago|Basilica|Politecnico|Liceo|Scuola|Accademia|Chiesa|Duomo|Hotel|Locanda|Trattoria|Osteria|Quadrato|Mercato|Cattedrale|College|Collegio|Facoltà|Parrocchia|Mura|Teatro|Palazzo|Museo|Ufficio Postale|Aula|Sartoria|Cantina|Questura|Stadio|Municipio|Cinema|Ospedale|Spiaggia|Palestra|Bar|Banca|Ristorante|Pasticceria|Lido|Porto|Carica|Libreria|Biblioteca|Chiostro|Cantiere|Sala|Bottega|Laboratorio|Torre|Resort|Fotogallery|Pinacoteca|Reggia|Ponte|Zoo|Centro|Centrale|Istituto|Caffetteria|Tribunale|Campanile|Castello|Giardino|Galleria|Club|Casa)\\s)(((nella|nei|per|nello|negli|nelle|nel|nell'|al|ai|allo|agli|alla|alle|del|dei|dello|degli|della|delle|sul|sui|sullo|sugli|sulla|sulle|dalla|dai|dallo|dagli|dalle|dal|S\\.|di|dì|a|su|est|da)\\s+([A-Z][a-z,A-Zè€éòóìàâe'ù]*\\s*)|([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}(in\\s+([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*){1,4})?)";
    private static final String REG_ED_2 = "(Torre\\s{1,6}di\\s{1,6}Pisa|Pizza\\s{1,6}Hut|Colosseo\\s{1,6}di\\s{1,6}Roma|Museo\\s{1,6}archeologico|Campanile\\s{1,6}di\\s{1,6}Giotto|Battistero\\s{1,6}di\\s{1,6}San\\s{1,6}Giovanni|Harvard|Pantheon|Fontana\\s{1,6}di\\s{1,6}Trevi)|((?i)(Colosseo|Supermarcheto|Drugstore|Piscina|Stagno|Laghetto|Parrochia|Guesthouse|Località|Magazzino|Ateneo|Cafferia|Refettorio|Corporation|Monte|Opere\\s{1,6}Teatrali|Arte\\s{1,6}Drammatica|Casetta\\s{1,6}Giocattolo|Conversario|Nosocomio|Mensa|Parrucchiere|Confettiere|Autostazione|Fermata|Edicola|Chiosco|Cinematografo|Vestibolo|Tavola\\s{1,6}Fredda|Fioraio|Parcheggio|Agriturismo|Banchina|Cartoleria|Ginnasio|Barra|Sbarra|Barretta|Pontile|Imbarcadero|Lavanderia|Bucato|Arsenale|Panetteria|Fruttivendolo|Pescheria|Macelleria|Molo|Concerti|Bettola|Negozio|Panificio|Spaccio|Apartamento|Dimora|Motel|Taverna|Ostello|Asilo|Bistro|Clinica|Tavola\\s{1,6}Calda|Ufficio|pensione|Centrali|Albergo|Caffè|cartoleria|Università)\\s)((\\s*([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}([,-]|\\s)*)";
    private static final String REG_ST = "(\\s{0,6},\\s{0,6})?(((?i)(Via|Viale|Corso|Strada|Vicolo)\\s)(((nella|nei|per|nello|negli|nelle|nel|nell'|al|ai|allo|agli|alla|alle|del|dei|dello|degli|della|delle|sul|sui|sullo|sugli|sulla|sulle|dalla|dai|dallo|dagli|dalle|dal|S\\.|di|dì|su|est|da)\\s+([A-Z][a-z,A-Zè€éòóìàâe'ù]*\\s*)|([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}((in|a)\\s+([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*){1,4})?)|(((?i)(Stradone)\\s)(\\s*([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}([,-]|\\s)*))([,-]{0,1}\\s{0,6}(?<!\\d)\\d{1,4}(?!\\d)\\s{0,6}(-\\d{1,4})?)?([,-]*\\s*(IT-(?<!\\d)\\d{5}(?!\\d)|I-(?<!\\d)\\d{5}(?!\\d)|(?<!\\d)\\d{5}(?!\\d))\\s*[,-]*)?";
    private static final String STRESSKEY_1_NEW = "((?i)(Via|Viale|Corso|Strada|Vicolo)\\s)";
    private static final String STRESSKEY_1_REST = "((?i)(Stradone)\\s)";
    private static final String WHITE = "(Torre\\s{1,6}di\\s{1,6}Pisa|Pizza\\s{1,6}Hut|Colosseo\\s{1,6}di\\s{1,6}Roma|Museo\\s{1,6}archeologico|Campanile\\s{1,6}di\\s{1,6}Giotto|Battistero\\s{1,6}di\\s{1,6}San\\s{1,6}Giovanni|Harvard|Pantheon|Fontana\\s{1,6}di\\s{1,6}Trevi)|";
    private static final String WORDS = "(\\s*([A-Z][a-zA-Zè€éòóìàâe'ù]*\\s*)){1,4}([,-]|\\s)*";

    @Override // com.huawei.i18n.tmr.address.util.Regexs
    public void init() {
        put("patternED", REG_ED_1);
        put("patternEDnopre", REG_ED_2);
        put("patternPCcity", CITY_KEY);
        put("patternregion", REGION);
        put("patterncountry", COUNTRY);
        put("patternST", REG_ST);
        put("patternbb", "(in|a)\\s([A-Z][a-z,A-Zè€éòóìàâe'ù]+)(\\s|\\.|,)?");
        put("patternbs", "(in|a)\\s([A-Z][a-z,A-Zè€éòóìàâe'ù]+)(\\s|\\.|,)?");
    }
}
