package com.android.server.wm;

public class HwSplitBarConstants {
    public static final int ADD_SPLIT_BAR = 0;
    public static final int ADD_SPLIT_BAR_DELAYED_TIME = 200;
    public static final long ANIM_DURATION_FOR_SCALE = 200;
    public static final int BLUR_RADIUS = 200;
    public static final int BOTTOM_REGION = 4;
    public static final int CENTER_REGION = 0;
    public static final int CONSTANT_NUM_DEFAULT = -1;
    public static final int CONSTANT_NUM_TWO = 2;
    public static final float COVER_SCALE_DOWN = 0.05f;
    public static final String CURRENT_POSITION = "currentPosition";
    public static final int DARK_MODE_DELAY = 5000;
    public static final long DELAYED_SHOW_SPLIT_BAR = 350;
    public static final int DELAY_DRAG_FULL_LONG_CLICK = 200;
    public static final float DIP_TO_PIXEL_CONSTANT = 0.5f;
    public static final String DISPLAY_HEIGHT = "displayHeight";
    public static final String DISPLAY_ROTATION = "displayRotation";
    public static final String DISPLAY_WIDTH = "displayWidth";
    public static final int DIVIDER_NUM = 6;
    public static final double DOUBLE_MINIMUM_NUMBER = 1.0E-5d;
    public static final int DOWN_SCALE = 20;
    public static final int DRAG_FULL_DEFAULT_COLUMNS = 2;
    public static final int DRAG_FULL_MODE_DRAGABLE = 9;
    public static final String DRAG_FULL_MODE_LINE_COLOR = "dragFullModeLineColor";
    public static final int DRAG_FULL_ONE_GEAR_COLUMNS = 1;
    public static final float DRAG_FULL_ZONE_LARGE_SCALE = 1.06f;
    public static final int DRAG_FULL_ZONE_PADDING = 16;
    public static final int DRAG_FULL_ZONE_SLOP = 60;
    public static final String DRAG_LINE_COLOR = "dragLineColor";
    public static final int DURATION_SINGLE_TO_DOUBLE = 750;
    public static final String END_POSITION = "endPosition";
    public static final String EXIT_REGION = "ExitRegion";
    public static final String EXIT_TO_FULL_BLACK_VIEW_COLOR = "#80000000";
    public static final String FAR_LINE_MARGIN = "farLineMargin";
    public static final String FAR_LINE_TRANS = "farLineTrans";
    public static final int ICON_DRAWABLE_ALPHA = 255;
    public static final float ICON_SCALE_FACTOR = 0.85f;
    public static final String IS_COVER_ANIM_DELAY = "isCoverAnimDelay";
    public static final int LEFT_REGION = 1;
    public static final int MOVE_DELAY_COUNT = 2;
    public static final int MOVE_OFFSET = 1;
    public static final String NEAR_LINE_MARGIN = "nearLineMargin";
    public static final String NEAR_LINE_TRANS = "nearLIneTrans";
    public static final int ON_CONFIGURATION_CHANGED = 3;
    public static final String RECT_FRAME_BORDER_COLOR = "#FF333333";
    public static final int REMOVE_COVER_DELAYED_TIME = 200;
    public static final int REMOVE_SPLIT_BAR = 1;
    public static final float RESIZE_RATIO_1_2 = 0.42f;
    public static final float RESIZE_RATIO_2_1 = 0.58f;
    public static final int RIGHT_REGION = 2;
    public static final int SET_SPLIT_BAR_POSITION = 5;
    public static final int SET_SPLIT_BAR_VISIBLE_IF_NEED = 4;
    public static final float SHARP_CURVE_CX1 = 0.33f;
    public static final float SHARP_CURVE_CX2 = 0.36f;
    public static final float SHARP_CURVE_CY1 = 0.0f;
    public static final float SHARP_CURVE_CY2 = 1.0f;
    public static final float SPLIT_BAR_DARK_MODE = 0.2f;
    public static final String SPLIT_BAR_DISPLAY_ID = "splitBarDisplayId";
    public static final float SPLIT_BAR_DRAGABLE_ALPHA = 0.5f;
    public static final float SPLIT_BAR_LIGHT_MODE = 1.0f;
    public static final float SPLIT_DRAG_FULL_MODE_ZONE_ALPHA = 0.7f;
    public static final String SPLIT_ORIENTATION = "splitOrientation";
    public static final String SPLIT_RATIO = "splitRatio";
    public static final int STACK_NUMBERS = 2;
    public static final int TOP_REGION = 3;
    public static final int UPDATAE_SPLIT_BAR_POS_DELAY_TIME = 100;
    public static final int UPDATE_SPLIT_BAR_POSITION = 2;
    public static final int UPDATE_SPLIT_BAR_POS_WHEN_EXIST = 6;
    public static final int UPDATE_SPLIT_BAR_TO_DRAG_FULL_DARK_MODE = 8;
    public static final int UPDATE_SPLIT_BAR_TO_DRAG_FULL_MODE = 7;
    public static final int VIBRATOR_TIP_TIME = 100;
    public static final String WINDOW_TITLE = "MultiWindowSplitScreenDividerView";

    private HwSplitBarConstants() {
    }
}
