package com.huawei.nb.utils.logger.DiagnoseLogger;

public class DiagnoseLogTitle {

    public enum Type {
        __BEGIN_OF_ODMF_DEFAULT_TYPE(0),
        ODMF_INNER(1),
        __BEGIN_OF_RESOURCE_SYNC_TYPE(100),
        PROCESS_EXCEPTION(101),
        DUPLICATE_STOPPING(102),
        PROCESS_FAIL_TO_STOP_OTHERS(103),
        SYNC_POLICY_NULL(104),
        REQUEST_FAIL_WITH_ENV(105),
        PUSH_MSG_NOT_ADAPT_LOCAL(106),
        QUERY_RESPONSE_HAS_NO_RESID(107),
        QUERY_RESPONSE_JSON_SYNTAXEXCEPTION(108),
        JSON_ARRAY_LONG_ANALYSE_FAIL(109),
        REQUEST_BODY_NULL(110),
        REQUEST_URL_FAIL_FROM_CLOUD(111),
        REQUEST_URL_NOTHING_CAN_UPDATE(112),
        XCHANNEL_PUSH_TOO_MANY_TIMES(113),
        XCHANNEL_PUSH_AN_ABSENT_RESID(114),
        XCHANNEL_PUSH_NULL_MSG(115),
        XCHANNEL_PUSH_WRONG_ACTION(116),
        XCHANNEL_PUSH_WRONG_JSON(117),
        XCHANNEL_PUSH_RES_HAS_NO_PERMISSION(118),
        HIACTION_REGISTER_FAIL(119),
        HIACTION_UNREGISTER_FAIL(120),
        HIACTION_FIRST_REGISTER(121),
        LAZY_UPDATE_CALLBACK_NULL(122),
        LAZY_UPDATE_PARAM_ERROR(123),
        LAZY_DELETE_PARAM_ERROR(124),
        LAZY_REQUESTER_LONG_PARSE_ERROR(125),
        LAZY_REQUESTER_INPUT_LIST_EMPTY(126),
        LAZY_REQUESTER_INPUT_ATTRIBUTE_INVALID(127),
        REMOTEEXCEPTION_HAPPEN(128),
        DELETE_AN_ABSENT_REOSOURCE(129),
        DELETE_RESOURCE_RESULT_FAIL(130),
        GETIMMEDIATE_FAIL_NULL_RES(131),
        GETIMMEDIATE_FAIL_NOT_PRESET_RES(132),
        GETIMMEDIATE_FAIL_ATTRIBUTE_EMPTY(133),
        DOWNLOAD_INTERRUP_BY_ENV(134),
        DOWNLOAD_OVERFLOW_WHEN_NO_WIFI(135),
        DOWNLOAD_STILL_DOWNLOAD(136),
        DOWNLOAD_VERIFY_FAILED(137),
        DOWNLOAD_EXCEPTION_HAPPEN(138),
        DOWNLOAD_LOOSE_RESOURCE(139),
        DOWNLOAD_NEED_NOT_SYNC(140),
        DOWNLOAD_PERMISSION_CLOSED(141),
        DOWNLOAD_RESULT_ONFAILURE(142),
        DOWNLOAD_FAIL_TO_COMPLETE(143),
        POSETHANDLE_UNZIP_AIMODEL_FAIL(144),
        POSETHANDLE_ENCRYPT_FAIL(145),
        POSETHANDLE_DECRYPT_FAIL(146),
        POSETHANDLE_GET_WORKKEY_FAIL(147),
        POSETHANDLE_METADATA_FAIL(148),
        AIMODEL_PERIOD_REQUEST_FAILED(149),
        AIMODEL_JOB_FRESH_DATA(150),
        AIMODEL_DOWNLOAD_TASK_FAIL(151),
        POSETHANDLE_UNZIP_INNER_ZIP_FAIL(152),
        POSETHANDLE_UPDATE_METADATA_FAIL(153),
        DELETE_RESOURCE_RECOVER_FAIL(154),
        __BEGIN_OF_AIMODEL_IMPORT_TYPE(200),
        __BEGIN_OF_POLICY_DATA_DOWNLOAD_TYPE(300);
        
        private final int value;

        private Type(int v) {
            this.value = v;
        }

        public int getValue() {
            return this.value;
        }
    }
}
