package com.huawei.iaware;

import android.rms.iaware.AwareConstant;
import android.rms.iaware.AwareLog;
import android.system.OsConstants;
import android.util.Log;
import java.util.ArrayList;

public class IAwareConstantAL {
    private static final ArrayList<String> EXCEPTION_KEYS_LIST = new ArrayList<>();
    private static final boolean INVALID_BOOLEAN = false;
    static final int INVALID_INT = -559038737;
    private static final String INVALID_STRING = "deadbeef";
    private static final int MAX_NUM = 5;
    private static final String TAG = "IAwareConstantAL";

    public static int getIntConstant(String key) {
        if (key == null || "".equals(key)) {
            AwareLog.e(TAG, "key is null or empty.");
            return INVALID_INT;
        }
        IntConstants[] values = IntConstants.values();
        for (IntConstants intValue : values) {
            if (key.equals(intValue.key)) {
                return intValue.value;
            }
        }
        saveExceptionKey(key);
        AwareLog.e(TAG, "can not find key in IntConstants, key = " + key);
        return INVALID_INT;
    }

    private enum IntConstants {
        IAL_REGISTER_FAILED("REGISTER_FAILED", -1),
        IAL_REGISTER_SUCCESS("REGISTER_SUCCESS", 0),
        RTC_VER_MAJOR("VER_MAJOR", 1),
        RTC_VER_MINOR("VER_MINOR", 0),
        RTC_CURRENT_USER_TYPE("CURRENT_USER_TYPE", AwareConstant.CURRENT_USER_TYPE),
        RTC_BETA_UESR_TYPE("BETA_UESR_TYPE", 3),
        RTC_GPS_STRATEGY("GPS_STRATEGY", 1901),
        RTC_WIFI_FEATURE("WIFI_FEATURE", 1902),
        FEATURETYPE_ALL("FEATURE_ALL", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_ALL)),
        FEATURETYPE_APPACC("FEATURE_APPACC", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_APPACC)),
        FEATURETYPE_INVALIDE_TYPE("FEATURE_INVALIDE_TYPE", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_INVALIDE_TYPE)),
        FEATURETYPE_MEMORY("FEATURE_MEMORY", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_MEMORY)),
        FEATURETYPE_MEMORY2("FEATURE_MEMORY2", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_MEMORY2)),
        FEATURETYPE_APPMNG("FEATURE_APPMNG", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_APPMNG)),
        FEATURETYPE_RESOURCE("FEATURE_RESOURCE", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_RESOURCE)),
        FEATURETYPE_CPU("FEATURE_CPU", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_CPU)),
        FEATURETYPE_INTELLI_REC("FEATURE_INTELLI_REC", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_INTELLI_REC)),
        FEATURETYPE_RECG_FAKEACTIVITY("FEATURE_RECG_FAKEACTIVITY", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_RECG_FAKEACTIVITY)),
        FEATURETYPE_APPSTARTUP("FEATURE_APPSTARTUP", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_APPSTARTUP)),
        FEATURETYPE_BROADCAST("FEATURE_BROADCAST", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_BROADCAST)),
        FEATURETYPE_APPCLEANUP("FEATURE_APPCLEANUP", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_APPCLEANUP)),
        FEATURETYPE_ALARM_MANAGER("FEATURE_ALARM_MANAGER", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_ALARM_MANAGER)),
        FEATURETYPE_SYSLOAD("FEATURE_SYSLOAD", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_SYSLOAD)),
        FEATURETYPE_BROADCASTEX("FEATURE_BROADCASTEX", AwareConstant.FeatureType.getFeatureId(AwareConstant.FeatureType.FEATURE_BROADCASTEX)),
        RESOURCETYPE_SCENE_REC("RESOURCE_SCENE_REC", AwareConstant.ResourceType.getReousrceId(AwareConstant.ResourceType.RESOURCE_SCENE_REC)),
        RESOURCETYPE_GAME_BOOST("RESOURCE_GAME_BOOST", AwareConstant.ResourceType.getReousrceId(AwareConstant.ResourceType.RESOURCE_GAME_BOOST)),
        NRTC_FLASH_HIBERNATION_EVENT_ID("FLASH_HIBERNATION_EVENT_ID", 3001),
        NRTC_SKIPPED_FRAME_EVENT_ID("SKIPPED_FRAME_EVENT_ID", 3003),
        NRTC_SCALE_HIBERNATION_EVENT_ID("SCALE_HIBERNATION_EVENT_ID", 3004),
        NRTC_FIRST_THERMAL_CTRL_EVENT_ID("FIRST_THERMAL_CTRL_EVENT_ID", 2050),
        NRTC_FIRST_UNIPERF_CTRL_EVENT_ID("FIRST_UNIPERF_CTRL_EVENT_ID", 3050),
        NRTC_PROCESS_STATE_CHANGE_EVENT_ID("PROCESS_STATE_CHANGE_EVENT_ID", 2051),
        NRTC_THERMALD_DATA_REPORT_EVENT_ID("THERMALD_DATA_REPORT_EVENT_ID", 2052),
        NRTC_BATERRY_STATUS_CHANGE_EVENT_ID("BATERRY_STATUS_CHANGE_EVENT_ID", 2053),
        NRTC_POWER_CONNECTED_EVENT_ID("POWER_CONNECTED_EVENT_ID", 2054),
        NRTC_POWER_DISCONNECTED_EVENT_ID("POWER_DISCONNECTED_EVENT_ID", 2055),
        NRTC_VR_MODE_CHANGED_EVENT_ID("VR_MODE_CHANGED_EVENT_ID", 2056),
        NRTC_FOLD_STATE_UPDATE_EVENT_ID("FOLD_STATE_UPDATE_EVENT_ID", 2057),
        NRTC_THERMAL_SDK_CALLBACK_EVENT_ID("THERMAL_SDK_CALLBACK_EVENT_ID", 3034),
        NRTC_VIP_THREAD_SET_EVENT_ID("VIP_THREAD_SET_EVENT_ID", 3006),
        NRTC_VIP_THREAD_RESET_EVENT_ID("VIP_THREAD_RESET_EVENT_ID", 3007),
        NRTC_GAME_EGL_REPOERT_EVENT_ID("GAME_EGL_REPOERT_EVENT_ID", 3015),
        NRTC_GAME_KPI_REPORT_EVENT_ID("GAME_KPI_REPORT_EVENT_ID", 3016),
        NRTC_APP_INNER_BOOST_EVENT_ID("APP_INNER_BOOST_EVENT_ID", 3033),
        NRTC_GAME_EGL_WINFRAME_REPORT_EVENT_ID("GAME_EGL_WINFRAME_REPORT_EVENT_ID", 3017),
        NRTC_GAME_AVGFPS_REPORT_EVENT_ID("GAME_AVGFPS_REPORT_EVENT_ID", 2301),
        NRTC_SCREEN_ON_EVENT_ID("SCREEN_ON_EVENT_ID", 2017),
        NRTC_SCREEN_OFF_EVENT_ID("SCREEN_OFF_EVENT_ID", 2016),
        NRTC_TRIGGER_IDLE_EVENT_ID("TRIGGER_IDLE_EVENT_ID", 2018),
        NRTC_MEMORY_RELEASE_EVENT_ID("MEMORY_RELEASE_EVENT_ID", 3002),
        NRTC_FIRST_PRELOAD_EVENT_ID("FIRST_PRELOAD_EVENT_ID", 2030),
        NRTC_APP_KILLED_EVENT_ID("APP_KILLED_EVENT_ID", 2031),
        NRTC_USERHABIT_DATA_LOAD_FINISHED_EVENT_ID("USERHABIT_DATA_LOAD_FINISHED_EVENT_ID", 2032),
        NRTC_FIRST_DEV_SCHED_EVENT_ID("FIRST_DEV_SCHED_EVENT_ID", 2100),
        NRTC_DEV_SCHED_SERVICE_RESTART_EVENT_ID("DEV_SCHED_SERVICE_RESTART_EVENT_ID", 2101),
        NRTC_MULTIWIN_DEV_SCHED_EVENT_ID("MULTIWIN_DEV_SCHED_EVENT_ID", 2102),
        NRTC_ACTIVITY_IN_EVENT_ID("ACTIVITY_IN_EVENT_ID", 2104),
        NRTC_ACTIVITY_OUT_EVENT_ID("ACTIVITY_OUT_EVENT_ID", 2105),
        NRTC_CUST_CONFIG_UPDATE("CUST_CONFIG_UPDATE", 2106),
        RTC_APP_BATTERY_STATEGY("APP_BATTERY_STATEGY_EVENT_ID", 2107),
        NRTC_GAME_SDK_DATA_EVENT_ID("GAME_SDK_DATA_EVENT_ID", 3005),
        NRTC_APP_SDK_DATA_EVENT_ID("APP_SDK_DATA_EVENT_ID", 3009),
        NRTC_APP_SDK_VIP_EVENT_ID("APP_SDK_VIP_EVENT_ID", 3010),
        NRTC_APPSCHEDULE_SDK_DATA_EVENT_ID("APPSCHEDULE_SDK_DATA_EVENT_ID", 3030),
        NRTC_PACKAGE_ADDED_EVENT_ID("PACKAGE_ADDED_EVENT_ID", 2001),
        NRTC_PACKAGE_REMOVED_EVENT_ID("PACKAGE_REMOVED_EVENT_ID", 2002),
        NRTC_HABIT_START_TRAIN_EVENT_ID("HABIT_START_TRAIN_EVENT_ID", 2003),
        NRTC_GAME_TOUCH_UP_EVENT_ID("GAME_TOUCH_UP_EVENT_ID", 3018),
        NRTC_SYSLOAD_SDK_DATA_EVENT_ID("SYSLOAD_SDK_DATA_EVENT_ID", 3031),
        NRTC_SYSLOAD_SDK_CALLBACK_EVENT_ID("SYSLOAD_SDK_CALLBACK_EVENT_ID", 3032),
        NRTC_UI_RENDER_PARALLEL_SDK_CALLBACK_EVENT_ID("UI_RENDER_PARALLEL_SDK_CALLBACK_EVENT_ID", 3040),
        NRTC_DYN_BUFF_SDK_CALLBACK_EVENT_ID("DYN_BUFF_SDK_CALLBACK_EVENT_ID", 3042),
        NRTC_APP_SCENE_DATA_QUERY_EVENT_ID("APP_SCENE_DATA_QUERY_EVENT_ID", 3035),
        NRTC_APP_SCENE_REPORT_RESULT_EVENT_ID("APP_SCENE_REPORT_RESULT_EVENT_ID", 3036),
        NRTC_QUERY_APP_TYPE_EVENT_ID("QUERY_APP_TYPE_EVENT_ID", 3037),
        NRTC_QUERY_APP_TYPE_LIST_EVENT_ID("QUERY_APP_TYPE_LIST_EVENT_ID", 3038),
        NRTC_THERMAL_HIGH_SPEED_EVENT_ID("THERMAL_HIGH_SPEED_EVENT_ID", 3039),
        FOLD_STATE_FOLDED("FOLD_STATE_FOLDED", 2),
        LISTENER_TYPE_FOLD("LISTENER_TYPE_FOLD", 1),
        EVENT_APP_GALLERY_SCALE("EVENT_APP_GALLERY_SCALE", 15014),
        EVENT_APP_SKIPPED_FRAME("EVENT_APP_SKIPPED_FRAME", 15012),
        EVENT_APP_CAMERA_SHOT("EVENT_APP_CAMERA_SHOT", 15011),
        EVENT_APP_REQUEST_MEM("EVENT_APP_REQUEST_MEM", 15010),
        PGSDK_PG_ID_2DGAME_FRONT("PG_ID_2DGAME_FRONT", 10011),
        PGSDK_PG_ID_3DGAME_FRONT("PG_ID_3DGAME_FRONT", 10002),
        PGSDK_PG_ID_VIDEO_START("PG_ID_VIDEO_START", 10015),
        PGSDK_PG_ID_VIDEO_END("PG_ID_VIDEO_END", 10016),
        PGSDK_EVENT_TYPE_ENTER("PG_EVENT_TYPE_ENTER", 1),
        PGSDK_EVENT_TYPE_EXIT("PG_EVENT_TYPE_EXIT", 2),
        PGSDK_PG_ID_BROWSER_FRONT("PG_ID_BROWSER_FRONT", 10001),
        PGSDK_PG_ID_EBOOK_FRONT("PG_ID_EBOOK_FRONT", 10003),
        PGSDK_PG_ID_GALLERY_FRONT("PG_ID_GALLERY_FRONT", 10004),
        PGSDK_PG_ID_CAMERA_FRONT("PG_ID_CAMERA_FRONT", 10007),
        PGSDK_PG_ID_CAMERA_END("PG_ID_CAMERA_END", 10017),
        PGSDK_PG_ID_VIDEO_FRONT("PG_ID_VIDEO_FRONT", 10009),
        PGSDK_PG_ID_LAUNCHER_FRONT("PG_ID_LAUNCHER_FRONT", 10010),
        PGSDK_STATE_AUDIO_OUT("STATE_AUDIO_OUT", 2),
        PGSDK_STATE_AUDIO_IN("STATE_AUDIO_IN", 1),
        PGSDK_TYPE_UNKNOW("PG_TYPE_UNKNOW", -1),
        PGSDK_STATE_THERMAL("STATE_THERMAL", 9),
        UNIPERF_TAG_B_CPU_MAX("UNIPERF_TAG_B_CPU_MAX", 7),
        UNIPERF_TAG_B_CPU_MIN("UNIPERF_TAG_B_CPU_MIN", 6),
        UNIPERF_TAG_M_CPU_MAX("UNIPERF_TAG_M_CPU_MAX", 4),
        UNIPERF_TAG_L_CPU_MAX("UNIPERF_TAG_L_CPU_MAX", 1),
        UNIPERF_TAG_GPU_MAX("UNIPERF_TAG_GPU_MAX", 10),
        UNIPERF_TAG_DDR_MIN("UNIPERF_TAG_DDR_MIN", 12),
        UNIPERF_TAG_IPA_POWER("UNIPERF_TAG_IPA_POWER", 40),
        UNIPERF_TAG_SET_SCHED_LEVEL("UNIPERF_TAG_SET_SCHED_LEVEL", 56),
        UNIPERF_TAG_SCHED_LEVEL_CHANGE_ONE("UNIPERF_TAG_SCHED_LEVEL_CHANGE_ONE", 55),
        UNIPERF_TAG_CTRL_TYPE_NEW("UNIPERF_TAG_CTRL_TYPE_NEW", 57),
        UNIPERF_CLIENT_EAPA("UNIPERF_CLIENT_EAPA", 3),
        UNIPERF_CLIENT_TEMPERATURE_CONTROL("UNIPERF_CLIENT_TEMPERATURE_CONTROL", 2),
        UNIPERF_EVENT_SPECIAL_GAME_SCENE("UNIPERF_EVENT_SPECIAL_GAME_SCENE", 4119),
        UNIPERF_EVENT_ON("UNIPERF_EVENT_ON", 0),
        UNIPERF_EVENT_OFF("UNIPERF_EVENT_OFF", -1),
        PROCESS_COMBINE("PROC_COMBINE", 256),
        PROCESS_OUT_LONG("PROC_OUT_LONG", 8192),
        PROCESS_SPACE_TERM("PROC_SPACE_TERM", 32),
        PROCESS_SHELL_UID("PROC_SHELL_UID", 2000),
        RAPI_IMPORTANCE_FOREGROUND("IMPORTANCE_FOREGROUND", 100),
        APS_FRAMERATE_MIN("APS_FRAMERATE_MIN", 15),
        APS_FRAMERATE_MAX("APS_FRAMERATE_MAX", 120),
        APS_INVALID_PARAM("APS_INVALID_PARAM", -1),
        APS_SERVICE_NOTREADY("APS_SERVICE_NOTREADY", -2),
        HWCFG_CUST_TYPE_CONFIG("CUST_TYPE_CONFIG", 0),
        PKGMON_PACKAGE_PERMANENT_CHANGE("PACKAGE_PERMANENT_CHANGE", 3),
        IDESE_DE_DATA_TYPE_IAWARE("DE_DATA_TYPE_IAWARE", 10),
        APPTYPE_UNKNOWN("APP_TYPE_UNKNOWN", -1),
        APPTYPE_IM("APP_TYPE_IM", 0),
        APPTYPE_EMAIL("APP_TYPE_EMAIL", 1),
        APPTYPE_SPORT("APP_TYPE_SPORT", 2),
        APPTYPE_NAVI("APP_TYPE_NAVI", 3),
        APPTYPE_STOCKS("APP_TYPE_STOCKS", 4),
        APPTYPE_ALARM("APP_TYPE_ALARM", IAwareConstantAL.MAX_NUM),
        APPTYPE_READING("APP_TYPE_READING", 6),
        APPTYPE_MUSIC("APP_TYPE_MUSIC", 7),
        APPTYPE_VIDEO("APP_TYPE_VIDEO", 8),
        APPTYPE_GAME("APP_TYPE_GAME", 9),
        APPTYPE_LEXICON("APP_TYPE_LEXICON", 10),
        APPTYPE_OFFICE("APP_TYPE_OFFICE", 12),
        APPTYPE_SHOPPING("APP_TYPE_SHOPPING", 14),
        APPTYPE_TOOL("APP_TYPE_TOOL", 15),
        APPTYPE_CAMERA("APP_TYPE_CAMERA", 17),
        APPTYPE_BROWSER("APP_TYPE_BROWSER", 18),
        APPTYPE_IME("APP_TYPE_IME", 19),
        APPTYPE_NEWS("APP_TYPE_NEWS", 26),
        APPTYPE_SMS("APP_TYPE_SMS", 27),
        APPTYPE_LAUNCHER("APP_TYPE_LAUNCHER", 28),
        APPTYPE_GALLERY("APP_TYPE_GALLERY", 29),
        APPTYPE_VOIP("APP_TYPE_VOIP", 30),
        APPTYPE_APP_MARKET("APP_TYPE_APP_MARKET", 31),
        APPTYPE_ASSISTANT("APP_TYPE_ASSISTANT", 32),
        APPTYPE_EDUCATION("APP_TYPE_EDUCATION", 33),
        APPTYPE_PAY("APP_TYPE_PAY", 34),
        APPTYPE_DOWN_UP_LOAD("APP_TYPE_DOWN_UP_LOAD", 35),
        APPTYPE_OTHERS("APP_TYPE_OTHERS", 255),
        APPTYPE_LIVE("APP_TYPE_LIVE", 21),
        APPTYPE_PG_LAUNCHER("PG_APP_TYPE_LAUNCHER", 301),
        APPTYPE_PG_SMS("PG_APP_TYPE_SMS", 302),
        APPTYPE_PG_EMAIL("PG_APP_TYPE_EMAIL", 303),
        APPTYPE_PG_INPUTMETHOD("PG_APP_TYPE_INPUTMETHOD", 304),
        APPTYPE_PG_GAME("PG_APP_TYPE_GAME", 305),
        APPTYPE_PG_BROWSER("PG_APP_TYPE_BROWSER", 306),
        APPTYPE_PG_EBOOK("PG_APP_TYPE_EBOOK", 307),
        APPTYPE_PG_VIDEO("PG_APP_TYPE_VIDEO", 308),
        APPTYPE_PG_SCRLOCK("PG_APP_TYPE_SCRLOCK", 309),
        APPTYPE_PG_ALARM("PG_APP_TYPE_ALARM", 310),
        APPTYPE_PG_IM("PG_APP_TYPE_IM", 311),
        APPTYPE_PG_MUSIC("PG_APP_TYPE_MUSIC", 312),
        APPTYPE_PG_NAVIGATION("PG_APP_TYPE_NAVIGATION", 313),
        APPTYPE_PG_LOCATION_PROVIDER("PG_APP_TYPE_LOCATION_PROVIDER", 314),
        APPTYPE_PG_OFFICE("PG_APP_TYPE_OFFICE", 315),
        APPTYPE_PG_GALLERY("PG_APP_TYPE_GALLERY", 316),
        APPTYPE_PG_SIP("PG_APP_TYPE_SIP", 317),
        APPTYPE_PG_NEWS_CLIENT("PG_APP_TYPE_NEWS_CLIENT", 318),
        APPTYPE_PG_SHOP("PG_APP_TYPE_SHOP", 319),
        APPTYPE_PG_APP_MARKET("PG_APP_TYPE_APP_MARKET", 320),
        APPTYPE_PG_LIFE_TOOL("PG_APP_TYPE_LIFE_TOOL", 321),
        APPTYPE_PG_EDUCATION("PG_APP_TYPE_EDUCATION", 322),
        APPTYPE_PG_MONEY("PG_APP_TYPE_MONEY", 323),
        APPTYPE_PG_CAMERA("PG_APP_TYPE_CAMERA", 324),
        APPTYPE_PG_PEDOMETER("PG_APP_TYPE_PEDOMETER", 325),
        APPTYPE_NEEDCHECK("APP_TYPE_NEEDCHECK", -2),
        APPTYPE_ATTRIBUTE_UNKNOWN("APP_ATTRIBUTE_UNKNOWN", -1),
        APPTYPE_ATTRIBUTE_PRELOAD("APP_ATTRIBUTE_PRELOAD", 16),
        APPTYPE_PG_BASE("PG_TYPE_BASE", 300),
        APPTYPE_APPFUNC_NAVI("APP_APPFUNC_NAVI", 4),
        OS_CONST_TIOCOUTQ("TIOCOUTQ", OsConstants.TIOCOUTQ),
        USERHANDLE_PER_USER_RANGE("PER_USER_RANGE", 100000),
        USER_HANDLE_USER_SYSTEM("USER_SYSTEM", 0),
        USER_HANDLE_USER_CURRENT("USER_CURRENT", -2),
        USER_HANDLE_USER_ALL("USER_ALL", -1),
        LOG_POWER_GAMEOF3D_RESUMED("GAMEOF3D_RESUMED", 106),
        LOG_POWER_APP_RUN_FRONT("APP_RUN_FRONT", 113),
        LOG_POWER_FULL_SCREEN("FULL_SCREEN", 120),
        LOG_POWER_FULL_SCREEN_END("FULL_SCREEN_END", 135),
        LOG_POWER_TOUCH_UP("TOUCH_UP", 126),
        LOG_POWER_TOUCH_DOWN("TOUCH_DOWN", 125),
        LOG_POWER_END_CHG_ROTATION("END_CHG_ROTATION", 130),
        LOG_POWER_MUSIC_AUDIO_PLAY("MUSIC_AUDIO_PLAY", 140),
        LOG_POWER_SURFACEVIEW_CREATED("SURFACEVIEW_CREATED", 141),
        LOG_POWER_ENABLE_SENSOR("ENABLE_SENSOR", 143),
        LOG_POWER_VIDEO_START("VIDEO_START", 136),
        LOG_POWER_VIDEO_END("VIDEO_END", 137),
        LOG_POWER_START_CAMERA("START_CAMERA", 129),
        LOG_POWER_END_CAMERA("END_CAMERA", 134),
        LOG_POWER_FIRST_IAWARE_TAG("FIRST_IAWARE_TAG", 2000),
        LOG_POWER_LAST_IAWARE_TAG("LAST_IAWARE_TAG", 2999),
        LOG_POWER_KEYBOARD_SHOW("KEYBOARD_SHOW", 117),
        LOG_POWER_KEYBOARD_HIDE("KEYBOARD_HIDE", 118),
        LOG_POWER_VIDEO_RECORD_START("VIDEO_RECORD_START", 204),
        LOG_POWER_VIDEO_RECORD_STOP("VIDEO_RECORD_STOP", 205),
        SYSPROP_PROP_VALUE_MAX("PROP_VALUE_MAX", 91),
        APP_TYPE_INFO_GAME("APP_TYPE_GAME", 9),
        LOG_DEBUG("LOG_DEBUG", 3),
        JLID_RESOURCE_MANAGER_ID("JLID_RESOURCE_MANAGER_ID", 143),
        JLID_IPA_TRIGGER_ID("JLID_IPA_TRIGGER_ID", 390),
        USERINFO_NO_PROFILE_GROUP_ID("USERINFO_NO_PROFILE_GROUP_ID", -10000),
        HWTRANSCODEEX_PRELOAD_APPLICATION_TRANSACTION("HWTRANSCODEEX_PRELOAD_APPLICATION_TRANSACTION", 506),
        PARSE_IS_REMOVABLE_PREINSTALLED_APK("PARSE_IS_REMOVABLE_PREINSTALLED_APK", 33554432),
        IAL_INVALID_INT("INVALID_INT", IAwareConstantAL.INVALID_INT);
        
        private String key;
        private int value;

        private IntConstants(String key2, int value2) {
            this.key = key2;
            this.value = value2;
        }
    }

    public static String getStringConstant(String key) {
        String arrayList;
        if (key == null || "".equals(key)) {
            return INVALID_STRING;
        }
        if ("EXCEPTION_CONSTANT_KEYS".equals(key)) {
            synchronized (EXCEPTION_KEYS_LIST) {
                arrayList = EXCEPTION_KEYS_LIST.size() == 0 ? null : EXCEPTION_KEYS_LIST.toString();
            }
            return arrayList;
        }
        StringConstants[] values = StringConstants.values();
        for (StringConstants stringValue : values) {
            if (key.equals(stringValue.key)) {
                return stringValue.value;
            }
        }
        saveExceptionKey(key);
        AwareLog.e(TAG, "can not find key in StringConstants, key = " + key);
        return INVALID_STRING;
    }

    private enum StringConstants {
        DATACON_APPS_PACKAGE_NAME("PACKAGE_NAME", "packageName"),
        ASSOC_RELATION_TYPE("ASSOC_RELATION_TYPE", "relationType"),
        INTENT_ACTION_USER_REMOVED("ACTION_USER_REMOVED", "android.intent.action.USER_REMOVED"),
        INTENT_ACTION_USER_ADDED("ACTION_USER_ADDED", "android.intent.action.USER_ADDED"),
        INTENT_ACTION_PACKAGE_REMOVED("ACTION_PACKAGE_REMOVED", "android.intent.action.PACKAGE_REMOVED"),
        INTENT_ACTION_USER_PRESENT("ACTION_USER_PRESENT", "android.intent.action.USER_PRESENT"),
        INTENT_ACTION_BATTERY_CHANGED("ACTION_BATTERY_CHANGED", "android.intent.action.BATTERY_CHANGED"),
        INTENT_ACTION_POWER_CONNECTED("ACTION_POWER_CONNECTED", "android.intent.action.ACTION_POWER_CONNECTED"),
        INTENT_ACTION_POWER_DISCONNECTED("ACTION_POWER_DISCONNECTED", "android.intent.action.ACTION_POWER_DISCONNECTED"),
        INTENT_EXTRA_REMOVED_FOR_ALL_USERS("EXTRA_REMOVED_FOR_ALL_USERS", "android.intent.extra.REMOVED_FOR_ALL_USERS"),
        INTENT_EXTRA_USER_HANDLE("EXTRA_USER_HANDLE", "android.intent.extra.user_handle"),
        INTENT_ACTION_REQUEST_SHUTDOWN("ACTION_REQUEST_SHUTDOWN", "com.android.internal.intent.action.REQUEST_SHUTDOWN"),
        INTENT_EXTRA_KEY_CONFIRM("EXTRA_KEY_CONFIRM", "android.intent.extra.KEY_CONFIRM"),
        IAL_CALLBACK_SINK("SINK", IAwareCallbackAL.SINK_KEY),
        IAL_CALLBACK_SINK_STATETYPE("SINK_STATETYPE", IAwareCallbackAL.SINK_STATETYPE),
        IAL_CALLBACK_PROCESS_OB("PROCESS_OB", IAwareCallbackAL.PROCESS_OB_KEY),
        IAL_CALLBACK_USERSWITCH_OB("USERSWITCH_OB", IAwareCallbackAL.USERSWITCH_OB_KEY),
        IAL_CALLBACK_USERSWITCH_OB_NAME("USERSWITCH_OB_NAME", IAwareCallbackAL.USERSWITCH_OB_NAME),
        IAL_CALLBACK_THIRD_PARTY_KEY("THIRD_PARTY_KEY", IAwareCallbackAL.THIRD_PARTY_KEY),
        IAL_CALLBACK_GAME_OB("GAME_OB", IAwareCallbackAL.GAME_OB_KEY),
        IAL_CALLBACK_VRSTATE_CALLBACKS_KEY("VRSTATE_CALLBACKS_KEY", IAwareCallbackAL.VRSTATE_CALLBACKS_KEY),
        IAL_PACKAGEMONITOR_OB_KEY("PACKAGEMONITOR_OB_KEY", IAwareCallbackAL.PACKAGEMONITOR_OB_KEY),
        IAL_PM_USER_HANDLE("PM_USER_HANDLE", IAwareCallbackAL.PM_USER_HANDLE),
        IAL_PM_EXTERNAL_STORAGE("PM_EXTERNAL_STORAGE", IAwareCallbackAL.PM_EXTERNAL_STORAGE),
        IAL_CALLBACK_FOLD_TYPE("FOLD_TYPE", IAwareCallbackAL.FOLD_TYPE_KEY),
        IAL_INVALID_STRING("INVALID_STRING", IAwareConstantAL.INVALID_STRING);
        
        private String key;
        private String value;

        private StringConstants(String key2, String value2) {
            this.key = key2;
            this.value = value2;
        }
    }

    public static boolean getBooleanConstant(String key) {
        if (key == null || "".equals(key)) {
            return INVALID_BOOLEAN;
        }
        BooleanConstants[] values = BooleanConstants.values();
        for (BooleanConstants booleanValue : values) {
            if (key.equals(booleanValue.key)) {
                return booleanValue.value;
            }
        }
        saveExceptionKey(key);
        AwareLog.e(TAG, "can not find key in getBooleanConstant, key = " + key);
        return INVALID_BOOLEAN;
    }

    private enum BooleanConstants {
        LOG_HWLOG("HWLOG", Log.HWLog),
        LOG_HWMODULELOG("HWMODULELOG", Log.HWModuleLog),
        IAL_INVALID_BOOLEAN("INVALID_BOOLEAN", IAwareConstantAL.INVALID_BOOLEAN);
        
        private String key;
        private boolean value;

        private BooleanConstants(String key2, boolean value2) {
            this.key = key2;
            this.value = value2;
        }
    }

    private static void saveExceptionKey(String keyName) {
        synchronized (EXCEPTION_KEYS_LIST) {
            if (EXCEPTION_KEYS_LIST.size() < MAX_NUM && !EXCEPTION_KEYS_LIST.contains(keyName)) {
                EXCEPTION_KEYS_LIST.add(keyName);
            }
        }
    }
}
