package android_maps_conflict_avoidance.com.google.googlenav.proto;

import android_maps_conflict_avoidance.com.google.common.io.protocol.ProtoBuf;
import android_maps_conflict_avoidance.com.google.common.io.protocol.ProtoBufType;

public class GmmMessageTypes {
    public static final ProtoBufType ACCEPT_PUBLIC_UPDATE_TERMS_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType ACCEPT_PUBLIC_UPDATE_TERMS_RESPONSE = new ProtoBufType();
    public static final ProtoBufType ACTIVITY = new ProtoBufType();
    public static final ProtoBufType ACTIVITY_FRIEND = new ProtoBufType();
    public static final ProtoBufType AD_EVENT_REPORT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType AD_EVENT_REPORT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType AD_LAYER = new ProtoBufType();
    public static final ProtoBufType BATCH_SPEECH_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType BATCH_SPEECH_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType BATTERY_STEP = new ProtoBufType();
    public static final ProtoBufType BATTERY_STEP_SETTING = new ProtoBufType();
    public static final ProtoBufType BATTERY_STEP_SETTINGS = new ProtoBufType();
    public static final ProtoBufType BUZZ_LAYER_SNIPPET = new ProtoBufType();
    public static final ProtoBufType BUZZ_USER_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType CAPTCHA_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CAPTCHA_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CATEGORY_INFO_LIST_PROTO = new ProtoBufType();
    public static final ProtoBufType CATEGORY_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType CATEGORY_TREE_INNER_NODE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLICKABLE_AREA_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_CAPABILITIES_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_CATEGORY_HISTORY_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_FEATURE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_INFO_MATCH_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_LATITUDE_WIDGET_MODEL_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_LAYER_MANAGER_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_PARAMETERS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_PARAMETERS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_POST_UPDATE_WIZARD_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_PROPERTIES_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_PROPERTIES_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_REQUIREMENTS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_ACTIVITY_FULL_PREFS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_DIRECTIONS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_FRIENDS_MINIMAL_SETTINGS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_FRIENDS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_FRIEND_PHOTOS_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_GAIA_ACCOUNT_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_OPTION_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_PHOTO_CACHE_INDEX = new ProtoBufType();
    public static final ProtoBufType CLIENT_SAVED_SEARCH_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_WAYPOINT_HISTORY_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_WAYPOINT_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType CLIENT_WIZARD_MANAGER_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType COMMENT = new ProtoBufType();
    public static final ProtoBufType COUNTRY_TO_TREE_MAP_PROTO = new ProtoBufType();
    public static final ProtoBufType COUPON_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_ACTIVITY_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType CREATE_ACTIVITY_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_ACTIVITY_RESPONSE = new ProtoBufType();
    public static final ProtoBufType CREATE_ACTIVITY_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_COMMENT_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType CREATE_COMMENT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_COMMENT_RESPONSE = new ProtoBufType();
    public static final ProtoBufType CREATE_COMMENT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_RALLY_POINT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType CREATE_RALLY_POINT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType CURRENT_MOTION_PROTO = new ProtoBufType();
    public static final ProtoBufType DATA_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DATE_TIME_PROTO = new ProtoBufType();
    public static final ProtoBufType DELETE_RALLY_POINT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DELETE_RALLY_POINT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType DEPARTURE_PROTO = new ProtoBufType();
    public static final ProtoBufType DETAIL_ITEM = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_ALERT_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_ICON_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_ICON_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_NOTE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_OPTION_DEFINITION_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_OPTION_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_OPTION_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_OPTION_VALUE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_STEP_CUE_PROTO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_STEP_INFO = new ProtoBufType();
    public static final ProtoBufType DIRECTIONS_TRAFFIC_SPAN = new ProtoBufType();
    public static final ProtoBufType DISMISS_SUGGESTED_FRIEND_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType DISMISS_SUGGESTED_FRIEND_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType DOCUMENT_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType EFFICIENT_MAP_POINT_PROTO = new ProtoBufType();
    public static final ProtoBufType EMAIL_OPTIONS = new ProtoBufType();
    public static final ProtoBufType ENABLE_FEATURE_PARAMETERS_PROTO = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_INTERSECTION = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_PGRAPH = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_ROUTE_NAME = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_SEGMENT = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_SHARED_SEGMENT = new ProtoBufType();
    public static final ProtoBufType EXPORTABLE_SIGN_NAME = new ProtoBufType();
    public static final ProtoBufType FEATURE_RANGE = new ProtoBufType();
    public static final ProtoBufType FEATURE_RESTRICTIONS_PROTO = new ProtoBufType();
    public static final ProtoBufType FEATURE_RESTRICTIONS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType FEATURE_RESTRICTIONS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType FEEDBACK_PROTO = new ProtoBufType();
    public static final ProtoBufType FRIEND_ENTRY = new ProtoBufType();
    public static final ProtoBufType FRIEND_PROFILE = new ProtoBufType();
    public static final ProtoBufType GAIA_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GEOMETRY_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_RESPONSE = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_STREAM_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_STREAM_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_STREAM_RESPONSE = new ProtoBufType();
    public static final ProtoBufType GET_ACTIVITY_STREAM_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIENDS_LOCATIONS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIENDS_LOCATIONS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIENDS_PROFILES_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIENDS_PROFILES_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIEND_FINDER_USERS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_FRIEND_FINDER_USERS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_INVITE_CONTACT_LIST_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_INVITE_CONTACT_LIST_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_INVITE_GROUP_LIST_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_INVITE_GROUP_LIST_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_PRODUCTION_STREAM_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType GET_PRODUCTION_STREAM_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_PRODUCTION_STREAM_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_RALLY_POINTS_FOR_USER_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_RALLY_POINTS_FOR_USER_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_RALLY_POINT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_RALLY_POINT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_SUGGESTED_FRIEND_LIST_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_SUGGESTED_FRIEND_LIST_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_USER_PROFILE_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType GET_USER_PROFILE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_USER_PROFILE_RESPONSE = new ProtoBufType();
    public static final ProtoBufType GET_USER_PROFILE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_USER_STATE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType GET_USER_STATE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType GUIDANCE_EVENT_PROTO = new ProtoBufType();
    public static final ProtoBufType HAS_ACCEPTED_PUBLIC_UPDATE_TERMS_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType HAS_ACCEPTED_PUBLIC_UPDATE_TERMS_RESPONSE = new ProtoBufType();
    public static final ProtoBufType HOTPOT_UPDATE = new ProtoBufType();
    public static final ProtoBufType HOTPOT_UPDATE_PARAM = new ProtoBufType();
    public static final ProtoBufType IMAGE_PROTO = new ProtoBufType();
    public static final ProtoBufType IMPLICIT_LOCATION_PROTO = new ProtoBufType();
    public static final ProtoBufType INVITE_GROUP_ID_PROTO = new ProtoBufType();
    public static final ProtoBufType JOIN_EXPERIMENTS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType JOIN_EXPERIMENTS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType JUSTIFICATION = new ProtoBufType();
    public static final ProtoBufType LAYER_CATEGORY_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_CATEGORY_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_EVENT_REPORT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_EVENT_REPORT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_ITEM_DETAIL_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_ITEM_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_ITEM_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_ITEM_SNIPPET_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_LIST_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_LIST_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_PARAMETER_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_TILE_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_TILE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_TILE_RESPONSE_HEADER_PROTO = new ProtoBufType();
    public static final ProtoBufType LAYER_TILE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCALE_AND_LABEL_PAIR_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCAL_DETAILS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCAL_DETAILS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION = new ProtoBufType();
    public static final ProtoBufType LOCATION_PRIVACY_SETTING_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION_REPORT_REASON = new ProtoBufType();
    public static final ProtoBufType LOCATION_SHIFT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION_SHIFT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION_UPDATE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType LOCATION_UPDATE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType MAPS_ADDRESS_BOOK_ENTRY_PROTO = new ProtoBufType();
    public static final ProtoBufType MAP_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType MAP_POINT_PROTO = new ProtoBufType();
    public static final ProtoBufType MAP_SHOP_RAW_REQUESTS = new ProtoBufType();
    public static final ProtoBufType MAP_TILE_PROTO = new ProtoBufType();
    public static final ProtoBufType MEDIA = new ProtoBufType();
    public static final ProtoBufType MORE_DETAILS_PROTO = new ProtoBufType();
    public static final ProtoBufType NAVIGATION_PARAMETERS_PROTO = new ProtoBufType();
    public static final ProtoBufType NETWORK_INITIATED_PREFERENCE = new ProtoBufType();
    public static final ProtoBufType NOTIFICATIONS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType NOTIFICATIONS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType NOTIFICATION_CHECK_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType NOTIFICATION_CHECK_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType NOTIFICATION_CHECK_RESPONSE = new ProtoBufType();
    public static final ProtoBufType NOTIFICATION_CHECK_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType NOTIFICATION_RESPONSE = new ProtoBufType();
    public static final ProtoBufType PARAMETER_CONFIGURATION_PROTO = new ProtoBufType();
    public static final ProtoBufType PARAMETER_GROUP_PROTO = new ProtoBufType();
    public static final ProtoBufType PARAMETER_RULE_PROTO = new ProtoBufType();
    public static final ProtoBufType PHOTO_DATA = new ProtoBufType();
    public static final ProtoBufType PHOTO_ID = new ProtoBufType();
    public static final ProtoBufType PHOTO_PROTO = new ProtoBufType();
    public static final ProtoBufType PHOTO_UPLOAD = new ProtoBufType();
    public static final ProtoBufType PIXEL_POINT_PROTO = new ProtoBufType();
    public static final ProtoBufType POINT = new ProtoBufType();
    public static final ProtoBufType PROFILE_PHOTO = new ProtoBufType();
    public static final ProtoBufType PROFILE_PHOTO_DATA = new ProtoBufType();
    public static final ProtoBufType PROFILE_PHOTO_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType PROFILE_PHOTO_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType PROFILE_PHOTO_SPEC_PROTO = new ProtoBufType();
    public static final ProtoBufType PUBLIC_UPDATE_TERMS_AND_CONDITIONS = new ProtoBufType();
    public static final ProtoBufType QUERY_PARAMETERS = new ProtoBufType();
    public static final ProtoBufType RALLY_POINT = new ProtoBufType();
    public static final ProtoBufType RATING_PROTO = new ProtoBufType();
    public static final ProtoBufType REAL_ESTATE_QUERY_REFINEMENT = new ProtoBufType();
    public static final ProtoBufType RECOMMENDATION_REASON_PROTO = new ProtoBufType();
    public static final ProtoBufType RECOMMENDATION_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType REPORT_MAP_ISSUE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType REPORT_MAP_ISSUE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType RESOURCE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType RESOURCE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType REVERSE_GEOCODE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType REVERSE_GEOCODE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType REVERSE_GEOCODE_RESULT_PROTO = new ProtoBufType();
    public static final ProtoBufType REVERSE_GEOCODE_RESULT_TYPE_ENUM = new ProtoBufType();
    public static final ProtoBufType REVIEW = new ProtoBufType();
    public static final ProtoBufType REVIEWS_PROTO = new ProtoBufType();
    public static final ProtoBufType REVIEW_PROTO = new ProtoBufType();
    public static final ProtoBufType ROADWAY_PROTO = new ProtoBufType();
    public static final ProtoBufType ROAD_POINT_PROTO = new ProtoBufType();
    public static final ProtoBufType ROUTE_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_DIALOG_PREFERENCES_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_OPTIONS = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_RESPONSE = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_RESPONSE_WITH_PAYLOAD_PROTO = new ProtoBufType();
    public static final ProtoBufType SEARCH_RESULT_PROTO = new ProtoBufType();
    public static final ProtoBufType SECURITY_POPUP_SETTINGS = new ProtoBufType();
    public static final ProtoBufType SEED_PLACE = new ProtoBufType();
    public static final ProtoBufType SERVER_SETTING_PARAMETERS_PROTO = new ProtoBufType();
    public static final ProtoBufType SESAME_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SESAME_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_HTTP_COOKIE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_HTTP_COOKIE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_LOCATION_PRIVACY_SETTING_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_LOCATION_PRIVACY_SETTING_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_NETWORK_INITIATED_PREFERENCE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_NETWORK_INITIATED_PREFERENCE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_USER_STATE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SET_USER_STATE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SHARE_WITH_FRIEND_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SHARE_WITH_FRIEND_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SNAP_TO_PLACE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SNAP_TO_PLACE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SNIPPET_PROTO = new ProtoBufType();
    public static final ProtoBufType SPEECH_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SPEECH_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType STARRING_PREFS_PROTO = new ProtoBufType();
    public static final ProtoBufType STAR_DETAILS_PROTO = new ProtoBufType();
    public static final ProtoBufType STAR_DETAILS_STORAGE_PROTO = new ProtoBufType();
    public static final ProtoBufType STAR_MRUITEM = new ProtoBufType();
    public static final ProtoBufType STAR_PROTO = new ProtoBufType();
    public static final ProtoBufType STAR_RESULT_PROTO = new ProtoBufType();
    public static final ProtoBufType STAR_WITH_DETAILS_PROTO = new ProtoBufType();
    public static final ProtoBufType STEP_PROTO = new ProtoBufType();
    public static final ProtoBufType STREAM = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_METADATA_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_REPORT_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_REPORT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_TAKE_DOWN_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType STREET_VIEW_TAKE_DOWN_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType STRUCTURED_ADDRESS_PROTO = new ProtoBufType();
    public static final ProtoBufType STRUCTURED_INSTRUCTIONS_PROTO = new ProtoBufType();
    public static final ProtoBufType SUBMIT_REVIEW_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SUBMIT_REVIEW_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SUGGESTION_GROUP_PROTO = new ProtoBufType();
    public static final ProtoBufType SUGGESTION_PROTO = new ProtoBufType();
    public static final ProtoBufType SUGGEST_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SUGGEST_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNCED_DATA_CORPUS_STORAGE_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNCED_DATA_PENDING_QUEUE_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNCED_DATA_PREFERENCES_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNCED_DATA_STORAGE_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNCED_DATA_VIEW_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNC_CORPUS_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNC_CORPUS_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNC_ERROR_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNC_ITEM = new ProtoBufType();
    public static final ProtoBufType SYNC_ITEM_UPDATE_REQUEST = new ProtoBufType();
    public static final ProtoBufType SYNC_ITEM_UPDATE_RESPONSE = new ProtoBufType();
    public static final ProtoBufType SYNC_OPERATION = new ProtoBufType();
    public static final ProtoBufType SYNC_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType SYNC_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType TRAFFIC_VECTOR_TILE_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_AGENCY_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_LINE_DISPLAY_PROPERTIES_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_LINE_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_LINE_RESULT_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_LINE_WITH_DEPARTURES_AT_STATION_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_STATION_INFO_PROTO = new ProtoBufType();
    public static final ProtoBufType TRANSIT_STATION_RESULT_PROTO = new ProtoBufType();
    public static final ProtoBufType TRIP_GROUP_AND_DEPARTURES_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_ACTIVITY_REQUEST_PAYLOAD = new ProtoBufType();
    public static final ProtoBufType UPDATE_ACTIVITY_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_ACTIVITY_RESPONSE = new ProtoBufType();
    public static final ProtoBufType UPDATE_ACTIVITY_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_FRIEND_STATE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_FRIEND_STATE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_LOCATION_ACL_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType UPDATE_LOCATION_ACL_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType URL_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType URL_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_CONTENT_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_CONTENT_RESPONSE_META = new ProtoBufType();
    public static final ProtoBufType USER_CONTENT_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_LOCATION_DEBUG_INFO = new ProtoBufType();
    public static final ProtoBufType USER_MAP_LISTING_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_PHOTO_DATA = new ProtoBufType();
    public static final ProtoBufType USER_PROFILE_UPDATE_REQUEST_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_PROFILE_UPDATE_RESPONSE_PROTO = new ProtoBufType();
    public static final ProtoBufType USER_STATE_PROTO = new ProtoBufType();
    public static final ProtoBufType VOICE_SEARCH_LANGUAGE_PROTO = new ProtoBufType();
    public static final ProtoBufType VOICE_SEARCH_PARAMETERS_PROTO = new ProtoBufType();

    static {
        DATE_TIME_PROTO.addElement(275, 1, null).addElement(545, 2, null);
        AD_EVENT_REPORT_REQUEST_PROTO.addElement(540, 1, null).addElement(533, 2, null).addElement(539, 3, DATE_TIME_PROTO);
        CLIENT_CAPABILITIES_PROTO.addElement(533, 1, null).addElement(533, 2, null).addElement(533, 3, null).addElement(1045, 16, null).addElement(536, 17, ProtoBuf.FALSE).addElement(536, 18, ProtoBuf.TRUE);
        CAPTCHA_REQUEST_PROTO.addElement(283, 1, CLIENT_CAPABILITIES_PROTO).addElement(538, 2, new ProtoBufType("ANSWER").addElement(284, 3, null).addElement(284, 4, null));
        CAPTCHA_RESPONSE_PROTO.addElement(277, 1, null).addElement(538, 2, new ProtoBufType("QUESTION").addElement(281, 3, null).addElement(284, 4, null));
        CATEGORY_INFO_PROTO.addElement(533, 1, new Long(1)).addElement(284, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(1051, 5, LOCALE_AND_LABEL_PAIR_PROTO).addElement(533, 6, null);
        LOCALE_AND_LABEL_PAIR_PROTO.addElement(284, 1, null).addElement(540, 2, null).addElement(540, 3, null);
        CATEGORY_TREE_INNER_NODE_PROTO.addElement(284, 1, null).addElement(1052, 2, null);
        COUNTRY_TO_TREE_MAP_PROTO.addElement(284, 1, null).addElement(1052, 2, null).addElement(1051, 3, CATEGORY_TREE_INNER_NODE_PROTO);
        CATEGORY_INFO_LIST_PROTO.addElement(1051, 1, CATEGORY_INFO_PROTO);
        CLIENT_PARAMETERS_REQUEST_PROTO.addElement(1051, 1, PARAMETER_GROUP_PROTO);
        CLIENT_PARAMETERS_RESPONSE_PROTO.addElement(1051, 1, PARAMETER_GROUP_PROTO);
        PARAMETER_GROUP_PROTO.addElement(277, 1, null).addElement(534, 2, null).addElement(539, 3, NAVIGATION_PARAMETERS_PROTO).addElement(539, 4, ENABLE_FEATURE_PARAMETERS_PROTO).addElement(539, 5, SERVER_SETTING_PARAMETERS_PROTO).addElement(539, 6, VOICE_SEARCH_PARAMETERS_PROTO);
        ENABLE_FEATURE_PARAMETERS_PROTO.addElement(536, 1, ProtoBuf.TRUE).addElement(536, 2, ProtoBuf.TRUE).addElement(536, 3, ProtoBuf.TRUE).addElement(536, 4, ProtoBuf.TRUE).addElement(536, 5, ProtoBuf.TRUE).addElement(536, 6, ProtoBuf.TRUE).addElement(536, 7, ProtoBuf.TRUE).addElement(536, 8, ProtoBuf.TRUE).addElement(536, 9, ProtoBuf.TRUE);
        NAVIGATION_PARAMETERS_PROTO.addElement(533, 1, new Long(70)).addElement(535, 2, new Long(650000)).addElement(533, 3, new Long(10)).addElement(533, 4, new Long(120)).addElement(533, 5, new Long(128)).addElement(533, 6, new Long(5)).addElement(533, 7, new Long(10)).addElement(535, 8, new Long(1000000)).addElement(533, 9, new Long(200)).addElement(533, 10, new Long(2000)).addElement(533, 11, new Long(10000)).addElement(533, 12, new Long(1000)).addElement(533, 13, new Long(5)).addElement(533, 14, new Long(96)).addElement(533, 27, new Long(100)).addElement(535, 15, new Long(2000000)).addElement(533, 16, new Long(300)).addElement(533, 17, new Long(900)).addElement(533, 18, new Long(50)).addElement(535, 19, new Long(10000)).addElement(533, 20, new Long(400)).addElement(533, 21, new Long(3)).addElement(533, 22, new Long(1000)).addElement(533, 23, new Long(5000)).addElement(533, 24, new Long(64)).addElement(536, 25, ProtoBuf.TRUE).addElement(533, 26, new Long(3));
        SERVER_SETTING_PARAMETERS_PROTO.addElement(540, 1, null);
        VOICE_SEARCH_PARAMETERS_PROTO.addElement(1051, 1, VOICE_SEARCH_LANGUAGE_PROTO).addElement(540, 2, null);
        VOICE_SEARCH_LANGUAGE_PROTO.addElement(540, 1, "en_US").addElement(540, 2, "American English").addElement(535, 3, new Long(500000));
        PARAMETER_CONFIGURATION_PROTO.addElement(1051, 1, CLIENT_INFO_MATCH_PROTO).addElement(1051, 2, PARAMETER_RULE_PROTO);
        PARAMETER_RULE_PROTO.addElement(1052, 1, null).addElement(1051, 2, PARAMETER_GROUP_PROTO);
        CLIENT_INFO_MATCH_PROTO.addElement(284, 1, null).addElement(1052, 2, null).addElement(1052, 3, null).addElement(1052, 4, null).addElement(1052, 5, null);
        CLIENT_PROPERTIES_REQUEST_PROTO.addElement(540, 1, null).addElement(536, 2, ProtoBuf.FALSE).addElement(533, 3, null).addElement(536, 4, ProtoBuf.FALSE).addElement(540, 5, null).addElement(540, 17, null).addElement(540, 18, null).addElement(540, 19, null).addElement(540, 20, null).addElement(536, 21, ProtoBuf.FALSE).addElement(533, 22, new Long(1)).addElement(1045, 23, null).addElement(533, 24, null).addElement(533, 25, new Long(0)).addElement(1045, 26, null);
        CLIENT_PROPERTIES_RESPONSE_PROTO.addElement(540, 1, null);
        MAP_POINT_PROTO.addElement(277, 1, null).addElement(277, 2, null);
        EFFICIENT_MAP_POINT_PROTO.addElement(289, 1, null).addElement(289, 2, null);
        PIXEL_POINT_PROTO.addElement(277, 1, null).addElement(277, 2, null).addElement(277, 3, null);
        GEOMETRY_PROTO.addElement(277, 1, null).addElement(539, 2, MAP_POINT_PROTO).addElement(538, 3, new ProtoBufType("POLY_LINE").addElement(533, 4, null).addElement(533, 5, null).addElement(537, 6, null)).addElement(538, 7, new ProtoBufType("POLYGON").addElement(533, 8, null).addElement(533, 9, null).addElement(537, 10, null).addElement(533, 11, null).addElement(1049, 12, null)).addElement(539, 13, PIXEL_POINT_PROTO).addElement(539, 14, EFFICIENT_MAP_POINT_PROTO);
        MAP_INFO_PROTO.addElement(283, 1, MAP_POINT_PROTO).addElement(277, 2, null).addElement(277, 3, null).addElement(533, 4, null);
        IMPLICIT_LOCATION_PROTO.addElement(283, 1, MAP_POINT_PROTO).addElement(530, 2, null).addElement(530, 3, null);
        MAP_TILE_PROTO.addElement(277, 1, null).addElement(277, 2, null).addElement(277, 3, null).addElement(277, 4, null).addElement(533, 5, new Long(1));
        DIRECTIONS_ICON_REQUEST_PROTO.addElement(539, 1, CLIENT_CAPABILITIES_PROTO).addElement(533, 2, new Long(1)).addElement(1043, 3, null);
        DIRECTIONS_ICON_RESPONSE_PROTO.addElement(533, 17, new Long(1)).addElement(1050, 1, new ProtoBufType("ICON_DEFINITION").addElement(290, 2, null).addElement(537, 3, null));
        LOCATION_PROTO.addElement(540, 1, null).addElement(539, 2, GEOMETRY_PROTO).addElement(540, 3, null).addElement(533, 5, new Long(0)).addElement(536, 6, ProtoBuf.FALSE);
        TRANSIT_AGENCY_PROTO.addElement(284, 1, null).addElement(540, 2, null).addElement(540, 3, null);
        DIRECTIONS_REQUEST_PROTO.addElement(1045, 1, null).addElement(1051, 2, LOCATION_PROTO).addElement(539, 3, DATE_TIME_PROTO).addElement(533, 4, new Long(0)).addElement(533, 5, new Long(3)).addElement(539, 6, DIRECTIONS_ICON_REQUEST_PROTO).addElement(533, 7, new Long(0)).addElement(545, 8, new Long(0)).addElement(539, 9, MAP_INFO_PROTO).addElement(1051, 10, DIRECTIONS_OPTION_VALUE_PROTO).addElement(536, 11, ProtoBuf.FALSE).addElement(536, 12, ProtoBuf.TRUE).addElement(536, 13, ProtoBuf.FALSE).addElement(536, 25, ProtoBuf.FALSE).addElement(536, 14, ProtoBuf.FALSE).addElement(533, 15, new Long(0)).addElement(536, 16, ProtoBuf.FALSE).addElement(539, 17, CURRENT_MOTION_PROTO).addElement(536, 20, ProtoBuf.FALSE).addElement(536, 21, ProtoBuf.FALSE).addElement(536, 22, ProtoBuf.FALSE).addElement(533, 23, null).addElement(533, 24, null).addElement(539, 26, IMPLICIT_LOCATION_PROTO).addElement(536, 27, ProtoBuf.FALSE).addElement(536, 29, ProtoBuf.FALSE);
        DIRECTIONS_RESPONSE_PROTO.addElement(277, 1, null).addElement(1045, 2, null).addElement(539, 3, DATE_TIME_PROTO).addElement(533, 4, null).addElement(1050, 5, new ProtoBufType("WAYPOINT_FEEDBACK").addElement(277, 6, null).addElement(1051, 7, LOCATION_PROTO).addElement(540, 15, null)).addElement(1050, 8, new ProtoBufType("TRIP").addElement(1051, 9, ROUTE_PROTO).addElement(540, 20, null).addElement(533, 21, new Long(0))).addElement(539, 10, DIRECTIONS_ICON_RESPONSE_PROTO).addElement(540, 11, null).addElement(1051, 12, TRANSIT_AGENCY_PROTO).addElement(533, 13, new Long(0)).addElement(536, 23, null).addElement(1051, 14, DIRECTIONS_OPTION_VALUE_PROTO).addElement(1051, 16, DIRECTIONS_ALERT_PROTO).addElement(1050, 17, new ProtoBufType("ALTERNATE_MODE").addElement(277, 18, null)).addElement(536, 19, ProtoBuf.TRUE).addElement(540, 22, null);
        STEP_PROTO.addElement(533, 1, new Long(0)).addElement(540, 2, null).addElement(533, 3, null).addElement(533, 4, null).addElement(533, 5, null).addElement(540, 6, null).addElement(540, 7, null).addElement(539, 8, DATE_TIME_PROTO).addElement(539, 9, DATE_TIME_PROTO).addElement(533, 10, null).addElement(540, 11, null).addElement(546, 12, null).addElement(540, 13, null).addElement(536, 14, ProtoBuf.TRUE).addElement(533, 15, null).addElement(540, 16, null).addElement(1045, 17, null).addElement(1052, 18, null).addElement(539, 19, STRUCTURED_INSTRUCTIONS_PROTO).addElement(540, 20, null);
        ROUTE_PROTO.addElement(533, 1, null).addElement(533, 2, null).addElement(533, 3, null).addElement(539, 4, DATE_TIME_PROTO).addElement(539, 5, DATE_TIME_PROTO).addElement(540, 6, null).addElement(1050, 7, new ProtoBufType("OFFSET_POLYLINE").addElement(283, 8, GEOMETRY_PROTO).addElement(537, 9, null)).addElement(1050, 12, new ProtoBufType("ETA_FROM_POINT").addElement(533, 13, null).addElement(277, 14, null)).addElement(1051, 10, STEP_PROTO).addElement(533, 11, null).addElement(1051, 15, DIRECTIONS_TRAFFIC_SPAN).addElement(1051, 16, LOCATION_PROTO);
        DIRECTIONS_OPTION_DEFINITION_PROTO.addElement(277, 1, null).addElement(284, 2, null).addElement(277, 3, null).addElement(1050, 4, new ProtoBufType("ALLOWABLE_VALUES").addElement(540, 6, null)).addElement(277, 7, null);
        DIRECTIONS_OPTION_VALUE_PROTO.addElement(277, 1, null).addElement(533, 2, null);
        DIRECTIONS_OPTION_RESPONSE_PROTO.addElement(1051, 1, DIRECTIONS_OPTION_DEFINITION_PROTO);
        DIRECTIONS_ALERT_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(540, 3, null);
        DIRECTIONS_NOTE_PROTO.addElement(533, 1, null).addElement(284, 2, null);
        STRUCTURED_INSTRUCTIONS_PROTO.addElement(533, 1, null).addElement(533, 2, null).addElement(533, 3, null).addElement(1051, 4, DIRECTIONS_STEP_CUE_PROTO).addElement(1051, 5, DIRECTIONS_NOTE_PROTO).addElement(1051, 6, GUIDANCE_EVENT_PROTO).addElement(533, 7, null);
        DIRECTIONS_STEP_CUE_PROTO.addElement(533, 1, null).addElement(540, 2, null).addElement(540, 5, null).addElement(540, 3, null).addElement(540, 4, null);
        DIRECTIONS_TRAFFIC_SPAN.addElement(277, 1, null).addElement(533, 2, new Long(0));
        CURRENT_MOTION_PROTO.addElement(533, 1, null).addElement(533, 2, null);
        GUIDANCE_EVENT_PROTO.addElement(277, 1, null).addElement(545, 2, null).addElement(533, 3, null).addElement(533, 4, null).addElement(536, 5, null).addElement(540, 6, null).addElement(533, 7, null).addElement(533, 8, null);
        GAIA_RESPONSE_PROTO.addElement(277, 1, null);
        POINT.addElement(277, 1, null).addElement(277, 2, null);
        LOCATION.addElement(539, 1, POINT).addElement(540, 2, null).addElement(540, 3, null).addElement(1052, 4, null).addElement(533, 5, null).addElement(540, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(531, 9, null).addElement(540, 10, null).addElement(540, 11, null);
        PROFILE_PHOTO_DATA.addElement(537, 1, null).addElement(540, 2, null).addElement(533, 3, null).addElement(533, 4, null);
        USER_PHOTO_DATA.addElement(275, 1, null).addElement(283, 2, PROFILE_PHOTO_DATA);
        FRIEND_ENTRY.addElement(275, 1, null).addElement(277, 2, null).addElement(536, 3, null).addElement(536, 4, null).addElement(536, 5, ProtoBuf.FALSE).addElement(536, 6, ProtoBuf.FALSE);
        FRIEND_PROFILE.addElement(283, 1, FRIEND_ENTRY).addElement(284, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(533, 5, null).addElement(533, 6, null).addElement(531, 7, null).addElement(533, 8, null).addElement(1052, 9, null).addElement(540, 10, null).addElement(533, 17, null).addElement(533, 12, null).addElement(536, 21, ProtoBuf.FALSE).addElement(540, 13, null).addElement(531, 14, null).addElement(531, 15, null).addElement(536, 16, ProtoBuf.FALSE).addElement(540, 18, null).addElement(540, 19, null).addElement(540, 20, null);
        ACTIVITY_FRIEND.addElement(531, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(533, 4, null).addElement(531, 5, null).addElement(540, 6, null);
        NETWORK_INITIATED_PREFERENCE.addElement(540, 1, null).addElement(540, 2, null).addElement(531, 3, null);
        LOCATION_REPORT_REASON.addElement(533, 1, null).addElement(531, 2, null).addElement(531, 3, null).addElement(531, 4, null).addElement(540, 5, null).addElement(533, 6, null).addElement(531, 7, null).addElement(531, 8, null).addElement(531, 9, null).addElement(531, 10, null).addElement(533, 11, null).addElement(533, 12, null).addElement(535, 13, null).addElement(535, 14, null).addElement(533, 15, null).addElement(535, 16, null).addElement(535, 17, null).addElement(533, 18, null).addElement(533, 19, null).addElement(540, 20, null).addElement(540, 21, null).addElement(533, 22, null).addElement(533, 23, null).addElement(533, 24, null).addElement(533, 25, null).addElement(540, 26, null);
        USER_LOCATION_DEBUG_INFO.addElement(1051, 1, LOCATION_REPORT_REASON);
        BATTERY_STEP.addElement(277, 1, null).addElement(275, 2, null).addElement(275, 3, null).addElement(1045, 4, null).addElement(1045, 5, null).addElement(531, 6, null).addElement(533, 7, new Long(0));
        BATTERY_STEP_SETTING.addElement(540, 1, null).addElement(533, 2, new Long(0)).addElement(1051, 3, null);
        BATTERY_STEP_SETTINGS.addElement(1051, 1, BATTERY_STEP_SETTING);
        RALLY_POINT.addElement(275, 1, null).addElement(275, 2, null).addElement(1043, 3, null).addElement(531, 4, null);
        COMMENT.addElement(540, 1, null).addElement(540, 2, null).addElement(531, 3, null).addElement(540, 4, null).addElement(540, 5, null).addElement(539, 6, LOCATION).addElement(531, 7, null).addElement(531, 8, null);
        MEDIA.addElement(540, 1, null).addElement(540, 2, null).addElement(533, 3, null).addElement(533, 4, null).addElement(540, 5, null);
        ACTIVITY.addElement(540, 1, null).addElement(540, 2, null).addElement(531, 3, null).addElement(531, 4, null).addElement(540, 5, null).addElement(540, 6, null).addElement(539, 7, LOCATION).addElement(531, 8, null).addElement(531, 9, null).addElement(1051, 10, COMMENT).addElement(533, 11, null).addElement(536, 12, null).addElement(1051, 13, MEDIA).addElement(536, 14, null).addElement(536, 15, null).addElement(540, 16, null).addElement(540, 17, null);
        STREAM.addElement(1051, 1, ACTIVITY);
        PHOTO_UPLOAD.addElement(281, 1, null).addElement(284, 2, null);
        CREATE_ACTIVITY_REQUEST_PAYLOAD.addElement(533, 1, null).addElement(536, 2, null).addElement(531, 3, null).addElement(540, 4, null).addElement(539, 5, LOCATION).addElement(539, 7, PHOTO_UPLOAD).addElement(536, 8, null).addElement(536, 9, null).addElement(536, 10, null);
        CREATE_ACTIVITY_RESPONSE.addElement(539, 1, ACTIVITY);
        CREATE_COMMENT_REQUEST_PAYLOAD.addElement(540, 1, null).addElement(540, 2, null).addElement(539, 3, LOCATION).addElement(536, 4, null);
        CREATE_COMMENT_RESPONSE.addElement(539, 1, COMMENT);
        UPDATE_ACTIVITY_REQUEST_PAYLOAD.addElement(540, 1, null).addElement(533, 2, null);
        GET_ACTIVITY_STREAM_REQUEST_PAYLOAD.addElement(533, 1, new Long(50)).addElement(533, 2, new Long(0)).addElement(531, 3, new Long(-1)).addElement(531, 4, new Long(-1));
        GET_PRODUCTION_STREAM_REQUEST_PAYLOAD.addElement(531, 1, null).addElement(539, 2, GET_ACTIVITY_STREAM_REQUEST_PAYLOAD);
        GET_ACTIVITY_STREAM_RESPONSE.addElement(539, 1, STREAM).addElement(1051, 2, ACTIVITY_FRIEND).addElement(531, 3, null);
        GET_ACTIVITY_REQUEST_PAYLOAD.addElement(540, 1, null).addElement(533, 2, new Long(50)).addElement(531, 3, new Long(-1));
        GET_ACTIVITY_RESPONSE.addElement(539, 1, ACTIVITY).addElement(1051, 2, ACTIVITY_FRIEND);
        NOTIFICATION_CHECK_REQUEST_PAYLOAD.addElement(536, 1, null).addElement(531, 2, null);
        NOTIFICATION_CHECK_RESPONSE.addElement(533, 1, null).addElement(540, 2, null).addElement(531, 3, null);
        ACCEPT_PUBLIC_UPDATE_TERMS_REQUEST_PAYLOAD.addElement(533, 1, null).addElement(536, 2, null).addElement(540, 3, null).addElement(540, 4, null);
        ACCEPT_PUBLIC_UPDATE_TERMS_RESPONSE.addElement(540, 1, null);
        HAS_ACCEPTED_PUBLIC_UPDATE_TERMS_RESPONSE.addElement(536, 1, null).addElement(533, 2, null);
        GET_USER_PROFILE_REQUEST_PAYLOAD.addElement(536, 1, null);
        GET_USER_PROFILE_RESPONSE.addElement(539, 1, ACTIVITY_FRIEND).addElement(539, 2, FRIEND_PROFILE);
        SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PAYLOAD.addElement(540, 1, null).addElement(539, 2, SEARCH_PUBLIC_ACTIVITIES_OPTIONS);
        SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PAYLOAD.addElement(539, 1, POINT).addElement(539, 2, SEARCH_PUBLIC_ACTIVITIES_OPTIONS);
        SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PAYLOAD.addElement(539, 1, POINT).addElement(539, 2, POINT).addElement(539, 3, SEARCH_PUBLIC_ACTIVITIES_OPTIONS);
        SEARCH_PUBLIC_ACTIVITIES_OPTIONS.addElement(540, 1, null).addElement(533, 2, null).addElement(533, 3, null).addElement(533, 4, null).addElement(537, 5, null).addElement(533, 6, null);
        SEARCH_PUBLIC_ACTIVITIES_REQUEST_PAYLOAD.addElement(540, 1, null).addElement(539, 2, POINT).addElement(533, 4, new Long(20)).addElement(533, 5, null).addElement(533, 6, null).addElement(533, 7, null).addElement(537, 8, null);
        SEARCH_PUBLIC_ACTIVITIES_RESPONSE.addElement(539, 1, STREAM).addElement(537, 2, null).addElement(1051, 3, ACTIVITY_FRIEND).addElement(531, 4, null);
        GET_ACTIVITY_REQUEST_PROTO.addElement(539, 1, null);
        GET_ACTIVITY_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        GET_ACTIVITY_STREAM_REQUEST_PROTO.addElement(539, 1, null);
        GET_ACTIVITY_STREAM_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        GET_PRODUCTION_STREAM_REQUEST_PROTO.addElement(539, 1, null);
        GET_PRODUCTION_STREAM_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, null).addElement(539, 3, GAIA_RESPONSE_PROTO);
        CREATE_ACTIVITY_REQUEST_PROTO.addElement(539, 1, null);
        CREATE_ACTIVITY_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        CREATE_COMMENT_REQUEST_PROTO.addElement(539, 1, null);
        CREATE_COMMENT_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        UPDATE_ACTIVITY_REQUEST_PROTO.addElement(539, 1, null);
        UPDATE_ACTIVITY_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        NOTIFICATION_CHECK_REQUEST_PROTO.addElement(539, 1, null);
        GET_USER_PROFILE_REQUEST_PROTO.addElement(539, 1, null);
        GET_USER_PROFILE_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        NOTIFICATION_CHECK_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        SEARCH_PUBLIC_ACTIVITIES_NEARBY_REQUEST_PROTO.addElement(539, 1, null);
        SEARCH_PUBLIC_ACTIVITIES_BY_CIDREQUEST_PROTO.addElement(539, 1, null);
        SEARCH_PUBLIC_ACTIVITIES_VIEWPORT_REQUEST_PROTO.addElement(539, 1, null);
        SEARCH_PUBLIC_ACTIVITIES_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, null).addElement(539, 3, GAIA_RESPONSE_PROTO);
        BUZZ_USER_STATE_PROTO.addElement(536, 1, null).addElement(533, 2, null);
        SET_USER_STATE_REQUEST_PROTO.addElement(539, 1, BUZZ_USER_STATE_PROTO);
        SET_USER_STATE_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        LOCATION_PRIVACY_SETTING_PROTO.addElement(277, 1, null).addElement(536, 2, null).addElement(533, 3, null).addElement(536, 4, ProtoBuf.FALSE).addElement(536, 5, ProtoBuf.FALSE).addElement(536, 6, ProtoBuf.FALSE);
        USER_STATE_PROTO.addElement(283, 1, LOCATION_PRIVACY_SETTING_PROTO).addElement(536, 2, ProtoBuf.FALSE).addElement(536, 3, null).addElement(533, 4, null);
        LOCATION_UPDATE_REQUEST_PROTO.addElement(283, 1, GEOMETRY_PROTO).addElement(533, 2, null).addElement(540, 3, null).addElement(536, 4, ProtoBuf.FALSE).addElement(531, 5, null).addElement(536, 6, null).addElement(533, 7, new Long(-1)).addElement(536, 8, ProtoBuf.FALSE).addElement(539, 9, null).addElement(536, 10, ProtoBuf.FALSE).addElement(531, 11, null).addElement(1051, 12, null);
        GET_USER_STATE_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, USER_STATE_PROTO).addElement(539, 4, BUZZ_USER_STATE_PROTO);
        LOCATION_UPDATE_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, USER_STATE_PROTO).addElement(1051, 6, null).addElement(536, 7, null);
        SET_LOCATION_PRIVACY_SETTING_REQUEST_PROTO.addElement(283, 1, LOCATION_PRIVACY_SETTING_PROTO);
        SET_LOCATION_PRIVACY_SETTING_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO);
        PHOTO_DATA.addElement(537, 1, null).addElement(540, 2, null).addElement(533, 3, null).addElement(533, 4, null);
        USER_PROFILE_UPDATE_REQUEST_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(533, 3, null).addElement(539, 4, PHOTO_DATA).addElement(540, 5, null).addElement(536, 6, null).addElement(536, 7, null).addElement(533, 8, null);
        USER_PROFILE_UPDATE_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO);
        UPDATE_FRIEND_STATE_REQUEST_PROTO.addElement(1043, 1, null).addElement(1052, 2, null).addElement(1052, 3, null).addElement(1043, 4, null).addElement(1043, 5, null).addElement(1043, 6, null).addElement(1043, 7, null).addElement(1043, 8, null).addElement(1052, 9, null);
        UPDATE_FRIEND_STATE_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO);
        GET_FRIEND_FINDER_USERS_REQUEST_PROTO.addElement(277, 1, null);
        GET_FRIEND_FINDER_USERS_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(1050, 3, new ProtoBufType("CONTACT").addElement(275, 4, null).addElement(284, 5, null).addElement(540, 6, null).addElement(280, 12, null));
        INVITE_GROUP_ID_PROTO.addElement(533, 1, null).addElement(531, 2, null);
        GET_INVITE_GROUP_LIST_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(1050, 3, new ProtoBufType("GROUP").addElement(283, 4, INVITE_GROUP_ID_PROTO).addElement(540, 5, null));
        GET_INVITE_CONTACT_LIST_REQUEST_PROTO.addElement(1050, 1, new ProtoBufType("GROUP_SPEC").addElement(283, 2, INVITE_GROUP_ID_PROTO).addElement(533, 3, null));
        GET_INVITE_CONTACT_LIST_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(1050, 3, new ProtoBufType("CONTACT").addElement(531, 4, null).addElement(540, 5, null).addElement(540, 6, null).addElement(277, 7, null).addElement(280, 8, null).addElement(1051, 9, INVITE_GROUP_ID_PROTO));
        GET_SUGGESTED_FRIEND_LIST_REQUEST_PROTO.addElement(533, 1, null);
        GET_SUGGESTED_FRIEND_LIST_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(1050, 3, new ProtoBufType("CONTACT").addElement(531, 4, null).addElement(540, 5, null).addElement(540, 6, null));
        DISMISS_SUGGESTED_FRIEND_REQUEST_PROTO.addElement(1043, 1, null);
        DISMISS_SUGGESTED_FRIEND_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO);
        UPDATE_LOCATION_ACL_REQUEST_PROTO.addElement(1043, 1, null).addElement(1043, 2, null);
        UPDATE_LOCATION_ACL_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO);
        PROFILE_PHOTO_SPEC_PROTO.addElement(275, 1, null).addElement(277, 2, null).addElement(277, 3, null).addElement(531, 4, null);
        PROFILE_PHOTO_REQUEST_PROTO.addElement(1051, 1, PROFILE_PHOTO_SPEC_PROTO);
        PROFILE_PHOTO_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(1050, 3, new ProtoBufType("PROFILE_PHOTO").addElement(537, 4, null));
        SET_NETWORK_INITIATED_PREFERENCE_REQUEST_PROTO.addElement(539, 1, null);
        SET_NETWORK_INITIATED_PREFERENCE_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        GET_FRIENDS_LOCATIONS_REQUEST_PROTO.addElement(1043, 1, null);
        GET_FRIENDS_LOCATIONS_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(1051, 3, null);
        GET_FRIENDS_PROFILES_REQUEST_PROTO.addElement(1043, 1, null);
        GET_FRIENDS_PROFILES_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(1051, 3, null);
        CREATE_RALLY_POINT_REQUEST_PROTO.addElement(1043, 1, null).addElement(531, 2, null);
        CREATE_RALLY_POINT_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(531, 3, null);
        DELETE_RALLY_POINT_REQUEST_PROTO.addElement(531, 1, null);
        DELETE_RALLY_POINT_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        GET_RALLY_POINT_REQUEST_PROTO.addElement(531, 1, null);
        GET_RALLY_POINT_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null);
        GET_RALLY_POINTS_FOR_USER_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(1051, 3, null);
        STRUCTURED_ADDRESS_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(540, 5, null).addElement(540, 6, null).addElement(540, 7, null);
        EMAIL_OPTIONS.addElement(536, 1, null).addElement(540, 2, null);
        FEATURE_RANGE.addElement(540, 1, null).addElement(540, 2, null);
        MAP_SHOP_RAW_REQUESTS.addElement(1050, 1, new ProtoBufType("REQUEST").addElement(533, 2, new Long(-1)).addElement(540, 3, null).addElement(1050, 19, new ProtoBufType("REQUEST_FEATURED_MAPS").addElement(284, 20, null)).addElement(540, 4, null).addElement(1043, 22, null).addElement(1045, 23, null).addElement(533, 5, new Long(-1)).addElement(1050, 12, new ProtoBufType("REQUEST_EDIT_INFO").addElement(277, 6, null).addElement(533, 7, new Long(-1)).addElement(540, 8, null).addElement(540, 21, null)).addElement(533, 9, null).addElement(533, 10, null).addElement(533, 11, null).addElement(540, 14, null).addElement(540, 13, null).addElement(540, 26, null).addElement(536, 15, null).addElement(540, 17, null).addElement(531, 18, null).addElement(540, 16, null).addElement(540, 25, null).addElement(540, 27, null).addElement(536, 30, null).addElement(536, 28, null).addElement(539, 29, EMAIL_OPTIONS).addElement(1051, 31, FEATURE_RANGE).addElement(540, 32, null).addElement(538, 34, new ProtoBufType("REQUEST_MLOG").addElement(277, 35, null).addElement(540, 36, null).addElement(531, 37, null))).addElement(540, 33, null);
        REAL_ESTATE_QUERY_REFINEMENT.addElement(533, 1, null).addElement(533, 2, null).addElement(1045, 3, null).addElement(1045, 4, null).addElement(1045, 5, null).addElement(533, 6, null).addElement(533, 7, null).addElement(1045, 8, null).addElement(1045, 9, null);
        HOTPOT_UPDATE.addElement(278, 1, null).addElement(533, 2, null).addElement(533, 3, null);
        HOTPOT_UPDATE_PARAM.addElement(1051, 1, HOTPOT_UPDATE);
        RECOMMENDATION_REQUEST_PROTO.addElement(533, 1, null).addElement(539, 2, HOTPOT_UPDATE_PARAM);
        SEED_PLACE.addElement(278, 1, null);
        JUSTIFICATION.addElement(277, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(531, 4, null).addElement(540, 5, null).addElement(533, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(540, 9, null);
        RECOMMENDATION_REASON_PROTO.addElement(1051, 1, SEED_PLACE).addElement(1051, 2, JUSTIFICATION);
        REVIEW.addElement(533, 1, null).addElement(540, 2, null).addElement(1051, 3, FEEDBACK_PROTO).addElement(540, 4, null);
        FEEDBACK_PROTO.addElement(277, 1, null).addElement(284, 2, null).addElement(540, 3, null).addElement(533, 4, new Long(0));
        SUBMIT_REVIEW_REQUEST_PROTO.addElement(532, 1, null).addElement(539, 2, REVIEW).addElement(540, 3, null).addElement(540, 4, null).addElement(540, 5, null).addElement(539, 6, MAP_POINT_PROTO);
        SUBMIT_REVIEW_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        TRANSIT_STATION_INFO_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(539, 3, EFFICIENT_MAP_POINT_PROTO);
        TRANSIT_STATION_RESULT_PROTO.addElement(539, 1, TRANSIT_STATION_INFO_PROTO).addElement(1051, 4, TRANSIT_LINE_WITH_DEPARTURES_AT_STATION_PROTO);
        TRANSIT_LINE_INFO_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(539, 3, TRANSIT_LINE_DISPLAY_PROPERTIES_PROTO).addElement(540, 4, null).addElement(540, 5, null).addElement(540, 6, null);
        TRANSIT_LINE_WITH_DEPARTURES_AT_STATION_PROTO.addElement(539, 1, TRANSIT_LINE_INFO_PROTO).addElement(1051, 2, TRIP_GROUP_AND_DEPARTURES_PROTO);
        TRANSIT_LINE_RESULT_PROTO.addElement(539, 1, TRANSIT_LINE_INFO_PROTO).addElement(1051, 2, TRANSIT_STATION_INFO_PROTO);
        DEPARTURE_PROTO.addElement(539, 1, DATE_TIME_PROTO);
        TRIP_GROUP_AND_DEPARTURES_PROTO.addElement(540, 1, null).addElement(1051, 2, DEPARTURE_PROTO);
        TRANSIT_LINE_DISPLAY_PROPERTIES_PROTO.addElement(541, 1, null).addElement(541, 2, null);
        SEARCH_REQUEST_PROTO.addElement(277, 1, null).addElement(284, 2, null).addElement(539, 3, MAP_INFO_PROTO).addElement(533, 4, new Long(0)).addElement(533, 5, new Long(9)).addElement(536, 6, ProtoBuf.TRUE).addElement(536, 7, ProtoBuf.FALSE).addElement(536, 8, ProtoBuf.FALSE).addElement(537, 9, null).addElement(540, 10, null).addElement(539, 11, null).addElement(539, 12, CLIENT_CAPABILITIES_PROTO).addElement(536, 13, ProtoBuf.FALSE).addElement(536, 14, ProtoBuf.FALSE).addElement(536, 15, ProtoBuf.FALSE).addElement(533, 16, null).addElement(536, 17, ProtoBuf.FALSE).addElement(536, 18, ProtoBuf.FALSE).addElement(536, 19, ProtoBuf.FALSE).addElement(536, 20, ProtoBuf.TRUE).addElement(536, 24, ProtoBuf.TRUE).addElement(533, 21, new Long(0)).addElement(533, 22, new Long(128)).addElement(536, 23, ProtoBuf.TRUE).addElement(536, 25, ProtoBuf.FALSE).addElement(536, 26, ProtoBuf.FALSE).addElement(1051, 27, GEOMETRY_PROTO).addElement(539, 28, IMPLICIT_LOCATION_PROTO).addElement(536, 29, null).addElement(536, 30, ProtoBuf.FALSE).addElement(536, 31, ProtoBuf.FALSE).addElement(536, 32, ProtoBuf.FALSE).addElement(536, 33, ProtoBuf.FALSE).addElement(539, 34, REAL_ESTATE_QUERY_REFINEMENT).addElement(539, 35, RECOMMENDATION_REQUEST_PROTO).addElement(536, 36, ProtoBuf.FALSE);
        SEARCH_RESPONSE_PROTO.addElement(277, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(536, 5, ProtoBuf.FALSE).addElement(540, 6, null).addElement(539, 7, MAP_INFO_PROTO).addElement(1051, 8, SEARCH_RESULT_PROTO).addElement(1051, 9, DOCUMENT_INFO_PROTO).addElement(1052, 10, null).addElement(533, 11, new Long(0)).addElement(533, 12, new Long(0)).addElement(533, 13, new Long(-1)).addElement(540, 14, null).addElement(540, 15, null);
        DOCUMENT_INFO_PROTO.addElement(1052, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(540, 5, null).addElement(540, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(533, 9, null);
        IMAGE_PROTO.addElement(540, 1, null).addElement(277, 2, null).addElement(537, 3, null);
        RATING_PROTO.addElement(533, 1, null).addElement(533, 4, null).addElement(1045, 5, null).addElement(540, 6, null);
        SET_HTTP_COOKIE_REQUEST_PROTO.addElement(536, 1, ProtoBuf.TRUE).addElement(280, 2, null).addElement(280, 3, null);
        PHOTO_PROTO.addElement(540, 1, null).addElement(540, 2, null);
        COUPON_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(1052, 3, null).addElement(539, 4, DATE_TIME_PROTO).addElement(539, 5, DATE_TIME_PROTO);
        DETAIL_ITEM.addElement(284, 1, null).addElement(284, 2, null).addElement(540, 3, null).addElement(540, 4, null);
        SNIPPET_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(540, 3, null);
        MORE_DETAILS_PROTO.addElement(1051, 1, PHOTO_PROTO).addElement(540, 2, null).addElement(1051, 3, COUPON_PROTO).addElement(1051, 4, DETAIL_ITEM).addElement(1051, 5, SNIPPET_PROTO).addElement(539, 6, TRANSIT_STATION_RESULT_PROTO);
        SEARCH_RESULT_PROTO.addElement(277, 1, null).addElement(540, 2, null).addElement(539, 3, GEOMETRY_PROTO).addElement(1052, 4, null).addElement(540, 11, null).addElement(1050, 12, new ProtoBufType("ENHANCED_CONTENT").addElement(284, 13, null).addElement(1052, 14, null).addElement(1052, 15, null).addElement(284, 16, null)).addElement(1050, 18, new ProtoBufType("REFERENCE").addElement(284, 19, null).addElement(284, 20, null).addElement(284, 21, null)).addElement(536, 22, ProtoBuf.TRUE).addElement(540, 23, null).addElement(540, 24, null).addElement(538, 90, new ProtoBufType("KML_INFO").addElement(1052, 91, null).addElement(540, 92, null).addElement(540, 93, null).addElement(539, 94, DOCUMENT_INFO_PROTO).addElement(540, 95, null).addElement(536, 96, ProtoBuf.TRUE)).addElement(1051, 100, IMAGE_PROTO).addElement(539, 101, STRUCTURED_ADDRESS_PROTO).addElement(540, 102, null).addElement(538, 110, new ProtoBufType("FRIEND_PROFILE_INFO").addElement(275, 111, null).addElement(284, 112, null).addElement(540, 113, null).addElement(533, 135, null).addElement(531, 121, null).addElement(533, 122, null).addElement(533, 125, null).addElement(540, 127, null).addElement(277, 128, null).addElement(280, 129, null).addElement(531, 130, null).addElement(531, 131, new Long(2400000)).addElement(536, 132, ProtoBuf.FALSE).addElement(536, 133, ProtoBuf.FALSE).addElement(536, 134, ProtoBuf.FALSE).addElement(540, 136, null)).addElement(538, 70, new ProtoBufType("AD_INFO").addElement(284, 71, null).addElement(540, 140, null).addElement(540, 72, null).addElement(540, 73, null).addElement(540, 115, null).addElement(540, 116, null).addElement(540, 155, null)).addElement(540, 117, null).addElement(539, 118, RATING_PROTO).addElement(534, 119, null).addElement(533, 120, null).addElement(536, 123, ProtoBuf.FALSE).addElement(540, 124, null).addElement(536, 126, ProtoBuf.FALSE).addElement(536, 149, ProtoBuf.FALSE).addElement(536, 152, ProtoBuf.TRUE).addElement(536, 137, ProtoBuf.FALSE).addElement(536, 138, ProtoBuf.FALSE).addElement(540, 139, null).addElement(538, 141, new ProtoBufType("GEOCODE_INFO").addElement(540, 142, null).addElement(533, 143, null).addElement(1051, 146, SEARCH_RESULT_PROTO).addElement(533, 147, new Long(0))).addElement(540, 144, null).addElement(539, 145, null).addElement(540, 148, null).addElement(540, 150, null).addElement(539, 151, MORE_DETAILS_PROTO).addElement(539, 153, REVIEW).addElement(539, 154, RECOMMENDATION_REASON_PROTO);
        BUZZ_LAYER_SNIPPET.addElement(540, 1, null).addElement(538, 2, new ProtoBufType("AUTHOR").addElement(531, 3, null).addElement(540, 4, null)).addElement(531, 5, null).addElement(533, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(536, 9, null).addElement(1052, 10, null);
        LAYER_INFO_PROTO.addElement(284, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(533, 4, new Long(1)).addElement(533, 5, new Long(2)).addElement(538, 6, new ProtoBufType("DISPLAY_FILTER").addElement(533, 61, new Long(0)).addElement(533, 62, new Long(21)).addElement(540, 63, "").addElement(539, 65, MAP_INFO_PROTO)).addElement(531, 8, null).addElement(531, 9, null).addElement(540, 13, null).addElement(540, 14, null).addElement(533, 15, null).addElement(536, 16, ProtoBuf.FALSE).addElement(1049, 17, null).addElement(1051, 18, LAYER_PARAMETER_PROTO).addElement(536, 19, ProtoBuf.FALSE).addElement(536, 20, ProtoBuf.FALSE).addElement(533, 21, new Long(0)).addElement(540, 22, null);
        LAYER_PARAMETER_PROTO.addElement(284, 1, null).addElement(284, 2, null);
        LAYER_ITEM_SNIPPET_PROTO.addElement(284, 1, null).addElement(284, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(536, 5, ProtoBuf.TRUE).addElement(539, 6, RATING_PROTO).addElement(533, 7, null).addElement(541, 8, new Long(0)).addElement(539, 9, BUZZ_LAYER_SNIPPET);
        LAYER_ITEM_DETAIL_PROTO.addElement(284, 1, null).addElement(284, 2, null).addElement(539, 3, SEARCH_RESULT_PROTO).addElement(540, 4, null).addElement(531, 5, null);
        CLICKABLE_AREA_PROTO.addElement(277, 1, null).addElement(1051, 2, LAYER_ITEM_SNIPPET_PROTO).addElement(538, 3, new ProtoBufType("CLICKABLE_ICON").addElement(539, 31, PIXEL_POINT_PROTO).addElement(533, 32, null).addElement(533, 33, null).addElement(533, 34, null).addElement(533, 35, null).addElement(533, 36, null)).addElement(538, 4, new ProtoBufType("CLICKABLE_POLYLINE")).addElement(538, 5, new ProtoBufType("CLICKABLE_POLYGON"));
        LAYER_TILE_INFO_PROTO.addElement(283, 1, MAP_TILE_PROTO).addElement(537, 2, null).addElement(1051, 3, CLICKABLE_AREA_PROTO);
        LAYER_TILE_RESPONSE_HEADER_PROTO.addElement(1050, 1, new ProtoBufType("LAYERS_RESPONSE").addElement(284, 11, null).addElement(1051, 12, CLICKABLE_AREA_PROTO).addElement(1051, 13, LAYER_PARAMETER_PROTO));
        LAYER_LIST_REQUEST_PROTO.addElement(539, 1, MAP_INFO_PROTO);
        LAYER_LIST_RESPONSE_PROTO.addElement(1051, 1, LAYER_INFO_PROTO);
        LAYER_TILE_REQUEST_PROTO.addElement(533, 1, new Long(128)).addElement(1050, 2, new ProtoBufType("LAYERS_REQUEST").addElement(284, 21, null).addElement(1051, 22, LAYER_PARAMETER_PROTO)).addElement(1051, 3, MAP_TILE_PROTO).addElement(539, 4, CLIENT_CAPABILITIES_PROTO);
        LAYER_TILE_RESPONSE_PROTO.addElement(283, 1, LAYER_TILE_RESPONSE_HEADER_PROTO).addElement(1051, 2, LAYER_TILE_INFO_PROTO);
        LAYER_ITEM_REQUEST_PROTO.addElement(284, 1, null).addElement(284, 2, null).addElement(539, 3, CLIENT_CAPABILITIES_PROTO).addElement(536, 4, ProtoBuf.FALSE);
        LAYER_ITEM_RESPONSE_PROTO.addElement(539, 1, LAYER_ITEM_DETAIL_PROTO);
        LAYER_CATEGORY_REQUEST_PROTO.addElement(540, 1, "").addElement(533, 2, new Long(0)).addElement(540, 3, null).addElement(539, 4, MAP_INFO_PROTO).addElement(1045, 5, null).addElement(536, 6, ProtoBuf.FALSE).addElement(534, 7, null);
        LAYER_CATEGORY_RESPONSE_PROTO.addElement(277, 1, null).addElement(533, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(1051, 5, CATEGORY_TREE_INNER_NODE_PROTO).addElement(1051, 6, CATEGORY_INFO_PROTO).addElement(1051, 7, LAYER_INFO_PROTO).addElement(1050, 8, new ProtoBufType("CATEGORY_ICON").addElement(277, 9, null).addElement(281, 10, null).addElement(537, 11, null)).addElement(534, 12, null);
        SEARCH_RESPONSE_WITH_PAYLOAD_PROTO.addElement(283, 1, SEARCH_RESPONSE_PROTO).addElement(539, 2, LAYER_INFO_PROTO).addElement(539, 3, AD_LAYER).addElement(539, 4, DIRECTIONS_RESPONSE_PROTO);
        AD_LAYER.addElement(533, 1, new Long(20)).addElement(540, 2, null).addElement(539, 3, LAYER_INFO_PROTO);
        CLIENT_SAVED_SEARCH_PROTO.addElement(539, 1, SEARCH_RESPONSE_WITH_PAYLOAD_PROTO).addElement(539, 2, MAP_INFO_PROTO).addElement(533, 3, null).addElement(540, 4, null);
        CLIENT_SAVED_DIRECTIONS_PROTO.addElement(540, 1, null).addElement(539, 2, DIRECTIONS_RESPONSE_PROTO).addElement(1051, 3, CLIENT_WAYPOINT_INFO_PROTO).addElement(533, 4, new Long(0)).addElement(533, 5, null).addElement(536, 6, ProtoBuf.TRUE).addElement(536, 7, ProtoBuf.FALSE);
        CLIENT_WAYPOINT_INFO_PROTO.addElement(533, 1, new Long(0)).addElement(540, 2, null).addElement(539, 3, SEARCH_RESULT_PROTO);
        CLIENT_SAVED_OPTION_PROTO.addElement(539, 1, DIRECTIONS_OPTION_RESPONSE_PROTO).addElement(536, 2, ProtoBuf.FALSE);
        CLIENT_WAYPOINT_HISTORY_PROTO.addElement(1050, 1, new ProtoBufType("WAYPOINT").addElement(539, 2, LOCATION_PROTO).addElement(539, 3, CLIENT_WAYPOINT_INFO_PROTO));
        CLIENT_SAVED_FRIENDS_PROTO.addElement(539, 1, LOCATION_PRIVACY_SETTING_PROTO).addElement(539, 2, SEARCH_RESPONSE_PROTO).addElement(1050, 5, new ProtoBufType("PROFILE_PHOTO_RESPONSE_GAIA_IDS").addElement(531, 6, null).addElement(537, 7, null).addElement(537, 8, null).addElement(540, 9, null)).addElement(1051, 10, null).addElement(531, 11, null).addElement(539, 12, MAP_POINT_PROTO).addElement(533, 13, null).addElement(533, 14, null);
        CLIENT_SAVED_FRIEND_PHOTOS_PROTO.addElement(1050, 1, new ProtoBufType("PROFILE_PHOTO").addElement(275, 2, null).addElement(537, 3, null).addElement(537, 4, null).addElement(540, 5, null));
        SECURITY_POPUP_SETTINGS.addElement(533, 1, null).addElement(536, 2, null).addElement(531, 3, null).addElement(531, 4, null);
        CLIENT_SAVED_FRIENDS_MINIMAL_SETTINGS_PROTO.addElement(539, 1, SECURITY_POPUP_SETTINGS).addElement(539, 2, LOCATION_PRIVACY_SETTING_PROTO).addElement(1051, 3, null).addElement(531, 4, null).addElement(539, 5, MAP_POINT_PROTO).addElement(533, 6, null);
        CLIENT_SAVED_GAIA_ACCOUNT_STATE_PROTO.addElement(540, 1, null).addElement(541, 2, new Long(0));
        CLIENT_SAVED_ACTIVITY_FULL_PREFS_PROTO.addElement(539, 1, BUZZ_USER_STATE_PROTO).addElement(539, 2, null);
        CLIENT_LAYER_MANAGER_STATE_PROTO.addElement(1050, 1, new ProtoBufType("LAYER_STATE").addElement(277, 2, null).addElement(281, 3, null).addElement(536, 4, null).addElement(536, 5, null).addElement(533, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(536, 9, null)).addElement(533, 10, null).addElement(533, 11, null).addElement(536, 12, ProtoBuf.TRUE).addElement(536, 13, ProtoBuf.FALSE);
        CLIENT_WIZARD_MANAGER_STATE_PROTO.addElement(536, 1, null);
        CLIENT_POST_UPDATE_WIZARD_STATE_PROTO.addElement(536, 1, null).addElement(539, 2, MAP_POINT_PROTO).addElement(1052, 3, null).addElement(540, 4, null);
        CLIENT_CATEGORY_HISTORY_PROTO.addElement(1051, 1, CATEGORY_INFO_PROTO);
        SEARCH_DIALOG_PREFERENCES_PROTO.addElement(280, 1, ProtoBuf.FALSE);
        CLIENT_SAVED_PHOTO_CACHE_INDEX.addElement(1051, 1, PHOTO_ID);
        PHOTO_ID.addElement(540, 1, null).addElement(531, 2, null).addElement(531, 3, null);
        PROFILE_PHOTO.addElement(539, 1, PHOTO_ID).addElement(1050, 2, new ProtoBufType("PROFILE_PHOTO_PHOTO").addElement(537, 3, null));
        CLIENT_LATITUDE_WIDGET_MODEL_PROTO.addElement(539, 1, SEARCH_RESULT_PROTO).addElement(1051, 2, SEARCH_RESULT_PROTO).addElement(1049, 3, null).addElement(531, 4, null);
        CLIENT_REQUIREMENTS_PROTO.addElement(540, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(533, 4, null);
        CLIENT_FEATURE_PROTO.addElement(533, 1, null).addElement(541, 2, null).addElement(539, 3, FEATURE_RESTRICTIONS_PROTO).addElement(539, 4, CLIENT_REQUIREMENTS_PROTO);
        FEATURE_RESTRICTIONS_PROTO.addElement(537, 1, null);
        FEATURE_RESTRICTIONS_REQUEST_PROTO.addElement(1051, 1, CLIENT_FEATURE_PROTO).addElement(533, 2, null);
        FEATURE_RESTRICTIONS_RESPONSE_PROTO.addElement(1051, 1, CLIENT_FEATURE_PROTO);
        JOIN_EXPERIMENTS_REQUEST_PROTO.addElement(1045, 1, null);
        JOIN_EXPERIMENTS_RESPONSE_PROTO.addElement(1045, 1, null);
        QUERY_PARAMETERS.addElement(539, 1, MAP_INFO_PROTO).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null);
        LAYER_EVENT_REPORT_REQUEST_PROTO.addElement(533, 1, null).addElement(539, 2, DATE_TIME_PROTO).addElement(540, 3, null).addElement(536, 4, ProtoBuf.FALSE).addElement(540, 5, null).addElement(540, 6, null).addElement(539, 7, QUERY_PARAMETERS).addElement(533, 8, null);
        LOCAL_DETAILS_REQUEST_PROTO.addElement(283, 1, MAP_POINT_PROTO).addElement(278, 2, null).addElement(538, 3, new ProtoBufType("REQUEST_REVIEWS").addElement(533, 4, null).addElement(533, 5, null));
        LOCAL_DETAILS_RESPONSE_PROTO.addElement(539, 1, REVIEWS_PROTO).addElement(540, 2, null);
        REVIEWS_PROTO.addElement(533, 1, null).addElement(533, 2, null).addElement(1051, 3, REVIEW_PROTO).addElement(533, 4, null);
        REVIEW_PROTO.addElement(533, 4, null).addElement(533, 5, null).addElement(540, 6, null).addElement(540, 7, null).addElement(540, 8, null).addElement(540, 9, null).addElement(539, 10, DATE_TIME_PROTO).addElement(540, 11, null).addElement(540, 12, null).addElement(540, 13, null).addElement(540, 14, null);
        LOCATION_SHIFT_REQUEST_PROTO.addElement(283, 2, MAP_POINT_PROTO);
        LOCATION_SHIFT_RESPONSE_PROTO.addElement(277, 1, null).addElement(1043, 2, null).addElement(539, 3, MAP_POINT_PROTO).addElement(533, 4, null).addElement(533, 5, null);
        NOTIFICATION_RESPONSE.addElement(277, 1, null).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(533, 5, new Long(0)).addElement(540, 6, null);
        NOTIFICATIONS_REQUEST_PROTO.addElement(533, 1, new Long(0)).addElement(536, 2, ProtoBuf.FALSE);
        NOTIFICATIONS_RESPONSE_PROTO.addElement(1050, 1, new ProtoBufType("NOTICE").addElement(284, 2, null).addElement(540, 3, null).addElement(536, 4, ProtoBuf.FALSE)).addElement(539, 5, null);
        RESOURCE_REQUEST_PROTO.addElement(534, 2, null).addElement(284, 4, null).addElement(539, 8, CLIENT_CAPABILITIES_PROTO);
        RESOURCE_RESPONSE_PROTO.addElement(1050, 1, new ProtoBufType("RESPONSE").addElement(284, 2, null).addElement(277, 3, null).addElement(278, 4, null).addElement(537, 6, null).addElement(284, 7, null));
        REVERSE_GEOCODE_RESULT_TYPE_ENUM.addElement(277, 1, null);
        REVERSE_GEOCODE_RESULT_PROTO.addElement(283, 1, REVERSE_GEOCODE_RESULT_TYPE_ENUM).addElement(1052, 2, null).addElement(539, 3, STRUCTURED_ADDRESS_PROTO);
        REVERSE_GEOCODE_REQUEST_PROTO.addElement(283, 1, GEOMETRY_PROTO).addElement(533, 2, new Long(1)).addElement(539, 3, MAP_INFO_PROTO).addElement(536, 4, ProtoBuf.TRUE);
        REVERSE_GEOCODE_RESPONSE_PROTO.addElement(277, 1, null).addElement(1051, 2, REVERSE_GEOCODE_RESULT_PROTO).addElement(540, 3, null);
        REPORT_MAP_ISSUE_REQUEST_PROTO.addElement(533, 1, null).addElement(540, 2, null).addElement(536, 3, null).addElement(539, 4, GEOMETRY_PROTO).addElement(539, 5, MAP_INFO_PROTO).addElement(539, 6, DIRECTIONS_STEP_INFO).addElement(537, 7, null).addElement(533, 8, new Long(0)).addElement(537, 9, null).addElement(540, 10, null);
        DIRECTIONS_STEP_INFO.addElement(533, 1, null).addElement(540, 2, null).addElement(533, 3, null).addElement(540, 4, null);
        REPORT_MAP_ISSUE_RESPONSE_PROTO.addElement(533, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        SESAME_REQUEST_PROTO.addElement(533, 1, new Long(0)).addElement(534, 2, null).addElement(540, 3, null).addElement(533, 4, null).addElement(540, 5, null).addElement(533, 6, null);
        SESAME_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO);
        SHARE_WITH_FRIEND_REQUEST_PROTO.addElement(533, 1, new Long(0)).addElement(533, 2, new Long(0)).addElement(540, 3, null).addElement(1052, 4, null).addElement(540, 5, null).addElement(540, 6, null).addElement(539, 7, EFFICIENT_MAP_POINT_PROTO).addElement(539, 8, MAP_INFO_PROTO);
        SHARE_WITH_FRIEND_RESPONSE_PROTO.addElement(533, 1, new Long(0)).addElement(540, 2, null).addElement(540, 3, null).addElement(540, 4, null);
        SNAP_TO_PLACE_REQUEST_PROTO.addElement(283, 1, null).addElement(277, 2, null).addElement(277, 3, null).addElement(540, 4, null).addElement(277, 5, new Long(10));
        SNAP_TO_PLACE_RESPONSE_PROTO.addElement(277, 1, null).addElement(283, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, null).addElement(1051, 4, null);
        SPEECH_REQUEST_PROTO.addElement(284, 1, null).addElement(1051, 2, null);
        BATCH_SPEECH_REQUEST_PROTO.addElement(540, 2, null).addElement(533, 3, new Long(1)).addElement(1051, 4, SPEECH_REQUEST_PROTO);
        SPEECH_RESPONSE_PROTO.addElement(281, 1, null);
        BATCH_SPEECH_RESPONSE_PROTO.addElement(277, 1, null).addElement(1051, 2, SPEECH_RESPONSE_PROTO);
        STAR_PROTO.addElement(284, 1, null).addElement(536, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(539, 5, GEOMETRY_PROTO).addElement(539, 6, SEARCH_RESULT_PROTO);
        STREET_VIEW_METADATA_PROTO.addElement(282, 1, new ProtoBufType("DATA_PROPERTIES").addElement(536, 2, ProtoBuf.FALSE).addElement(533, 3, new Long(0)).addElement(533, 17, new Long(2000)).addElement(277, 4, null).addElement(277, 5, null).addElement(533, 6, new Long(512)).addElement(533, 7, new Long(512)).addElement(284, 8, null).addElement(533, 9, new Long(4)).addElement(283, 10, MAP_POINT_PROTO).addElement(540, 11, "").addElement(540, 12, "").addElement(540, 13, "").addElement(277, 14, null).addElement(277, 15, null).addElement(533, 16, new Long(1))).addElement(282, 33, new ProtoBufType("PROJECTION_PROPERTIES").addElement(533, 34, new Long(0)).addElement(533, 35, new Long(0)).addElement(533, 36, new Long(0)).addElement(533, 37, new Long(0)).addElement(533, 38, new Long(3)).addElement(533, 39, new Long(80000000)).addElement(533, 40, new Long(-90000000)).addElement(533, 41, new Long(90000000))).addElement(282, 49, new ProtoBufType("ANNOTATION_PROPERTIES").addElement(533, 50, new Long(450000)).addElement(533, 51, new Long(500000)).addElement(1050, 52, new ProtoBufType("ANNOTATION_PROPERTIES_LINK").addElement(533, 53, new Long(0)).addElement(284, 54, null).addElement(533, 55, new Long(-2130839438)).addElement(540, 56, "").addElement(540, 57, ""))).addElement(538, 58, new ProtoBufType("MODEL").addElement(537, 59, null).addElement(537, 60, null));
        STREET_VIEW_REQUEST_PROTO.addElement(540, 1, null).addElement(539, 2, MAP_POINT_PROTO).addElement(533, 52, new Long(-1)).addElement(538, 17, new ProtoBufType("METADATA").addElement(536, 18, ProtoBuf.FALSE).addElement(536, 56, ProtoBuf.FALSE).addElement(536, 57, ProtoBuf.FALSE)).addElement(538, 33, new ProtoBufType("TILES").addElement(283, 34, CLIENT_CAPABILITIES_PROTO).addElement(277, 35, null).addElement(277, 36, null).addElement(1050, 37, new ProtoBufType("TILES_INDEX").addElement(277, 39, null).addElement(277, 40, null))).addElement(538, 53, new ProtoBufType("THUMBNAIL").addElement(277, 54, null).addElement(277, 55, null)).addElement(536, 49, null).addElement(536, 50, ProtoBuf.FALSE).addElement(536, 51, ProtoBuf.FALSE);
        STREET_VIEW_RESPONSE_PROTO.addElement(540, 2, null).addElement(539, 3, STREET_VIEW_METADATA_PROTO).addElement(538, 17, new ProtoBufType("TILES").addElement(277, 19, null).addElement(277, 20, null).addElement(277, 21, null).addElement(1050, 22, new ProtoBufType("TILES_TILE").addElement(277, 23, null).addElement(277, 24, null).addElement(281, 25, null))).addElement(538, 35, new ProtoBufType("THUMBNAIL").addElement(277, 36, null).addElement(277, 37, null).addElement(281, 38, null)).addElement(538, 68, new ProtoBufType("NAVIGATION_IMAGE").addElement(277, 69, null).addElement(277, 70, null).addElement(281, 71, null)).addElement(540, 33, null).addElement(536, 34, ProtoBuf.FALSE);
        STREET_VIEW_TAKE_DOWN_REQUEST_PROTO.addElement(283, 1, CAPTCHA_REQUEST_PROTO).addElement(538, 2, new ProtoBufType("REQUEST_BODY").addElement(284, 3, null).addElement(283, 4, MAP_POINT_PROTO).addElement(277, 5, null).addElement(284, 6, null).addElement(284, 7, null).addElement(284, 8, null).addElement(533, 9, new Long(0)).addElement(533, 10, new Long(0)));
        STREET_VIEW_TAKE_DOWN_RESPONSE_PROTO.addElement(536, 1, ProtoBuf.FALSE).addElement(539, 2, CAPTCHA_RESPONSE_PROTO).addElement(538, 3, new ProtoBufType("RESPONSE_BODY").addElement(277, 4, null));
        STREET_VIEW_REPORT_PROTO.addElement(1050, 1, new ProtoBufType("PANORAMA_VISITED").addElement(284, 2, null).addElement(283, 3, MAP_POINT_PROTO));
        SUGGESTION_PROTO.addElement(284, 1, null).addElement(540, 2, null).addElement(533, 3, new Long(0)).addElement(536, 4, ProtoBuf.FALSE).addElement(533, 5, null).addElement(533, 6, null);
        SUGGESTION_GROUP_PROTO.addElement(540, 1, null).addElement(1051, 2, SUGGESTION_PROTO).addElement(540, 3, "");
        SUGGEST_REQUEST_PROTO.addElement(284, 1, null).addElement(539, 2, MAP_INFO_PROTO).addElement(539, 3, EFFICIENT_MAP_POINT_PROTO).addElement(533, 4, null);
        SUGGEST_RESPONSE_PROTO.addElement(284, 1, null).addElement(1051, 2, SUGGESTION_GROUP_PROTO).addElement(539, 3, GAIA_RESPONSE_PROTO);
        TRAFFIC_VECTOR_TILE_PROTO.addElement(1051, 1, ROADWAY_PROTO);
        ROADWAY_PROTO.addElement(1051, 1, ROAD_POINT_PROTO).addElement(533, 2, null).addElement(533, 3, null);
        ROAD_POINT_PROTO.addElement(289, 1, null).addElement(289, 2, null).addElement(277, 3, null);
        URL_REQUEST_PROTO.addElement(284, 1, null);
        URL_RESPONSE_PROTO.addElement(539, 1, SEARCH_RESPONSE_PROTO);
        USER_CONTENT_REQUEST_PROTO.addElement(533, 1, new Long(0));
        USER_CONTENT_RESPONSE_PROTO.addElement(277, 1, null).addElement(539, 2, GAIA_RESPONSE_PROTO).addElement(539, 3, USER_CONTENT_RESPONSE_META).addElement(1051, 4, USER_MAP_LISTING_PROTO);
        USER_MAP_LISTING_PROTO.addElement(284, 1, null).addElement(284, 2, null).addElement(540, 3, null).addElement(531, 4, null).addElement(531, 5, null).addElement(540, 7, null).addElement(533, 8, new Long(0)).addElement(536, 9, ProtoBuf.FALSE);
        STAR_DETAILS_PROTO.addElement(284, 1, null).addElement(533, 2, null).addElement(539, 3, STAR_RESULT_PROTO);
        STAR_RESULT_PROTO.addElement(539, 1, SEARCH_RESULT_PROTO);
        STAR_WITH_DETAILS_PROTO.addElement(283, 1, STAR_PROTO).addElement(283, 2, STAR_DETAILS_PROTO);
        STAR_DETAILS_STORAGE_PROTO.addElement(1051, 1, STAR_DETAILS_PROTO);
        STAR_MRUITEM.addElement(284, 1, null);
        STARRING_PREFS_PROTO.addElement(283, 1, STAR_DETAILS_STORAGE_PROTO).addElement(280, 2, ProtoBuf.TRUE).addElement(1051, 3, STAR_MRUITEM);
        SYNC_ITEM.addElement(539, 1, STAR_PROTO).addElement(539, 3, MAPS_ADDRESS_BOOK_ENTRY_PROTO).addElement(284, 2, null);
        SYNC_ITEM_UPDATE_REQUEST.addElement(540, 1, null).addElement(535, 2, null).addElement(283, 3, SYNC_ITEM);
        SYNC_ITEM_UPDATE_RESPONSE.addElement(284, 1, null).addElement(539, 2, SYNC_ERROR_PROTO);
        SYNC_OPERATION.addElement(539, 1, SYNC_ITEM_UPDATE_RESPONSE).addElement(539, 2, SYNC_ITEM);
        SYNC_CORPUS_REQUEST_PROTO.addElement(277, 1, null).addElement(532, 2, null).addElement(1051, 3, SYNC_ITEM_UPDATE_REQUEST);
        SYNC_REQUEST_PROTO.addElement(1051, 1, SYNC_CORPUS_REQUEST_PROTO).addElement(536, 2, null);
        SYNC_CORPUS_RESPONSE_PROTO.addElement(277, 1, null).addElement(532, 2, null).addElement(536, 3, ProtoBuf.FALSE).addElement(1051, 4, SYNC_OPERATION).addElement(539, 5, SYNC_ERROR_PROTO).addElement(536, 6, null);
        SYNC_RESPONSE_PROTO.addElement(1051, 1, SYNC_CORPUS_RESPONSE_PROTO).addElement(539, 2, GAIA_RESPONSE_PROTO);
        SYNC_ERROR_PROTO.addElement(277, 1, null).addElement(540, 2, null).addElement(539, 3, GAIA_RESPONSE_PROTO);
        MAPS_ADDRESS_BOOK_ENTRY_PROTO.addElement(284, 1, null).addElement(277, 2, null);
        SYNCED_DATA_CORPUS_STORAGE_PROTO.addElement(277, 1, null).addElement(1051, 2, SYNC_ITEM);
        SYNCED_DATA_STORAGE_PROTO.addElement(1051, 1, SYNCED_DATA_CORPUS_STORAGE_PROTO);
        SYNCED_DATA_PENDING_QUEUE_PROTO.addElement(533, 1, null).addElement(539, 2, SYNC_REQUEST_PROTO);
        SYNCED_DATA_VIEW_PROTO.addElement(536, 1, null);
        SYNCED_DATA_PREFERENCES_PROTO.addElement(539, 1, SYNCED_DATA_VIEW_PROTO).addElement(539, 2, SYNCED_DATA_STORAGE_PROTO).addElement(539, 3, SYNCED_DATA_PENDING_QUEUE_PROTO);
        EXPORTABLE_ROUTE_NAME.addElement(284, 1, null);
        EXPORTABLE_SIGN_NAME.addElement(284, 1, null);
        EXPORTABLE_SEGMENT.addElement(533, 1, null).addElement(533, 2, null).addElement(1045, 3, null).addElement(1045, 4, null);
        EXPORTABLE_SHARED_SEGMENT.addElement(540, 1, null);
        EXPORTABLE_INTERSECTION.addElement(279, 1, null).addElement(279, 2, null).addElement(540, 3, null).addElement(540, 4, null).addElement(1045, 5, null).addElement(1045, 6, null);
        EXPORTABLE_PGRAPH.addElement(277, 1, null).addElement(1051, 2, null).addElement(1051, 3, null).addElement(1051, 4, null).addElement(1051, 5, null).addElement(1051, 6, null);
    }
}
