package android.icu.text;

class RBBIRuleParseTable {
    static final short doCheckVarDef = 1;
    static final short doDotAny = 2;
    static final short doEndAssign = 3;
    static final short doEndOfRule = 4;
    static final short doEndVariableName = 5;
    static final short doExit = 6;
    static final short doExprCatOperator = 7;
    static final short doExprFinished = 8;
    static final short doExprOrOperator = 9;
    static final short doExprRParen = 10;
    static final short doExprStart = 11;
    static final short doLParen = 12;
    static final short doNOP = 13;
    static final short doNoChain = 14;
    static final short doOptionEnd = 15;
    static final short doOptionStart = 16;
    static final short doReverseDir = 17;
    static final short doRuleChar = 18;
    static final short doRuleError = 19;
    static final short doRuleErrorAssignExpr = 20;
    static final short doScanUnicodeSet = 21;
    static final short doSlash = 22;
    static final short doStartAssign = 23;
    static final short doStartTagValue = 24;
    static final short doStartVariableName = 25;
    static final short doTagDigit = 26;
    static final short doTagExpectedError = 27;
    static final short doTagValue = 28;
    static final short doUnaryOpPlus = 29;
    static final short doUnaryOpQuestion = 30;
    static final short doUnaryOpStar = 31;
    static final short doVariableNameExpectedErr = 32;
    static RBBIRuleTableElement[] gRuleParseStateTable = null;
    static final short kRuleSet_default = 255;
    static final short kRuleSet_digit_char = 128;
    static final short kRuleSet_eof = 252;
    static final short kRuleSet_escaped = 254;
    static final short kRuleSet_name_char = 129;
    static final short kRuleSet_name_start_char = 130;
    static final short kRuleSet_rule_char = 131;
    static final short kRuleSet_white_space = 132;

    static class RBBIRuleTableElement {
        short fAction;
        short fCharClass;
        boolean fNextChar;
        short fNextState;
        short fPushState;
        String fStateName;

        RBBIRuleTableElement(short a, int cc, int ns, int ps, boolean nc, String sn) {
            this.fAction = a;
            this.fCharClass = (short) cc;
            this.fNextState = (short) ns;
            this.fPushState = (short) ps;
            this.fNextChar = nc;
            this.fStateName = sn;
        }
    }

    RBBIRuleParseTable() {
    }

    static {
        RBBIRuleTableElement rBBIRuleTableElement = new RBBIRuleTableElement(13, 0, 0, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement2 = new RBBIRuleTableElement(11, 254, 29, 9, false, "start");
        RBBIRuleTableElement rBBIRuleTableElement3 = new RBBIRuleTableElement(13, 132, 1, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement4 = new RBBIRuleTableElement(14, 94, 12, 9, true, null);
        RBBIRuleTableElement rBBIRuleTableElement5 = new RBBIRuleTableElement(11, 36, 88, 98, false, null);
        RBBIRuleTableElement rBBIRuleTableElement6 = new RBBIRuleTableElement(13, 33, 19, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement7 = new RBBIRuleTableElement(13, 59, 1, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement8 = new RBBIRuleTableElement(13, 252, 0, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement9 = new RBBIRuleTableElement(11, 255, 29, 9, false, null);
        RBBIRuleTableElement rBBIRuleTableElement10 = new RBBIRuleTableElement(4, 59, 1, 0, true, "break-rule-end");
        RBBIRuleTableElement rBBIRuleTableElement11 = new RBBIRuleTableElement(13, 132, 9, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement12 = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement13 = new RBBIRuleTableElement(11, 254, 29, 0, false, "start-after-caret");
        RBBIRuleTableElement rBBIRuleTableElement14 = new RBBIRuleTableElement(13, 132, 12, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement15 = new RBBIRuleTableElement(doRuleError, 94, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement16 = new RBBIRuleTableElement(11, 36, 88, 37, false, null);
        RBBIRuleTableElement rBBIRuleTableElement17 = new RBBIRuleTableElement(doRuleError, 59, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement18 = new RBBIRuleTableElement(doRuleError, 252, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement19 = new RBBIRuleTableElement(11, 255, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement20 = new RBBIRuleTableElement(13, 33, 21, 0, true, "rev-option");
        RBBIRuleTableElement rBBIRuleTableElement21 = new RBBIRuleTableElement(17, 255, 28, 9, false, null);
        RBBIRuleTableElement rBBIRuleTableElement22 = new RBBIRuleTableElement(16, 130, 23, 0, true, "option-scan1");
        RBBIRuleTableElement rBBIRuleTableElement23 = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement24 = new RBBIRuleTableElement(13, 129, 23, 0, true, "option-scan2");
        RBBIRuleTableElement rBBIRuleTableElement25 = new RBBIRuleTableElement(15, 255, 25, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement26 = new RBBIRuleTableElement(13, 59, 1, 0, true, "option-scan3");
        RBBIRuleTableElement rBBIRuleTableElement27 = new RBBIRuleTableElement(13, 132, 25, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement28 = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement29 = new RBBIRuleTableElement(11, 255, 29, 9, false, "reverse-rule");
        RBBIRuleTableElement rBBIRuleTableElement30 = new RBBIRuleTableElement(doRuleChar, 254, 38, 0, true, "term");
        RBBIRuleTableElement rBBIRuleTableElement31 = new RBBIRuleTableElement(13, 132, 29, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement32 = new RBBIRuleTableElement(doRuleChar, 131, 38, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement33 = new RBBIRuleTableElement(13, 91, 94, 38, false, null);
        RBBIRuleTableElement rBBIRuleTableElement34 = new RBBIRuleTableElement(12, 40, 29, 38, true, null);
        RBBIRuleTableElement rBBIRuleTableElement35 = new RBBIRuleTableElement(13, 36, 88, 37, false, null);
        RBBIRuleTableElement rBBIRuleTableElement36 = new RBBIRuleTableElement(2, 46, 38, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement37 = new RBBIRuleTableElement(doRuleError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement38 = new RBBIRuleTableElement(1, 255, 38, 0, false, "term-var-ref");
        RBBIRuleTableElement rBBIRuleTableElement39 = new RBBIRuleTableElement(13, 132, 38, 0, true, "expr-mod");
        RBBIRuleTableElement rBBIRuleTableElement40 = new RBBIRuleTableElement(doUnaryOpStar, 42, 43, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement41 = new RBBIRuleTableElement(doUnaryOpPlus, 43, 43, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement42 = new RBBIRuleTableElement(doUnaryOpQuestion, 63, 43, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement43 = new RBBIRuleTableElement(13, 255, 43, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement44 = new RBBIRuleTableElement(7, 254, 29, 0, false, "expr-cont");
        RBBIRuleTableElement rBBIRuleTableElement45 = new RBBIRuleTableElement(13, 132, 43, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement46 = new RBBIRuleTableElement(7, 131, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement47 = new RBBIRuleTableElement(7, 91, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement48 = new RBBIRuleTableElement(7, 40, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement49 = new RBBIRuleTableElement(7, 36, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement50 = new RBBIRuleTableElement(7, 46, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement51 = new RBBIRuleTableElement(7, 47, 55, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement52 = new RBBIRuleTableElement(7, 123, 67, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement53 = new RBBIRuleTableElement(9, 124, 29, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement54 = new RBBIRuleTableElement(10, 41, 255, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement55 = new RBBIRuleTableElement(8, 255, 255, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement56 = new RBBIRuleTableElement(doSlash, 47, 57, 0, true, "look-ahead");
        RBBIRuleTableElement rBBIRuleTableElement57 = new RBBIRuleTableElement(13, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement58 = new RBBIRuleTableElement(7, 254, 29, 0, false, "expr-cont-no-slash");
        RBBIRuleTableElement rBBIRuleTableElement59 = new RBBIRuleTableElement(13, 132, 43, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement60 = new RBBIRuleTableElement(7, 131, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement61 = new RBBIRuleTableElement(7, 91, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement62 = new RBBIRuleTableElement(7, 40, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement63 = new RBBIRuleTableElement(7, 36, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement64 = new RBBIRuleTableElement(7, 46, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement65 = new RBBIRuleTableElement(9, 124, 29, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement66 = new RBBIRuleTableElement(10, 41, 255, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement67 = new RBBIRuleTableElement(8, 255, 255, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement68 = new RBBIRuleTableElement(13, 132, 67, 0, true, "tag-open");
        RBBIRuleTableElement rBBIRuleTableElement69 = new RBBIRuleTableElement(doStartTagValue, 128, 70, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement70 = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement71 = new RBBIRuleTableElement(13, 132, 74, 0, true, "tag-value");
        RBBIRuleTableElement rBBIRuleTableElement72 = new RBBIRuleTableElement(13, 125, 74, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement73 = new RBBIRuleTableElement(doTagDigit, 128, 70, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement74 = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement75 = new RBBIRuleTableElement(13, 132, 74, 0, true, "tag-close");
        RBBIRuleTableElement rBBIRuleTableElement76 = new RBBIRuleTableElement(doTagValue, 125, 77, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement77 = new RBBIRuleTableElement(doTagExpectedError, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement78 = new RBBIRuleTableElement(7, 254, 29, 0, false, "expr-cont-no-tag");
        RBBIRuleTableElement rBBIRuleTableElement79 = new RBBIRuleTableElement(13, 132, 77, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement80 = new RBBIRuleTableElement(7, 131, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement81 = new RBBIRuleTableElement(7, 91, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement82 = new RBBIRuleTableElement(7, 40, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement83 = new RBBIRuleTableElement(7, 36, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement84 = new RBBIRuleTableElement(7, 46, 29, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement85 = new RBBIRuleTableElement(7, 47, 55, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement86 = new RBBIRuleTableElement(9, 124, 29, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement87 = new RBBIRuleTableElement(10, 41, 255, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement88 = new RBBIRuleTableElement(8, 255, 255, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement89 = new RBBIRuleTableElement(doStartVariableName, 36, 90, 0, true, "scan-var-name");
        RBBIRuleTableElement rBBIRuleTableElement90 = new RBBIRuleTableElement(13, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement91 = new RBBIRuleTableElement(13, 130, 92, 0, true, "scan-var-start");
        RBBIRuleTableElement rBBIRuleTableElement92 = new RBBIRuleTableElement(32, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement93 = new RBBIRuleTableElement(13, 129, 92, 0, true, "scan-var-body");
        RBBIRuleTableElement rBBIRuleTableElement94 = new RBBIRuleTableElement(5, 255, 255, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement95 = new RBBIRuleTableElement(doScanUnicodeSet, 91, 255, 0, true, "scan-unicode-set");
        RBBIRuleTableElement rBBIRuleTableElement96 = new RBBIRuleTableElement(doScanUnicodeSet, 112, 255, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement97 = new RBBIRuleTableElement(doScanUnicodeSet, 80, 255, 0, true, null);
        RBBIRuleTableElement rBBIRuleTableElement98 = new RBBIRuleTableElement(13, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement99 = new RBBIRuleTableElement(13, 132, 98, 0, true, "assign-or-rule");
        RBBIRuleTableElement rBBIRuleTableElement100 = new RBBIRuleTableElement(doStartAssign, 61, 29, 101, true, null);
        RBBIRuleTableElement rBBIRuleTableElement101 = new RBBIRuleTableElement(13, 255, 37, 9, false, null);
        RBBIRuleTableElement rBBIRuleTableElement102 = new RBBIRuleTableElement(3, 59, 1, 0, true, "assign-end");
        RBBIRuleTableElement rBBIRuleTableElement103 = new RBBIRuleTableElement(doRuleErrorAssignExpr, 255, 103, 0, false, null);
        RBBIRuleTableElement rBBIRuleTableElement104 = new RBBIRuleTableElement(6, 255, 103, 0, true, "errorDeath");
        gRuleParseStateTable = new RBBIRuleTableElement[]{rBBIRuleTableElement, rBBIRuleTableElement2, rBBIRuleTableElement3, rBBIRuleTableElement4, rBBIRuleTableElement5, rBBIRuleTableElement6, rBBIRuleTableElement7, rBBIRuleTableElement8, rBBIRuleTableElement9, rBBIRuleTableElement10, rBBIRuleTableElement11, rBBIRuleTableElement12, rBBIRuleTableElement13, rBBIRuleTableElement14, rBBIRuleTableElement15, rBBIRuleTableElement16, rBBIRuleTableElement17, rBBIRuleTableElement18, rBBIRuleTableElement19, rBBIRuleTableElement20, rBBIRuleTableElement21, rBBIRuleTableElement22, rBBIRuleTableElement23, rBBIRuleTableElement24, rBBIRuleTableElement25, rBBIRuleTableElement26, rBBIRuleTableElement27, rBBIRuleTableElement28, rBBIRuleTableElement29, rBBIRuleTableElement30, rBBIRuleTableElement31, rBBIRuleTableElement32, rBBIRuleTableElement33, rBBIRuleTableElement34, rBBIRuleTableElement35, rBBIRuleTableElement36, rBBIRuleTableElement37, rBBIRuleTableElement38, rBBIRuleTableElement39, rBBIRuleTableElement40, rBBIRuleTableElement41, rBBIRuleTableElement42, rBBIRuleTableElement43, rBBIRuleTableElement44, rBBIRuleTableElement45, rBBIRuleTableElement46, rBBIRuleTableElement47, rBBIRuleTableElement48, rBBIRuleTableElement49, rBBIRuleTableElement50, rBBIRuleTableElement51, rBBIRuleTableElement52, rBBIRuleTableElement53, rBBIRuleTableElement54, rBBIRuleTableElement55, rBBIRuleTableElement56, rBBIRuleTableElement57, rBBIRuleTableElement58, rBBIRuleTableElement59, rBBIRuleTableElement60, rBBIRuleTableElement61, rBBIRuleTableElement62, rBBIRuleTableElement63, rBBIRuleTableElement64, rBBIRuleTableElement65, rBBIRuleTableElement66, rBBIRuleTableElement67, rBBIRuleTableElement68, rBBIRuleTableElement69, rBBIRuleTableElement70, rBBIRuleTableElement71, rBBIRuleTableElement72, rBBIRuleTableElement73, rBBIRuleTableElement74, rBBIRuleTableElement75, rBBIRuleTableElement76, rBBIRuleTableElement77, rBBIRuleTableElement78, rBBIRuleTableElement79, rBBIRuleTableElement80, rBBIRuleTableElement81, rBBIRuleTableElement82, rBBIRuleTableElement83, rBBIRuleTableElement84, rBBIRuleTableElement85, rBBIRuleTableElement86, rBBIRuleTableElement87, rBBIRuleTableElement88, rBBIRuleTableElement89, rBBIRuleTableElement90, rBBIRuleTableElement91, rBBIRuleTableElement92, rBBIRuleTableElement93, rBBIRuleTableElement94, rBBIRuleTableElement95, rBBIRuleTableElement96, rBBIRuleTableElement97, rBBIRuleTableElement98, rBBIRuleTableElement99, rBBIRuleTableElement100, rBBIRuleTableElement101, rBBIRuleTableElement102, rBBIRuleTableElement103, rBBIRuleTableElement104};
    }
}
