package com.android.server.location;

public class HwGnssLogHandlerMsgID {
    public static final int ADDBATCHINGSTATUS = 16;
    public static final int ADDGEOFENCESTATUS = 15;
    public static final int BCM_GNSS_ERR_MSG = 22;
    public static final int BCM_GNSS_MANAGER_INIT = 21;
    public static final int GPS_FREEZE = 104;
    public static final int IAWARE_ADD = 102;
    public static final int IAWARE_REMOVE = 103;
    public static final int IDLE_CHANGE = 105;
    public static final int INITGPS = 1;
    public static final int INJECT_EXTRA_PARAM = 24;
    public static final int INJECT_NTP_TIME_PARAM = 27;
    public static final int JASON_EXCEPTION_BODY = 26;
    public static final int LOCATION_SETTINGS_SWITCH_OFF = 28;
    public static final int LOGEVENT = 25;
    public static final int NETWORK_LOCATION_APKINFO = 106;
    public static final int NLP_STATUS = 29;
    public static final int NTP_ADDRESS_MSG = 23;
    public static final int OPENGPSSWITCH = 14;
    public static final int PERMISSIONERR = 13;
    public static final int QUICK_GPS_PARAMETER = 30;
    public static final int REQUEST_START = 100;
    public static final int REQUEST_STOP = 101;
    public static final int STARTGPS = 2;
    public static final int STOPGPS = 5;
    public static final int UPDATEAGPSSTATE = 4;
    public static final int UPDATEAPKINFO = 31;
    public static final int UPDATEAPKNAME = 18;
    public static final int UPDATEBINDERRORTIME = 20;
    public static final int UPDATEGPSRUNSTATE = 6;
    public static final int UPDATELOCATION = 8;
    public static final int UPDATELOSTPOSITION = 17;
    public static final int UPDATENETWORKLOCATION = 0;
    public static final int UPDATENETWORKSTATE = 3;
    public static final int UPDATENTPDLOADSTATUS = 11;
    public static final int UPDATENTPERRORTIME = 19;
    public static final int UPDATESETPOSMODE = 12;
    public static final int UPDATESVSTATUS = 9;
    public static final int UPDATEXTRA = 7;
    public static final int UPDATEXTRADLOADSTATUS = 10;
}
