package ohos.com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_it extends ListResourceBundle {
    @Override // java.util.ListResourceBundle
    public Object[][] getContents() {
        return new Object[][]{new Object[]{BasisLibrary.RUN_TIME_INTERNAL_ERR, "Errore interno in runtime in ''{0}''"}, new Object[]{BasisLibrary.RUN_TIME_COPY_ERR, "Errore in runtime durante l'esecuzione di <xsl:copy>."}, new Object[]{"DATA_CONVERSION_ERR", "Conversione non valida da ''{0}'' a ''{1}''."}, new Object[]{BasisLibrary.EXTERNAL_FUNC_ERR, "Funzione esterna ''{0}'' non supportata da XSLTC."}, new Object[]{BasisLibrary.EQUALITY_EXPR_ERR, "Tipo di argomento sconosciuto nell'espressione di uguaglianza."}, new Object[]{BasisLibrary.INVALID_ARGUMENT_ERR, "Tipo di argomento ''{0}'' non valido nella chiamata a ''{1}''"}, new Object[]{BasisLibrary.FORMAT_NUMBER_ERR, "Tentativo di formattare il numero ''{0}'' mediante il pattern ''{1}''."}, new Object[]{BasisLibrary.ITERATOR_CLONE_ERR, "Impossibile duplicare l''iteratore ''{0}''."}, new Object[]{BasisLibrary.AXIS_SUPPORT_ERR, "Iteratore per l''asse ''{0}'' non supportato."}, new Object[]{BasisLibrary.TYPED_AXIS_SUPPORT_ERR, "Iteratore per l''asse immesso ''{0}'' non supportato."}, new Object[]{"STRAY_ATTRIBUTE_ERR", "Attributo ''{0}'' al di fuori dell''elemento."}, new Object[]{BasisLibrary.STRAY_NAMESPACE_ERR, "Dichiarazione dello spazio di nomi ''{0}''=''{1}'' al di fuori dell''elemento."}, new Object[]{BasisLibrary.NAMESPACE_PREFIX_ERR, "Lo spazio di nomi per il prefisso ''{0}'' non è stato dichiarato."}, new Object[]{BasisLibrary.DOM_ADAPTER_INIT_ERR, "DOMAdapter creato utilizzando il tipo errato di DOM di origine."}, new Object[]{BasisLibrary.PARSER_DTD_SUPPORT_ERR, "Il parser SAX in uso non gestisce gli eventi di dichiarazione DTD."}, new Object[]{BasisLibrary.NAMESPACES_SUPPORT_ERR, "Il parser SAX in uso non supporta gli spazi di nomi XML."}, new Object[]{BasisLibrary.CANT_RESOLVE_RELATIVE_URI_ERR, "Impossibile risolvere il riferimento URI ''{0}''."}, new Object[]{"UNSUPPORTED_XSL_ERR", "Elemento XSL \"{0}\" non supportato"}, new Object[]{"UNSUPPORTED_EXT_ERR", "Estensione XSLTC ''{0}'' non riconosciuta"}, new Object[]{BasisLibrary.UNKNOWN_TRANSLET_VERSION_ERR, "Il translet specificato ''{0}'' è stato creato utilizzando una versione di XSLTC più recente di quella della fase di runtime XSLTC in uso. Ricompilare il foglio di stile o utilizzare una versione più recente di XSLTC per eseguire questo translet."}, new Object[]{"INVALID_QNAME_ERR", "Un attributo il cui valore deve essere un QName contiene il valore ''{0}''"}, new Object[]{"INVALID_NCNAME_ERR", "Un attributo il cui valore deve essere un NCName contiene il valore ''{0}''"}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_FUNCTION_ERR, "Non è consentito utilizzare la funzione di estensione ''{0}'' se la funzione di elaborazione sicura è impostata su true."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_ELEMENT_ERR, "Non è consentito utilizzare l''elemento di estensione ''{0}'' se la funzione di elaborazione sicura è impostata su true."}};
    }
}
