package ohos.com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_ko extends ListResourceBundle {
    @Override // java.util.ListResourceBundle
    public Object[][] getContents() {
        return new Object[][]{new Object[]{BasisLibrary.RUN_TIME_INTERNAL_ERR, "''{0}''에 런타임 내부 오류가 있습니다."}, new Object[]{BasisLibrary.RUN_TIME_COPY_ERR, "<xsl:copy>를 실행하는 중 런타임 오류가 발생했습니다."}, new Object[]{"DATA_CONVERSION_ERR", "''{0}''에서 ''{1}''(으)로의 변환이 부적합합니다."}, new Object[]{BasisLibrary.EXTERNAL_FUNC_ERR, "XSLTC는 외부 함수 ''{0}''을(를) 지원하지 않습니다."}, new Object[]{BasisLibrary.EQUALITY_EXPR_ERR, "동등성 표현식에 알 수 없는 인수 유형이 있습니다."}, new Object[]{BasisLibrary.INVALID_ARGUMENT_ERR, "''{1}''에 대한 호출에 부적합한 인수 유형 ''{0}''이(가) 있습니다."}, new Object[]{BasisLibrary.FORMAT_NUMBER_ERR, "''{1}'' 패턴을 사용하여 ''{0}'' 숫자의 형식을 지정하려고 시도하는 중입니다."}, new Object[]{BasisLibrary.ITERATOR_CLONE_ERR, "''{0}'' 이터레이터를 복제할 수 없습니다."}, new Object[]{BasisLibrary.AXIS_SUPPORT_ERR, "''{0}'' 축에 대한 이터레이터는 지원되지 않습니다."}, new Object[]{BasisLibrary.TYPED_AXIS_SUPPORT_ERR, "입력된 축 ''{0}''에 대한 이터레이터는 지원되지 않습니다."}, new Object[]{"STRAY_ATTRIBUTE_ERR", "''{0}'' 속성이 요소에 포함되어 있지 않습니다."}, new Object[]{BasisLibrary.STRAY_NAMESPACE_ERR, "네임스페이스 선언 ''{0}''=''{1}''이(가) 요소에 포함되어 있지 않습니다."}, new Object[]{BasisLibrary.NAMESPACE_PREFIX_ERR, "''{0}'' 접두어에 대한 네임스페이스가 선언되지 않았습니다."}, new Object[]{BasisLibrary.DOM_ADAPTER_INIT_ERR, "소스 DOM의 잘못된 유형을 사용하여 DOMAdapter가 생성되었습니다."}, new Object[]{BasisLibrary.PARSER_DTD_SUPPORT_ERR, "사용 중인 SAX 구문 분석기가 DTD 선언 이벤트를 처리하지 않습니다."}, new Object[]{BasisLibrary.NAMESPACES_SUPPORT_ERR, "사용 중인 SAX 구문 분석기가 XML 네임스페이스를 지원하지 않습니다."}, new Object[]{BasisLibrary.CANT_RESOLVE_RELATIVE_URI_ERR, "URI 참조 ''{0}''을(를) 분석할 수 없습니다."}, new Object[]{"UNSUPPORTED_XSL_ERR", "''{0}''은(는) 지원되지 않는 XSL 요소입니다."}, new Object[]{"UNSUPPORTED_EXT_ERR", "''{0}''은(는) 알 수 없는 XSLTC 확장입니다."}, new Object[]{BasisLibrary.UNKNOWN_TRANSLET_VERSION_ERR, "지정된 translet ''{0}''이(가) 사용 중인 XSLTC 런타임 버전보다 최신의 XSLTC 버전을 사용하여 생성되었습니다. 이 translet을 실행하려면 스타일시트를 재컴파일하거나 최신 XSLTC 버전을 사용해야 합니다."}, new Object[]{"INVALID_QNAME_ERR", "값이 QName이어야 하는 속성의 값이 ''{0}''입니다."}, new Object[]{"INVALID_NCNAME_ERR", "값이 NCName이어야 하는 속성의 값이 ''{0}''입니다."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_FUNCTION_ERR, "보안 처리 기능이 true로 설정된 경우 확장 함수 ''{0}''을(를) 사용할 수 없습니다."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_ELEMENT_ERR, "보안 처리 기능이 true로 설정된 경우 확장 요소 ''{0}''을(를) 사용할 수 없습니다."}};
    }
}
