package ohos.com.sun.org.apache.xalan.internal.xsltc.runtime;

import java.util.ListResourceBundle;

public class ErrorMessages_es extends ListResourceBundle {
    @Override // java.util.ListResourceBundle
    public Object[][] getContents() {
        return new Object[][]{new Object[]{BasisLibrary.RUN_TIME_INTERNAL_ERR, "Error interno de tiempo de ejecución en ''{0}''"}, new Object[]{BasisLibrary.RUN_TIME_COPY_ERR, "Error de tiempo de ejecución al ejecutar <xsl:copy>."}, new Object[]{"DATA_CONVERSION_ERR", "Conversión no válida de ''{0}'' a ''{1}''."}, new Object[]{BasisLibrary.EXTERNAL_FUNC_ERR, "Función externa ''{0}'' no soportada por XSLTC."}, new Object[]{BasisLibrary.EQUALITY_EXPR_ERR, "Tipo de argumento desconocido en la expresión de igualdad."}, new Object[]{BasisLibrary.INVALID_ARGUMENT_ERR, "Tipo de argumento ''{0}'' no válido en la llamada a ''{1}''"}, new Object[]{BasisLibrary.FORMAT_NUMBER_ERR, "Intentando formatear número ''{0}'' mediante el patrón ''{1}''."}, new Object[]{BasisLibrary.ITERATOR_CLONE_ERR, "No se puede clonar el iterador ''{0}''."}, new Object[]{BasisLibrary.AXIS_SUPPORT_ERR, "El iterador para el eje ''{0}'' no está soportado."}, new Object[]{BasisLibrary.TYPED_AXIS_SUPPORT_ERR, "El iterador para el eje introducido ''{0}'' no está soportado."}, new Object[]{"STRAY_ATTRIBUTE_ERR", "El atributo ''{0}'' está fuera del elemento."}, new Object[]{BasisLibrary.STRAY_NAMESPACE_ERR, "Declaración del espacio de nombres ''{0}''=''{1}'' fuera del elemento."}, new Object[]{BasisLibrary.NAMESPACE_PREFIX_ERR, "No se ha declarado el espacio de nombres para el prefijo ''{0}''."}, new Object[]{BasisLibrary.DOM_ADAPTER_INIT_ERR, "Se ha creado DOMAdapter mediante un tipo incorrecto de DOM de origen."}, new Object[]{BasisLibrary.PARSER_DTD_SUPPORT_ERR, "El analizador SAX que está utilizando no maneja los eventos de declaración DTD."}, new Object[]{BasisLibrary.NAMESPACES_SUPPORT_ERR, "El analizador SAX que está utilizando no soporta los espacios de nombres XML."}, new Object[]{BasisLibrary.CANT_RESOLVE_RELATIVE_URI_ERR, "No se ha podido resolver la referencia al URI ''{0}''."}, new Object[]{"UNSUPPORTED_XSL_ERR", "Elemento ''{0}'' de XSL no soportado"}, new Object[]{"UNSUPPORTED_EXT_ERR", "Extensión ''{0}'' de XSLTC no reconocida"}, new Object[]{BasisLibrary.UNKNOWN_TRANSLET_VERSION_ERR, "El translet especificado, ''{0}'' se ha creado con una versión de XSLTC más reciente que la versión del tiempo de ejecución de XSLTC que se está utilizando. Debe volver a compilar la hoja de estilo o utilizar una versión más reciente de XSLTC para ejecutar este translet."}, new Object[]{"INVALID_QNAME_ERR", "Un atributo cuyo valor debe ser un QName tenía el valor ''{0}''"}, new Object[]{"INVALID_NCNAME_ERR", "Un atributo cuyo valor debe ser un NCName tenía el valor ''{0}''"}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_FUNCTION_ERR, "El uso de la función de extensión ''{0}'' no está permitido cuando la función de procesamiento seguro se ha definido en true."}, new Object[]{BasisLibrary.UNALLOWED_EXTENSION_ELEMENT_ERR, "El uso del elemento de extensión ''{0}'' no está permitido cuando la función de procesamiento seguro se ha definido en true."}};
    }
}
