package com.android.server.wifi;

public class HwWifiDFT2StabilityStat {
    private static final int GAME_BOOST_SIGNAL = 4;
    public int mDsStatSuccNum;
    public int mDsStatWebDelay;
    public short mExtendMaxTemCnt;
    public int[] mGameLag = new int[4];
    public int mabDisconnCnt;
    public short maccWebFailCnt;
    public short maccWebSlowCnt;
    public int mcloseCnt;
    public int mcloseDura;
    public int mcloseSucCnt;
    public int mconnectTotalCnt;
    public int mconnectedCnt;
    public int mconnectedDura;
    public int mconnectingDura;
    public int mdisCheckAbCnt;
    public int mdisCheckFailCnt;
    public int mdisCheckL1;
    public int mdisCheckL2;
    public int mdisCheckL3;
    public int mdisconnCnt;
    public int mevaluFailCnt;
    public int mevaluSuccCnt;
    public int mevaluTimeL1;
    public int mevaluTimeL2;
    public int mevaluTimeL3;
    public int mgameCnt;
    public String mgameName;
    public int misScanAlwaysAvailble;
    public int misWifiNotifationOn;
    public int misWifiProOn;
    public short mmaxTem;
    public short mminDutyCycleCnt;
    public int mmobileTotalConnDura;
    public int mmobileTotalTraffic;
    public int mnoNetByTcp;
    public int mnoNetByUdp;
    public int mopenCnt;
    public int mopenDura;
    public int mopenSucCnt;
    public int mrepeaterWorkDura;
    public byte mrepeterClientMaxCnt;
    public byte mrepeterConnFailCnt;
    public int mrepeterDiffFreqDura;
    public int mrepeterOpenCnt;
    public int mrepeterOpenSuccCnt;
    public int mscanAlwaysSwCnt;
    public short mtemCtrlCnt;
    public int mtemCtrlDura;
    public int mwebFailDura;
    public int mwebSlowDura;
    public int mwifiNotifationSwCnt;
    public int mwifiProSwCnt;
    public byte mwifiSleepPolicy;
    public int mwifiSleepSwCnt;
    public byte mwifiToPDP;
    public int mwifiToPDPSwCnt;
    public int mwlanTotalConnDura;
    public int mwlanTotalTraffic;

    public HwWifiDFT2StabilityStat() {
        resetStat();
    }

    public void resetStat() {
        this.mopenCnt = 0;
        this.mopenSucCnt = 0;
        this.mopenDura = 0;
        this.mcloseCnt = 0;
        this.mcloseSucCnt = 0;
        this.mcloseDura = 0;
        this.mrepeterOpenCnt = 0;
        this.mrepeterOpenSuccCnt = 0;
        this.mrepeterClientMaxCnt = (byte) 0;
        this.mrepeterConnFailCnt = (byte) 0;
        this.mconnectedCnt = 0;
        this.mconnectTotalCnt = 0;
        this.mabDisconnCnt = 0;
        this.mdisconnCnt = 0;
        this.mconnectedDura = 0;
        this.mwebFailDura = 0;
        this.mwebSlowDura = 0;
        this.mconnectingDura = 0;
        this.maccWebFailCnt = (short) 0;
        this.maccWebSlowCnt = (short) 0;
        this.misWifiProOn = 0;
        this.mwifiProSwCnt = 0;
        this.misScanAlwaysAvailble = 0;
        this.mscanAlwaysSwCnt = 0;
        this.misWifiNotifationOn = 0;
        this.mwifiNotifationSwCnt = 0;
        this.mwifiSleepPolicy = (byte) 0;
        this.mwifiSleepSwCnt = 0;
        this.mwifiToPDP = (byte) 0;
        this.mwifiToPDPSwCnt = 0;
        this.mwlanTotalConnDura = 0;
        this.mwlanTotalTraffic = 0;
        this.mmobileTotalTraffic = 0;
        this.mmobileTotalConnDura = 0;
        this.mrepeaterWorkDura = 0;
        this.mrepeterDiffFreqDura = 0;
        this.mDsStatWebDelay = 0;
        this.mDsStatSuccNum = 0;
        this.mnoNetByTcp = 0;
        this.mnoNetByUdp = 0;
        this.mdisCheckAbCnt = 0;
        this.mdisCheckFailCnt = 0;
        this.mdisCheckL1 = 0;
        this.mdisCheckL2 = 0;
        this.mdisCheckL3 = 0;
        this.mevaluSuccCnt = 0;
        this.mevaluFailCnt = 0;
        this.mevaluTimeL1 = 0;
        this.mevaluTimeL2 = 0;
        this.mevaluTimeL3 = 0;
        this.mgameCnt = 0;
        this.mgameName = "";
        this.mtemCtrlCnt = (short) 0;
        this.mtemCtrlDura = 0;
        this.mmaxTem = (short) 0;
        this.mminDutyCycleCnt = (short) 0;
        this.mExtendMaxTemCnt = (short) 0;
    }
}
