package com.android.server.wifi;

public class HwWifiDFT2StabilitySsidStat {
    private static final int MSS_REASON_CNT = 3;
    private static final int TX_BOOST_SIGNAL = 5;
    public int mABSAssocCnt;
    public int mABSAssocFailCnt;
    public int mABSMimoDura;
    public int mABSMimoScreenOnDura;
    public int mABSSisoDura;
    public int mABSSisoScreenOnDura;
    public String mAPSsid;
    public int mDnsCount;
    public int mDnsDelayL1;
    public int mDnsDelayL2;
    public int mDnsDelayL3;
    public int mDnsDelayL4;
    public int mDnsDelayL5;
    public int mDnsDelayL6;
    public int mDnsFailCount;
    public int mDnsIpv6TimeOut;
    public int mDnsTotaldelay;
    public int mDsDelayL1;
    public int mDsDelayL2;
    public int mDsDelayL3;
    public int mDsDelayL4;
    public int mDsDelayL5;
    public int mDsDelayL6;
    public int mDsRTTL1;
    public int mDsRTTL2;
    public int mDsRTTL3;
    public int mDsRTTL4;
    public int mDsRTTL5;
    public int mDsStatFailNum;
    public int mDsStatNoAckNum;
    public int mDsStatRTT;
    public int mDsStatSuccNum;
    public int mDsStatTcpTotalNum;
    public int mDsStatTotalNum;
    public int mDsStatWebDelay;
    public String mMAC;
    public String mMACHASH;
    public int mMaxspeed;
    public int mMssFailCnt;
    public int[] mMssFailCntArray;
    public int mMssReasonCode;
    public int mMssSuccCnt;
    public int[] mMssSuccCntArray;
    public int mOnSceenConnSucDura;
    public int mOnSceenReConnCnt;
    public int mOnScreenAbDisconnCnt;
    public int mOnScreenConnCnt;
    public int mOnScreenConnSucCnt;
    public int mOnScreenDisconnCnt;
    public int mRSSI;
    public String mSSID;
    public int[] mTxBoostOffRTT;
    public int[] mTxBoostOffRTTCnt;
    public int[] mTxBoostOffTxRetry;
    public int[] mTxBoostOfftxBad;
    public int[] mTxBoostOfftxGood;
    public int[] mTxBoostOnRTT;
    public int[] mTxBoostOnRTTCnt;
    public int[] mTxBoostOnTxRetry;
    public int[] mTxBoostOntxBad;
    public int[] mTxBoostOntxGood;
    public int mabDisconnCnt;
    public int maccWebCnt;
    public short maccWebFailCnt;
    public int maccWebFailPortal;
    public int maccWebReDHCPFailPortal;
    public int maccWebRoamFailPortal;
    public short maccWebSlowCnt;
    public int maccWebSucCnt;
    public String mapVendorInfo;
    public int mappDisabledAbCnt;
    public int mappDisabledScSucCnt;
    public int marpReassocOkCnt;
    public int marpUnreachCnt;
    public int massocByABSCnt;
    public int massocCnt;
    public int massocDura;
    public int massocRejAbCnt;
    public int massocRejFullCnt;
    public int massocRejScSucCnt;
    public int massocSucCnt;
    public int mauthCnt;
    public int mauthDura;
    public int mauthFailAbCnt;
    public int mauthFailScSucCnt;
    public int mauthSucCnt;
    public byte mbandWidth;
    public int mblackListAbCnt;
    public int mblackListScSucCnt;
    public int mconnectTotalCnt;
    public int mconnectedCnt;
    public int mconnectedDura;
    public int mconnectingDura;
    public int mdhcpDura;
    public int mdhcpFailAbCnt;
    public int mdhcpFailScSucCnt;
    public int mdhcpFailStaticScSucCnt;
    public int mdhcpRenewCnt;
    public int mdhcpRenewDura;
    public int mdhcpRenewSucCnt;
    public int mdhcpStaticSucCnt;
    public int mdhcpSucCnt;
    public int mdisconnCnt;
    public int mdnsAbnormalCnt;
    public int mdnsAvgTime;
    public int mdnsParseFailCnt;
    public int mdnsReqCnt;
    public int mdnsReqFail;
    public int mdnsResetScSucCnt;
    public int mdnsScSucCnt;
    public String meap;
    public int mfirstConnInetFailCnt;
    public int mfirstConnInetFailDura;
    public short mfrequency;
    public int mgatewayAbCnt;
    public int mgoodReConnCnt;
    public int mgoodReConnSucCnt;
    public byte mgwIpCnt;
    public byte mgwMacCnt;
    public int mgwResetScSucCnt;
    public int minvalidIpScAbnormalCnt;
    public int minvalidIpScSuccCnt;
    public int mipAutoCnt;
    public int mipDhcpCnt;
    public int mipStaticCnt;
    public byte misMobleAP;
    public String mkeyMgmt;
    public short mlinkspeed;
    public int mnoUserProcRunCnt;
    public int monlyTxNoRxCnt;
    public byte mproxySetting;
    public byte mpublicEssCnt;
    public int mreDHCPAccWebSuccCnt;
    public int mreDhcpScSucCnt;
    public int mreassScSucCnt;
    public int mreassocScConnFailCnt;
    public int mrekeyCnt;
    public int mrekeyDura;
    public int mrekeySucCnt;
    public int mresetScConnFailCnt;
    public int mresetScSuccCnt;
    public int mroamAccWebSucCnt;
    public int mroamCnt;
    public int mroamDura;
    public int mroamSucCnt;
    public int mroamingAbCnt;
    public int mroamingResetScSucCnt;
    public int mrouterDisplayNoInternetCnt;
    public String mrouterModel;
    public int mrouterUnreachableCnt;
    public int mrssiAvg;
    public int mstaticIpConflictedScSucCnt;
    public int mstaticIpScSucCnt;
    public int mtcpRxAbCnt;
    public int muserEnableStaticIpCnt;
    public int mweakReConnCnt;
    public int mweakReConnSucCnt;
    public int mwebFailDura;
    public int mwebSlowDura;

    public HwWifiDFT2StabilitySsidStat() {
        resetSsidStat();
    }

    public void resetSsidStat() {
        this.mAPSsid = "";
        this.mpublicEssCnt = (byte) 0;
        this.massocCnt = 0;
        this.massocRejFullCnt = 0;
        this.massocByABSCnt = 0;
        this.massocSucCnt = 0;
        this.mauthCnt = 0;
        this.mauthSucCnt = 0;
        this.mipDhcpCnt = 0;
        this.mdhcpSucCnt = 0;
        this.mipStaticCnt = 0;
        this.mdhcpStaticSucCnt = 0;
        this.mipAutoCnt = 0;
        this.mconnectedCnt = 0;
        this.mconnectTotalCnt = 0;
        this.mabDisconnCnt = 0;
        this.mdisconnCnt = 0;
        this.massocDura = 0;
        this.mauthDura = 0;
        this.mdhcpDura = 0;
        this.mconnectingDura = 0;
        this.mconnectedDura = 0;
        this.mwebFailDura = 0;
        this.mwebSlowDura = 0;
        this.mdnsReqCnt = 0;
        this.mdnsReqFail = 0;
        this.mdnsAvgTime = 0;
        this.mdhcpRenewCnt = 0;
        this.mdhcpRenewSucCnt = 0;
        this.mdhcpRenewDura = 0;
        this.mroamCnt = 0;
        this.mroamSucCnt = 0;
        this.mroamDura = 0;
        this.mrekeyCnt = 0;
        this.mrekeySucCnt = 0;
        this.mrekeyDura = 0;
        this.maccWebFailCnt = (short) 0;
        this.maccWebSlowCnt = (short) 0;
        this.mgwIpCnt = (byte) 0;
        this.mgwMacCnt = (byte) 0;
        this.mrssiAvg = 0;
        this.mgoodReConnCnt = 0;
        this.mgoodReConnSucCnt = 0;
        this.mweakReConnCnt = 0;
        this.mweakReConnSucCnt = 0;
        this.mOnScreenConnCnt = 0;
        this.mOnScreenConnSucCnt = 0;
        this.mOnScreenAbDisconnCnt = 0;
        this.mOnScreenDisconnCnt = 0;
        this.mOnSceenConnSucDura = 0;
        this.mOnSceenReConnCnt = 0;
        this.mdnsAbnormalCnt = 0;
        this.mtcpRxAbCnt = 0;
        this.mroamingAbCnt = 0;
        this.mgatewayAbCnt = 0;
        this.mdnsScSucCnt = 0;
        this.mreDhcpScSucCnt = 0;
        this.mstaticIpScSucCnt = 0;
        this.mreassScSucCnt = 0;
        this.mresetScSuccCnt = 0;
        this.mauthFailAbCnt = 0;
        this.massocRejAbCnt = 0;
        this.mdhcpFailAbCnt = 0;
        this.mappDisabledAbCnt = 0;
        this.mauthFailScSucCnt = 0;
        this.massocRejScSucCnt = 0;
        this.mdhcpFailScSucCnt = 0;
        this.mappDisabledScSucCnt = 0;
        this.mreassocScConnFailCnt = 0;
        this.mresetScConnFailCnt = 0;
        this.mdnsResetScSucCnt = 0;
        this.mroamingResetScSucCnt = 0;
        this.mgwResetScSucCnt = 0;
        this.mblackListScSucCnt = 0;
        this.mblackListAbCnt = 0;
        this.mdhcpFailStaticScSucCnt = 0;
        this.mstaticIpConflictedScSucCnt = 0;
        this.muserEnableStaticIpCnt = 0;
        this.mrouterDisplayNoInternetCnt = 0;
        this.mrouterUnreachableCnt = 0;
        this.minvalidIpScAbnormalCnt = 0;
        this.minvalidIpScSuccCnt = 0;
        this.mapVendorInfo = "";
        this.mMAC = "";
        this.mMACHASH = "";
        this.mSSID = "";
        this.mkeyMgmt = "";
        this.meap = "";
        this.mlinkspeed = (short) 0;
        this.mfrequency = (short) 0;
        this.mRSSI = 0;
        this.misMobleAP = (byte) 0;
        this.mbandWidth = (byte) 0;
        this.mproxySetting = (byte) 0;
        this.maccWebCnt = 0;
        this.maccWebSucCnt = 0;
        this.mfirstConnInetFailDura = 0;
        this.mfirstConnInetFailCnt = 0;
        this.monlyTxNoRxCnt = 0;
        this.mdnsParseFailCnt = 0;
        this.marpUnreachCnt = 0;
        this.marpReassocOkCnt = 0;
        this.mroamAccWebSucCnt = 0;
        this.mreDHCPAccWebSuccCnt = 0;
        this.mnoUserProcRunCnt = 0;
        this.maccWebFailPortal = 0;
        this.maccWebRoamFailPortal = 0;
        this.maccWebReDHCPFailPortal = 0;
        this.mABSAssocCnt = 0;
        this.mABSAssocFailCnt = 0;
        this.mABSMimoDura = 0;
        this.mABSSisoDura = 0;
        this.mABSMimoScreenOnDura = 0;
        this.mABSSisoScreenOnDura = 0;
        this.mMaxspeed = 0;
        this.mDsStatRTT = 0;
        this.mDsStatWebDelay = 0;
        this.mDsStatSuccNum = 0;
        this.mDsStatFailNum = 0;
        this.mDsStatNoAckNum = 0;
        this.mDsStatTotalNum = 0;
        this.mDsStatTcpTotalNum = 0;
        this.mDsDelayL1 = 0;
        this.mDsDelayL2 = 0;
        this.mDsDelayL3 = 0;
        this.mDsDelayL4 = 0;
        this.mDsDelayL5 = 0;
        this.mDsDelayL6 = 0;
        this.mDsRTTL1 = 0;
        this.mDsRTTL2 = 0;
        this.mDsRTTL3 = 0;
        this.mDsRTTL4 = 0;
        this.mDsRTTL5 = 0;
        this.mDnsCount = 0;
        this.mDnsTotaldelay = 0;
        this.mDnsIpv6TimeOut = 0;
        this.mDnsFailCount = 0;
        this.mDnsDelayL1 = 0;
        this.mDnsDelayL2 = 0;
        this.mDnsDelayL3 = 0;
        this.mDnsDelayL4 = 0;
        this.mDnsDelayL5 = 0;
        this.mDnsDelayL6 = 0;
        this.mMssSuccCnt = 0;
        this.mMssFailCnt = 0;
        this.mMssReasonCode = 0;
        this.mTxBoostOnRTT = new int[5];
        this.mTxBoostOnRTTCnt = new int[5];
        this.mTxBoostOntxGood = new int[5];
        this.mTxBoostOntxBad = new int[5];
        this.mTxBoostOnTxRetry = new int[5];
        this.mTxBoostOffRTT = new int[5];
        this.mTxBoostOffRTTCnt = new int[5];
        this.mTxBoostOfftxGood = new int[5];
        this.mTxBoostOfftxBad = new int[5];
        this.mTxBoostOffTxRetry = new int[5];
        this.mrouterModel = "";
        this.mMssSuccCntArray = new int[3];
        this.mMssFailCntArray = new int[3];
    }
}
